Create extract data from schema function
CDCgov/phdi pull request #100
Opened 2022-10-28 12:04 UTC by spencer-skylight

# Description
This PR creates a new function that accepts a tabulation schema, and extracts resources based on the derived search string.

# Additional Changes
The method signature for `extract_data_from_fhir_search_incremental` was updated to specify the correct return type, and the return docstring was also updated.

2022-10-28 15:54 UTC, bamader requested changes
Almost there, I think we just need to align on what the output type of our extractions is going to be (bundle or just a list of resources).

2022-10-28 15:54 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +) -> Tuple[List[dict], str]:
I think my only suggested change is that we standardize all of the return types of all of the extract functions to be the same thing. I.e. any function whose output should be passed to tabulation as input should have the exact same format, so that tabulation can be written with one input type in mind. Currently, that format is a bundle (complete with `entry` field), but this one looks like the first parameter is a list whose tuples already have the resources extracted from the bundle. Given that we discussed needing the `entry.search.mode` parameter, I think this should probably stay as a bundle of data for each page so that tabulate can access the search parameter and continue processing everything as a bundle.

2022-10-28 16:06 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +) -> Tuple[List[dict], str]:
Good call! The common denominator returned by extract functions is `List[dict]`, and I updated the `extract_data_from_schema` to report the right return value. 

The incremental function also returns the `next`, and the "from schema" function indexes results by table name but in all cases the actual results are managed as a `List[dict]`. Does this make sense and look good to you?

2022-10-28 16:20 UTC, m-goggins approved these changes

2022-10-31 19:33 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +) -> Tuple[List[dict], str]:
I added a ticket to ensure extract and tabulate have a consistent format to pass data between them:
https://app.clickup.com/t/3rgp6w4

2022-10-31 20:17 UTC, bamader approved these changes
Looks great, and very clear ticket and AC for instructions on reconciling the two formats moving forward!

2022-10-31 20:36 UTC, merged