about the encounter
CDCgov/phdi pull request #1005
Opened 2023-12-26 15:39 UTC by JNygaard-Skylight

# PULL REQUEST

## Summary
What changes are being proposed?

## Related Issue
Fixes #932 

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2023-12-26 16:20 UTC, JNygaard-Skylight commented
<img width="1469" alt="image" src="https://github.com/CDCgov/phdi/assets/141273852/79883a4d-2bb2-4219-b97e-c84ce096e5e2">

2023-12-26 17:21 UTC, BobanL submitted a review, later dismissed
Code looks good to me!

2023-12-26 17:21 UTC, BobanL commented on containers/ecr-viewer/src/app/utils.tsx
> +        `${streetAddress.join("\n")}
thanks for moving this down here and making it more clear!

2023-12-28 18:11 UTC, BobanL submitted a review, later dismissed

2024-01-02 21:36 UTC, sarahtress commented
@JNygaard-Skylight formatting looks good here to me, but I just have some questions on the functionality/data:

- are we able to pull out the time of the encounter as well, or just the date? I'm not sure what data is available but it would be great to include time if it is possible
- do you know what we're using to source the facility name? as in, are we confident it's where the encounter happened and not just the sender of the eCR? let me know if that question doesn't make sense and I can try to clarify!

2024-01-03 16:22 UTC, JNygaard-Skylight commented
@sarahtress:
- Both the date and time are given for encounters, so we include both. Encounters also have a start and end date/time. I assume we are only interested in the start time?
- Within the FIHR bundle, encounters have a specific location, so this is indeed using the facility name of the location of the encounter.

2024-01-03 16:43 UTC, JNygaard-Skylight commented
@sarahtress: Updated screenshot with date and time for encounter date: 
<img width="1469" alt="Screenshot 2023-12-26 at 11 20 33" src="https://github.com/CDCgov/phdi/assets/141273852/4ddd741f-f5dd-4ba3-ab5e-f7aded1b2ed2">

2024-01-03 19:44 UTC, JNygaard-Skylight commented
@sarahtress: How does this look:
![image](https://github.com/CDCgov/phdi/assets/141273852/ed69666d-e366-4bc6-9476-32290d9f34ec)

2024-01-03 20:41 UTC, sarahtress commented
> @sarahtress: How does this look: ![image](https://private-user-images.githubusercontent.com/141273852/294012713-ed69666d-e366-4bc6-9476-32290d9f34ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTQ3NDcsIm5iZiI6MTcwNDMxNDQ0NywicGF0aCI6Ii8xNDEyNzM4NTIvMjk0MDEyNzEzLWVkNjk2NjZkLWUzNjYtNGJjNi05NDc2LTMyMjkwZDlmMzRlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QyMDQwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMWMyNGZjYzdiZTVmYzdmYzE3MGI3NGE3ZGE5M2QwOGRhYWJhMDYzNDZkZjNlZGUzN2MxMDFmNWZjMDkxNDc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7y2xrrTw3WHSSybogZYC1TvgagPnGBOSp-tm82EaWMc)

@JNygaard-Skylight looks great thank you!

2024-01-03 20:45 UTC, nickbristow commented on containers/ecr-viewer/src/app/utils.tsx
should this just be a .ts file? I don't see any jsx

2024-01-03 20:47 UTC, nickbristow approved these changes

2024-01-03 21:01 UTC, JNygaard-Skylight commented on containers/ecr-viewer/src/app/utils.tsx
Wish I could tell you why, but everything breaks if you rename it to a `.ts` file.

2024-01-03 21:38 UTC, JNygaard-Skylight commented
@BobanL, can you have a particularly good look at my branch? Git went wild with merge conflicts so can you double check I didn't bungle something while resolving conflicts?

2024-01-03 23:45 UTC, emmastephenson requested changes
This looks great Josh, thank you! I think there may just be some issues with the diff to `main` - maybe try merging it again?

2024-01-03 23:45 UTC, emmastephenson commented on containers/ecr-viewer/src/app/view-data/components/EcrSummary.tsx
> +                            <h4>Lab results relevant to reportable condition</h4>
Is this section ("lab results relevant to reportable condition") supposed to be here? It looks like it's hardcoded to the design, rather than pulling out whatever the correct fields are from the eCR. (Which is a big can of worms, so probably shouldn't be tackled in this PR)

2024-01-03 23:45 UTC, emmastephenson commented on containers/orchestration/app/DAL/DataMapper.py
> +from typing import Any
These changes look like they're from Boban's PR #1007 - could you merge with `main` again to get rid of the diff? (I think you should just be able to merge, not rebase)

2024-01-03 23:45 UTC, emmastephenson commented on containers/standardization/tests/assets/censusResponse.json
> +{
Same here,  I think these changes came from Robert's geocoding work (#1003)

2024-01-04 00:21 UTC, BobanL commented
@emmastephenson @JNygaard-Skylight It seems like those conflicts that were already in main were an issue with [github](https://stackoverflow.com/a/46782679). I set the base to to another branch and then back to main and it looks like all those conflicts went away. There are only 9 changed files 😅!

2024-01-04 00:22 UTC, BobanL commented on containers/ecr-viewer/src/app/view-data/components/EcrSummary.tsx
> +                            <h4>Lab results relevant to reportable condition</h4>
This change actually came form my PR that was merged in recently. I accidentally did the work to format the data, but didn't really want it to go to waste so I just hardcoded it. I can comment it out if you'd prefer!

2024-01-04 01:37 UTC, BobanL commented on containers/ecr-viewer/src/app/utils.tsx
This change doesn't need to be handled in this PR, but what issues are seeing with that change? When I make that change everything looks fine (tests pass and visually looks ok)

2024-01-04 16:56 UTC, emmastephenson commented on containers/ecr-viewer/src/app/view-data/components/EcrSummary.tsx
> +                            <h4>Lab results relevant to reportable condition</h4>
Ahh gotcha - it's probably fine to leave in for now then! Thanks for clarifying.

2024-01-04 16:58 UTC, emmastephenson approved these changes
LGTM, thanks Josh!

2024-01-09 22:25 UTC, BobanL approved these changes

2024-01-09 22:28 UTC, KennethSkylight approved these changes
lgtm

2024-01-09 22:29 UTC, merged