add preliminary db connection to orchestration
CDCgov/phdi pull request #1007
Opened 2023-12-28 17:17 UTC by BobanL

# PULL REQUEST

## Summary
- Create a DB model of the data
- Create a repository for db connection

## Related Issue
Fixes #977 

## Additional Information
- This is just part one of the process to begin saving to the db

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-01-02 18:16 UTC, emmastephenson requested changes
Looks great, thanks Boban! Just some minor changes to request.

2024-01-02 18:16 UTC, emmastephenson commented on containers/orchestration/app/DAL/FhirDataModel.py
> +class FhirDataModel(Base):
Could you rename this to something more specific to Postgres? It's pretty likely that during the pilot we'll use another data source (like cloud blob storage) and we'll probably need another DataModel class for that.

2024-01-02 18:16 UTC, emmastephenson commented on containers/orchestration/app/DAL/SqlFhirRepository.py
> +        self.session = session
Do we need to close the session at the end of use, or does SQL Alchemy do that automatically?

2024-01-02 19:31 UTC, BobanL commented on containers/orchestration/app/DAL/SqlFhirRepository.py
> +        self.session = session
So the session will usually be closed just at the end of where this is be instantiated. If you look at the [test](https://github.com/CDCgov/phdi/pull/1007/files#diff-71057b7766e450052c4b98c2bfe715a4b2a8f4963ba35a6ff737d2f3a15622d5R16-R21):
```py
    with Session(engine) as session:
        repo = SqlAlchemyFhirRepository(session)
        repo.persist(expected)
        actual = session.query(FhirDataModel).get(str(ecr_id))
        assert expected.ecr_id == actual.ecr_id
        assert expected.data == actual.data
```
The session will just [closes at the end of the `with Session(engine) as session:` block.](https://docs.sqlalchemy.org/en/20/orm/session_basics.html#basics-of-using-a-session:~:text=Above%2C%20the%20Session%20is%20instantiated%20with%20an%20Engine%20associated%20with%20a%20particular%20database%20URL.%20It%20is%20then%20used%20in%20a%20Python%20context%20manager%20(i.e.%20with%3A%20statement)%20so%20that%20it%20is%20automatically%20closed%20at%20the%20end%20of%20the%20block%3B%20this%20is%20equivalent%20to%20calling%20the%20Session.close()%20method.)

2024-01-02 20:20 UTC, emmastephenson commented on containers/orchestration/app/DAL/SqlFhirRepository.py
> +        self.session = session
Ahh got it, thank you!

2024-01-02 20:22 UTC, emmastephenson commented on containers/orchestration/app/DAL/SqlFhirRepository.py
> +        self.session.flush()
I think we may need to use [`commit` instead of `flush`](https://stackoverflow.com/a/4202016) here. Otherwise the DB changes won't be permanently peristed. (I think the reason this is currently working in the integration test is that the assertions are all happening inside the `with Session` block)

2024-01-03 18:04 UTC, emmastephenson approved these changes
LGTM!

2024-01-03 20:07 UTC, nickbristow approved these changes

2024-01-03 20:21 UTC, merged