Add config and steps to save to DB in orchestration
CDCgov/phdi pull request #1017
Opened 2024-01-05 01:21 UTC by nickbristow

# PULL REQUEST

## Summary
In the orchestration, save to DB as a step.
## Related Issue
Fixes #978

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-01-18 19:11 UTC, BobanL reviewed
Looks good to me, but as one of my first time looking at python I don't feel comfortable approving it!

2024-01-18 22:05 UTC, emmastephenson reviewed
Mostly looking great! My feedback is more about expected behavior than implementation. Thank you both for tackling this! 🙏

2024-01-18 22:05 UTC, emmastephenson commented on containers/orchestration/app/default_configs/sample-orchestration-config.json
>        "service": "message_parser",
We can make this a follow-up PR, but since we're saving the FHIR bundles to the DB, message parsing shouldn't be a step in the default (eCR processing) config anymore.

2024-01-18 22:05 UTC, emmastephenson commented on containers/orchestration/app/services.py
> +        ecr_id = uuid.uuid4()
I'd actually argue there should be different behavior here - if the eicr ID can't be found, I think the service should throw an exception rather than generate a random UUID.

The product thinking here is that we'll only be able to find the eCRs users are looking at in NBS through the original eICR ID - they won't know what the generated ID is.

2024-01-18 22:05 UTC, emmastephenson commented on containers/orchestration/local-dev.sh
> +cd ../ecr-viewer
nit: Is it possible to check if a database is already running? In the same way we check for other Docker containers before trying to start them up.

2024-01-18 22:06 UTC, emmastephenson requested changes
Meant to request changes, not comment 🤦

2024-01-19 19:09 UTC, gordonfarrell commented on containers/orchestration/local-dev.sh
> +cd ../ecr-viewer
Gooood ideeaaaoooood

2024-01-19 19:33 UTC, gordonfarrell commented on containers/orchestration/app/services.py
> +        ecr_id = uuid.uuid4()
Good idea, added an exception here and a test for it

2024-01-19 19:37 UTC, gordonfarrell commented on containers/orchestration/app/default_configs/sample-orchestration-config.json
>        "service": "message_parser",
Cool we'll leave it out of this one and then take a look

2024-01-19 20:40 UTC, emmastephenson approved these changes
Looks great! Thank you for making those changes!

2024-01-19 21:00 UTC, merged