Fixing demographics
CDCgov/phdi pull request #1027
Opened 2024-01-08 16:40 UTC by KennethSkylight

# PULL REQUEST

## Summary
The Demographics data ordering was out of place and is missing some fields. The PR fixes these issues. **Please ignore the blank fields. They will be replaced with "N/A" in another PR**

## Related Issue
Fixes #1016

Screenshots:

![image](https://github.com/CDCgov/phdi/assets/107214304/c72cde49-bfc1-49e9-b5ba-465f95a7919c)

2024-01-09 18:23 UTC, BobanL submitted a review, later dismissed
looks good!

2024-01-09 22:22 UTC, sarahtress commented
@KennethSkylight it looks gtm except for 2 things:

- should be "Patient IDs" not "Patient ID"
- is County a field that's available to show? I thought it was, but can remove from the design if it's not

2024-01-10 15:55 UTC, KennethSkylight commented
@sarahtress I don't see county in any of our test data

Here's the updated screenshot
<img width="810" alt="image" src="https://github.com/CDCgov/phdi/assets/107214304/0b5c2a79-6ccd-44e2-81e8-fafcd69f0c74">

2024-01-10 15:58 UTC, sarahtress commented
> @sarahtress I don't see county in any of our test data
> 
> Here's the updated screenshot <img alt="image" width="810" src="https://private-user-images.githubusercontent.com/107214304/295625743-0b5c2a79-6ccd-44e2-81e8-fafcd69f0c74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MDI1MTIsIm5iZiI6MTcwNDkwMjIxMiwicGF0aCI6Ii8xMDcyMTQzMDQvMjk1NjI1NzQzLTBiNWMyYTc5LTZjY2QtNDRlMi04MWU4LWZhZmNkNjlmMGM3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQxNTU2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2M4NTEyYjE4OWIyMjhmNjEzYWI1ZWY2MjQ1ZmE4NzQ4MjllYmI5NTIxZDE3ZGFhNmQ4YWIzMWVlYjE2M2U2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gBz0n-dBzTZRpDcgRZqPj_cdQ4qjJ0WCB19YFFvpsrU">

hmm interesting, I'm seeing county right at the top of this RR. is that an anomaly for this one example or are you able to see that in the other RR samples?
<img width="994" alt="Screenshot 2024-01-10 at 10 56 44 AM" src="https://github.com/CDCgov/phdi/assets/126291169/f1833400-e1f3-4a4f-a935-4c50fed7cd3a">

everything else looks good though!

2024-01-10 16:11 UTC, KennethSkylight commented
@sarahtress I see. I think it might be getting lost in the fhir converter? I'll add the field and we'll have to find that missing field later.

<img width="843" alt="image" src="https://github.com/CDCgov/phdi/assets/107214304/391d9ef9-2863-4c93-be41-03f43efbd326">

2024-01-10 16:12 UTC, sarahtress commented
> @sarahtress I see. I think it might be getting lost in the fhir converter? I'll add the field and we'll have to find that missing field later.
> 
> <img alt="image" width="843" src="https://private-user-images.githubusercontent.com/107214304/295630278-391d9ef9-2863-4c93-be41-03f43efbd326.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MDMzNjMsIm5iZiI6MTcwNDkwMzA2MywicGF0aCI6Ii8xMDcyMTQzMDQvMjk1NjMwMjc4LTM5MWQ5ZWY5LTI4NjMtNGM5My1iZTQxLTAzZjQzZWZiZDMyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQxNjExMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGRiZTY5MzQ3YzYwOTNkYjRiZDBkMTAyZTk4YmM3NWRkOWI1YWM4ZTAyZDE2YjYyNDgyNWJkZjQ0YTliZDU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f4bEj95BXgtjkoWN81B4xqNZfUj7wwY12_CgG442vr8">

okay! sounds good to me, thanks!

2024-01-10 20:44 UTC, JNygaard-Skylight requested changes
LGTM, just need to remove a stray `console.log`

2024-01-10 20:44 UTC, JNygaard-Skylight commented on containers/ecr-viewer/src/app/view-data/components/Demographics.tsx
> +  console.log(evaluate(fhirBundle, fhirPathMappings.patientTribalAffiliation));
Remove console log.

2024-01-10 21:56 UTC, KennethSkylight commented on containers/ecr-viewer/src/app/view-data/components/Demographics.tsx
> +  console.log(evaluate(fhirBundle, fhirPathMappings.patientTribalAffiliation));
Done

2024-01-10 22:18 UTC, JNygaard-Skylight approved these changes

2024-01-11 15:20 UTC, merged