Side Nav
CDCgov/phdi pull request #1043
Opened 2024-01-10 00:33 UTC by JNygaard-Skylight

# PULL REQUEST

## Summary
What changes are being proposed?

## Related Issue
Fixes #994 

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-01-10 20:39 UTC, JNygaard-Skylight commented
@sarahtress, I still have some behind-the-scenes work to do for this ticket, but could you take a look at what I currently have?
![image](https://github.com/CDCgov/phdi/assets/141273852/abbc3c1f-d55a-40b2-ab64-e44a265cdcf2)

2024-01-10 22:55 UTC, sarahtress commented
> @sarahtress, I still have some behind-the-scenes work to do for this ticket, but could you take a look at what I currently have? ![image](https://private-user-images.githubusercontent.com/141273852/295705427-abbc3c1f-d55a-40b2-ab64-e44a265cdcf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MjQzODcsIm5iZiI6MTcwNDkyNDA4NywicGF0aCI6Ii8xNDEyNzM4NTIvMjk1NzA1NDI3LWFiYmMzYzFmLWQ1NWEtNDBiMi1hYjY0LWU0NGEyNjVjZGNmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQyMjAxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjVmMDIzNDRjYzM0NDcwMzg4ODZhMmZlMzJkNTYzYTQ3YzgwNjYzZTU5Njc4Yjg0ZTUzODU2OWE3NWI4MGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RzDYkaqoA14-Xiyw9_jNWs2NjVcoAkYv8VpZZxlFRxI)

thanks for sending @JNygaard-Skylight few things to match the designs:
- the width of the navigation menu should be 170 px, looks wider than that here
- I just realized that the styling of my navigation in the designs doesn't match the USWDS default, so I'll work on changing that in the designs!
- is it possible to make the main section headings (Patient Info, Encounter Info, Clinical Info, Lab Info, eCR Metadata, Unavailable Info) bolded in the side navigation?
- the design also has eCR Summary and eCR Document as items in the side navigation, could those be added? they should be in black text, rather than gray
- right now everything is left justified, but the side navigation and the eCR data should be centered on the page
- also, does the side navigation stay in place when you scroll? (as in, you should always be able to see the side navigation, it shouldn't disappear as you scroll)

let me know if you have any questions!

2024-01-29 16:30 UTC, JNygaard-Skylight commented
![image](https://github.com/CDCgov/phdi/assets/141273852/219a41cb-43fa-4fe0-9bb5-56a8521be5d2)
![image](https://github.com/CDCgov/phdi/assets/141273852/baecfa34-532d-4d4d-934b-bd48881ad604)
@sarahtress, some new screenshots, how do things look now?

2024-01-29 17:33 UTC, nickbristow approved these changes

2024-01-29 20:00 UTC, sarahtress commented
> ![image](https://private-user-images.githubusercontent.com/141273852/300532650-219a41cb-43fa-4fe0-9bb5-56a8521be5d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NTgwNTQsIm5iZiI6MTcwNjU1Nzc1NCwicGF0aCI6Ii8xNDEyNzM4NTIvMzAwNTMyNjUwLTIxOWE0MWNiLTQzZmEtNGZlMC05YmI1LTU2YTg1MjFiZTVkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxOTQ5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTJkMDJmNzgzZTQzNTMxN2ZiZjQwNzI5OTdlZTJjNmQ1MTNjZjZkNzAxZTEzNGUyMTU2N2I0NDlkMjI1YzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oXAkqirY5uAIqb13AwCUYhsNxXYgS7kWOMlnG2zLXHw) ![image](https://private-user-images.githubusercontent.com/141273852/300532871-baecfa34-532d-4d4d-934b-bd48881ad604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NTgwNTQsIm5iZiI6MTcwNjU1Nzc1NCwicGF0aCI6Ii8xNDEyNzM4NTIvMzAwNTMyODcxLWJhZWNmYTM0LTUzMmQtNGQ0ZC05MzRiLWJkNDg4ODFhZDYwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxOTQ5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzk1ZDQ4ZDExNmQ3ZGJmZGQwZTkxZWJjN2E1MmEyYmViMGMyZTNmY2Q4YzczYjk0YzA1NzMwY2YzYzRmOGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bl0IFMPmrHzhsdO2qGGro614jandjfEH9hExQ51GSlQ) @sarahtress, some new screenshots, how do things look now?

thanks for the new screenshots @JNygaard-Skylight. it's looking closer, but still some things to be adjusted. you may also need to send a video for this one bc it's interaction heavy and I can't totally tell what's going on as you scroll

- there should be three levels of hierarchy in the navigation, so only eCR Summary and eCR Document should be fully left justified. I attached a screenshot which labels the 3 levels within the navigation in the design, but let me know if you have more questions
- the side navigation shouldn't go above the content on the right. when at the top of the page, the top of the side navigation and the top of the "eCR Summary" text should be at the same height. I also attached a screenshot to show this alignment
- in the screenshots you sent, I'm not seeing any active sections on the side navigation. as you scroll the page, it should be responsive to show where you are on a page with bolded blue text. good example is on this page for the component, the right side navigation is responsive as you scroll the page (... I see the styling of that component is different though and matches my original styling... perhaps there is a different component with this functionality built in??)


<img width="238" alt="Screenshot 2024-01-29 at 2 52 00 PM" src="https://github.com/CDCgov/phdi/assets/126291169/32a0d2fa-bc83-4d5b-9066-638dd60d61f8">

<img width="1176" alt="Screenshot 2024-01-29 at 2 59 20 PM" src="https://github.com/CDCgov/phdi/assets/126291169/3f3fe92a-f038-41c3-a353-7849c2a20db9">

2024-01-29 23:56 UTC, emmastephenson requested changes
Thanks Josh! Some comments, happy to chat through offline if that's best.

2024-01-29 23:56 UTC, emmastephenson commented on containers/ecr-viewer/src/app/view-data/page.tsx
> +          items={[<a href="#demographics">Demographics</a>]}
I think there should also be a "Social History" sub-section here

2024-01-29 23:56 UTC, emmastephenson commented on containers/ecr-viewer/src/app/view-data/page.tsx
> +  const accordionItems: any[] = [
I'm wondering if there's a way to do this more dynamically...because as-is, I think we'll need to manually update the side nav with every new section that's added, and I can see that getting hard to maintain somewhat quickly. 

My idea would be to generate the side nav based on the `h2` or `h3` elements within the accordion. Anything on the page with h2 or h3 tags is auto-included in the side nav, and any heading levels below that are ignored. 

I'm not sure if this would be practical with the `Accordion` components that were recently added, though - happy to chat more offline.

2024-01-29 23:56 UTC, emmastephenson commented on containers/ecr-viewer/src/app/view-data/page.tsx
> +        <div className="main-container">
We have snapshot tests for specific sections/components, but I don't think we have any test coverage for the side nav itself at the moment - could you add one? Either a snapshot test of the entire page or unit tests for the side nav specifically would work.

2024-01-31 19:28 UTC, JNygaard-Skylight commented on containers/ecr-viewer/src/app/view-data/page.tsx
> +        <div className="main-container">
I moved the side nav code to its own file and added unit tests.

2024-01-31 19:28 UTC, JNygaard-Skylight commented on containers/ecr-viewer/src/app/view-data/page.tsx
> +          items={[<a href="#demographics">Demographics</a>]}
Added.

2024-01-31 19:31 UTC, JNygaard-Skylight commented on containers/ecr-viewer/src/app/view-data/page.tsx
> +  const accordionItems: any[] = [
I created a `SectionConfig` class that I think should reduce the technical load for adding a new section.

2024-01-31 23:08 UTC, emmastephenson requested changes
This looks great Josh, thanks for making those changes! Just one other small request for changes.

2024-01-31 23:08 UTC, emmastephenson commented on containers/ecr-viewer/src/app/view-data/components/EcrSummary.tsx
> +            About the Patient
Would it be possible to reference the title as defined in the `eCRSummaryConfig` above? You might need to tweak the `SectionConfig` class definition, but I think then you could do something like

```html
<h3 className="summary-box-key-information" id={eCRSummaryConfig.subNav[1].id}>
            {eCRSummaryConfig.subNav[1].title}
</h3>
```

The reason I suggest it is that right now it'd be easy to only update the title in one place and have the side nav mismatch the actual content. I think this also applies to the `EcrMetadata` file, but `Demographics` and `SocialHistory` look good already :)

2024-02-01 16:52 UTC, JNygaard-Skylight commented on containers/ecr-viewer/src/app/view-data/components/tests/SideNav.test.tsx
> +    // @ts-ignore
It was concerned that `subNavItems` could be null, but it should never be null, and if it is, we want the test to fail anyway. Just rewrote it to get rid of the TS ignores.

2024-02-02 22:57 UTC, emmastephenson approved these changes
Looks good to me, thank you Josh! 🙌 This will be great to have on the viewer.

The failing `build-containers` job should resolve itself if you merge with `main`, btw - that issue was from a bad PR I put out earlier this week, but it's resolved now.

2024-02-05 15:07 UTC, merged