Draft dump
CDCgov/phdi pull request #107
Opened 2022-11-02 14:54 UTC by bamader

2022-11-02 20:28 UTC, m-goggins requested changes
Looking pretty good to me. I made a few minor suggestions and commented on several things that are likely outside the scope of this PR but I wanted to get your thinking on them as well.

2022-11-02 20:28 UTC, m-goggins commented on phdi/tabulation/tables.py
> +        tuple_data = [tuple([str(x) for x in row]) for row in tabulated_data[1:]]
Why are we converting to string? Would we not want to preserve the original data types before inserting into a table? 

I imagine this could also trigger an error if the table has been defined prior to using the tabulation BB and the datatypes are not strings.

2022-11-02 20:28 UTC, m-goggins commented on phdi/tabulation/tables.py
> +        with open(location + filename, "a", newline="") as fp:
This is likely outside the scope of this ticket (and possibly the BB), but I'm wondering if you think users would only want to append _new_ data to an existing file. I'm not sure if there's a use case but maybe something like maintaining a list of patients who have gotten their flu shots over time. You wouldn't want to re-add data that's already in the existing file. Maybe this is a question for research but curious to know what you think as well.

2022-11-02 20:28 UTC, m-goggins commented on tests/tabulation/test_tables.py
> +        reader = csv.reader(csv_file, dialect="excel")
Do we need `dialect-"excel"`?

2022-11-02 20:28 UTC, m-goggins commented on tests/tabulation/test_tables.py
> +        reader = csv.reader(csv_file, dialect="excel")
ditto

2022-11-02 20:28 UTC, m-goggins commented on tests/tabulation/test_tables.py
> +            print(row)
Remove print statement unless necessary

2022-11-02 20:28 UTC, m-goggins commented on tests/tabulation/test_tables.py
> +        ("Shepard", "Zakera Ward", "None", "no-srsly-i-am-hoomun"),
lol

2022-11-02 20:28 UTC, m-goggins commented on tests/tabulation/test_tables.py
> +# @TODO: REMOVE THIS FUNCTION ALONG WITH THE OLD GENERATE ALL TABLES CODE
Good call on marking these as needing to be deleted.

2022-11-03 14:18 UTC, bamader commented on phdi/tabulation/tables.py
> +        cursor = conn.cursor()
We probably should, yeah. This is a good idea to support in the future, but since that relates more to a SQL feature than an intrinsic part of the writing functionality, I'm going to say that's out of scope for the current PR. I'll write a ticket for it as part of closing this PR.

2022-11-03 14:22 UTC, bamader commented on phdi/tabulation/tables.py
> +        tuple_data = [tuple([str(x) for x in row]) for row in tabulated_data[1:]]
Yeah, I hear you. Initially the conversion wasn't in this PR at all, and we just wrote the raw data into the table. But then when we merged in tabulation and had values start coming back as lists (i.e. lists of reverse pointers to a an anchor resource), everything broke. This is one of the only things I have to complain about SQL and sqlite3--we can't insert Python lists into tables as objects. We have to instead serialize them in some way, our options of which are stringifying (done here), json.dumps (seemed weird because we're not maintaining a dictionary), or converting to binary (the worst out of the three lol). I _think_ there are ways we can register decorators or automatic converters to serialize for us when writing, but it did seem to be a bit more complex and could involve some architecture conversations around how we want to handle this (so I'll ping @bryan-skylight for his thoughts on serializing). 

My instinct for right now is to leave this as a string (because it works and unblocks the write features), and then open a separate ticket for work around proper serializing/de-serializing data as its being written and read from the database file (because I think it'll involve some research and extra complexity).

2022-11-03 14:26 UTC, bamader commented on phdi/tabulation/tables.py
> +        with open(location + filename, "a", newline="") as fp:
I think your mind is in the right place with a pretty clear use case our end users might have, but my current understanding is that that falls outside the scope of the building blocks (or rather, the BB as write presently). Data maintenance and updating existing records are more akin to a style of database management we don't currently support; so, using the example you provided, I would expect a user's workflow to be something like: use BB to write and append incoming data to a record of all patients, write separate program or function to work through this file of existing records and add info where relevant in a new column. If we tried to use the BB (that we have currently) to do this, I think we'd end up backed into doing something really clunky, gross, and inefficient versus just asking the user to write such a function themselves. @bryan-skylight Any more thoughts on whether this is something we should support in the future? It's definitely not in scope for this PR, but it is a good question that we might want to tackle at some point.

2022-11-03 14:30 UTC, bamader commented on tests/tabulation/test_tables.py
> +        reader = csv.reader(csv_file, dialect="excel")
I think we do need this, yeah. A `csv.reader.Dialect` is the object that holds rules for interpreting quotes, double quotes, end of lines, and escape characters, so having this ensures that the results of the tests are consistent across operating systems that generate the test CSV (there are dialect objects for both Windows systems via `excel` and unix systems via, well, `unix`).

2022-11-03 14:30 UTC, bamader commented on tests/tabulation/test_tables.py
> +        reader = csv.reader(csv_file, dialect="excel")
lol likewise ditto

2022-11-03 14:31 UTC, bamader commented on tests/tabulation/test_tables.py
> +        ("Shepard", "Zakera Ward", "None", "no-srsly-i-am-hoomun"),
For my own curiosity, which part of this 100% legitimate test data point earned the lol?

2022-11-03 14:34 UTC, bamader commented on phdi/tabulation/tables.py
> +        with open(location + filename, "a", newline="") as fp:
Love this. Great call 😎

2022-11-03 15:25 UTC, m-goggins commented on tests/tabulation/test_tables.py
> +        ("Shepard", "Zakera Ward", "None", "no-srsly-i-am-hoomun"),
"no-srsly-i-am-hoomun"

2022-11-03 15:34 UTC, m-goggins commented on phdi/tabulation/tables.py
> +        tuple_data = [tuple([str(x) for x in row]) for row in tabulated_data[1:]]
Yeah, that makes sense to me for now. Maybe add a TODO item here to remind us to come back to this.

2022-11-03 16:16 UTC, bamader commented on tests/tabulation/test_tables.py
> +        ("Shepard", "Zakera Ward", "None", "no-srsly-i-am-hoomun"),
Ah shoot I was hoping you might've recognized the game reference lol

2022-11-03 16:17 UTC, bamader commented on tests/tabulation/test_tables.py
> +        reader = csv.reader(csv_file, dialect="excel")
Actually yeah we probably should. We expect our users to be operating on government Windows machines, but that extra safety layer is smart.

2022-11-03 17:29 UTC, m-goggins approved these changes
Approve knowing that we have future word related to this function

2022-11-07 17:10 UTC, merged