Commenting guidelines
CDCgov/phdi pull request #11
Opened 2022-08-10 17:51 UTC by spencer-skylight

Add commenting guidelines to CONTRIBUTING.md.

2022-08-18 18:09 UTC, bamader requested changes
Just a couple minor suggestions

2022-08-18 18:09 UTC, bamader commented on CONTRIBUTING.md
> +:return: A description of the return value (where applicable).
Do we want to include the `:return:` here, since we're taking it out of the standard docstring signature?

2022-08-18 18:09 UTC, bamader commented on CONTRIBUTING.md
> +* *Self-documenting code is best*: Choose good module and function names, and write code that speaks for itself.
I would change this to "... Use clear, descriptive, and precise names for modules, variables, and functions; write code that speaks for itself." The change here is to elaborate on what "good" means and to add "variables" as members in naming conventions, so I had to change the structure of the sentence to avoid too many run-on commas.

2022-08-18 18:09 UTC, bamader commented on CONTRIBUTING.md
> +* *Comments should add clarity*: Good comments can add information that cannot be just as easily read or inferred, summarize functionality provided by a block of code, or add context to explain non-i
I would delete the "just as" in the first sentence. i.e. "Good comments can add information that cannot be easily read or inferred, summarize ..."

2022-08-18 22:05 UTC, spencer-skylight commented on CONTRIBUTING.md
> +:return: A description of the return value (where applicable).
Yes, you're right, updated!

2022-08-18 22:06 UTC, spencer-skylight commented on CONTRIBUTING.md
> +* *Self-documenting code is best*: Choose good module and function names, and write code that speaks for itself.
Replaced with your suggested text.

2022-08-18 22:06 UTC, spencer-skylight commented on CONTRIBUTING.md
> +* *Comments should add clarity*: Good comments can add information that cannot be just as easily read or inferred, summarize functionality provided by a block of code, or add context to explain non-i
Updated as suggested.

2022-08-19 12:35 UTC, bamader approved these changes
LGTM! Let's show this to Bryan and land this bad dog.

2022-08-19 15:20 UTC, KennethSkylight approved these changes
lgtm

2022-08-19 15:45 UTC, spencer-skylight commented on CONTRIBUTING.md
> +The [VS Code Extensions](#extensions) section below outlines how the autoDocstring extension can be used to streamline docstring creation in the VS Code IDE.
Good catch.  Updated.

2022-08-19 15:46 UTC, merged