Adding observation to clinical info
CDCgov/phdi pull request #1184
Opened 2024-01-29 21:04 UTC by robertandremitchell

# PULL REQUEST

## Summary
Adds the previously created Observation data to Clinical Information.

## Related Issue
Fixes #1166

2024-01-30 18:32 UTC, robertandremitchell commented
I'm still puzzling through the tests, but the tests worked locally.

2024-01-30 20:23 UTC, robertandremitchell commented
@zdeveloper and @robertmitchellv , do you have any recommendations for how I might be able to resolve this last check? I'm pretty stumped, but I recall you both running into this on another PR where the unittests worked locally but not on Git.

2024-01-30 20:36 UTC, robertandremitchell commented
never mind, my eyesight is not helping matters. actual issue is with the fhir unittest.

2024-01-31 15:06 UTC, DanPaseltiner requested changes
Thanks for putting this together. Really awesome to start seeing the "meat" of a PHDC. I think there are few places (see comments below) that we can tighten things up a bit.

2024-01-31 15:06 UTC, DanPaseltiner commented on containers/message-parser/app/phdc/builder.py
> +            observation_data.append(value_element_xml)
I might be missing something here, but since there is a 1:1 correspondence between codes and value couldn't we do all of this inside a single loop? To my it looks like we are iterating through something twice when we could just iterate through once.

2024-01-31 15:32 UTC, robertandremitchell commented on containers/message-parser/app/phdc/builder.py
> +        ET.register_namespace("xsi", "http://www.w3.org/2001/XMLSchema-instance")
all thanks to @robertmitchellv (I shamelessly stole from your PR)

2024-01-31 16:05 UTC, robertandremitchell commented on containers/message-parser/app/phdc/builder.py
> +            observation_data.append(value_element_xml)
This was definitely more densely written than it needed to be. I've taken a stab at simplifying the CodedElement logic.

2024-01-31 16:06 UTC, robertandremitchell commented on containers/message-parser/app/phdc/models.py
> +        return attributes
agreed. The pop logic didn't quite work, but a dictionary comprehension did the trick!

2024-01-31 16:06 UTC, robertandremitchell commented on containers/message-parser/app/phdc/models.py
>          # Create a dictionary with XML attribute names
added!

2024-01-31 16:06 UTC, robertandremitchell commented on containers/message-parser/app/phdc/builder.py
> +                section.append(observation_element)
updated!

2024-01-31 16:06 UTC, robertandremitchell commented on containers/message-parser/app/phdc/builder.py
> +    def _build_case_report(
updated!

2024-01-31 16:06 UTC, robertandremitchell commented on containers/message-parser/app/phdc/builder.py
>      def _build_observation_method(self, observation: Observation) -> ET.Element:
updated!

2024-01-31 17:28 UTC, DanPaseltiner commented on containers/message-parser/app/phdc/builder.py
> +            value_element_xml.append(translation_element_xml)
This is much flatter. Nice refactor.

2024-01-31 17:28 UTC, DanPaseltiner commented on containers/message-parser/app/phdc/builder.py
> +    def _build_clinical_info(
Looks like we are missing a doc string here.

2024-01-31 17:28 UTC, DanPaseltiner commented on containers/message-parser/app/phdc/models.py
> +        return {k: v for k, v in attributes.items() if v is not None}
So while this is simpler in that it is all one line it still has the problem of creating any object in memory to store duplicate data. Let me see if I can code up an example.

2024-01-31 17:47 UTC, DanPaseltiner commented on containers/message-parser/app/phdc/models.py
> +        return {k: v for k, v in attributes.items() if v is not None}
Ahh right, the piece I was missing is that the dict changes size during iteration.

2024-01-31 17:55 UTC, DanPaseltiner commented on containers/message-parser/app/phdc/builder.py
> +    def _build_clinical_info(
I realize this isn't a fault with this PR, but could we add one please?

2024-01-31 19:53 UTC, robertmitchellv commented on containers/message-parser/app/phdc/builder.py
> +        ET.register_namespace("xsi", "http://www.w3.org/2001/XMLSchema-instance")
glad that it helped!

2024-01-31 20:54 UTC, robertandremitchell commented on containers/message-parser/app/phdc/builder.py
> +    def _build_clinical_info(
added!

2024-01-31 21:40 UTC, DanPaseltiner approved these changes
LGTM. Thanks for you work on this and going back and forth with me a bit.

2024-01-31 21:54 UTC, merged