Add reason for visit, clinical data section, custom liquid filters
CDCgov/phdi pull request #1239
Opened 2024-02-02 16:04 UTC by nickbristow

# PULL REQUEST

## Summary
The main focus of this PR is to add reason for visit to the ecr visit. 

Also adds custom liquid filters and some refactors

<img width="775" alt="Next_js" src="https://github.com/CDCgov/phdi/assets/5296248/64955ce2-aa09-4605-982c-9f20e945a7c1">

## Related Issue
Fixes #1077 

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-02-06 18:57 UTC, emmastephenson reviewed
Looking great! Just a few small comments. Thanks for all your work on this!!

2024-02-06 18:57 UTC, emmastephenson commented on containers/ecr-viewer/docker-compose-local-dev.yml
> +version: "3.8"
@robertandremitchell is doing similar work for the orchestration service, btw - see #1241. (Specifically [this comment](https://github.com/CDCgov/phdi/pull/1241#discussion_r1479018865))

Up to y'all how we deconflict/merge this - but Nick, maybe you can just rename this to `database-local-compose` or similar?

2024-02-06 18:57 UTC, emmastephenson commented on containers/ecr-viewer/src/app/utils.tsx
> +// export const evaluateClinicalData = (
Can this commented section be removed?

2024-02-06 18:57 UTC, emmastephenson commented on containers/ecr-viewer/src/app/view-data/components/AccordionContainer.tsx
> +      title: "eCR Metadata",
While you're doing this, can you move eCR Metadata to the bottom section? That'll knock out #1121 too.

2024-02-06 18:57 UTC, emmastephenson commented on containers/fhir-converter/CustomFilters/CustomFilters.cs
> +      list.Remove(firstElement);
Is there a `list.pop` or `list.removeFirst()` you could use here instead? Retrieve then remove seems a little inefficient.

2024-02-06 18:57 UTC, emmastephenson commented on containers/fhir-converter/CustomFilters/CustomFilters.cs
> +    public static string FooBar(string data)
I think this FooBar method can probably be removed, no?

2024-02-06 18:57 UTC, emmastephenson commented on containers/fhir-converter/Dockerfile
> +# RUN pwd && ls -la
Can you remove the comments here? Unless we need them

2024-02-06 19:19 UTC, nickbristow commented on containers/ecr-viewer/docker-compose-local-dev.yml
> +version: "3.8"
I think they are similar. This is a special docker compose for use when you want to not start the ecr-viewer service in docker compose, so that you can hot reload it. I've renamed it

2024-02-06 19:20 UTC, nickbristow commented on containers/ecr-viewer/src/app/utils.tsx
> +// export const evaluateClinicalData = (
i like it

2024-02-06 19:22 UTC, nickbristow commented on containers/ecr-viewer/src/app/view-data/components/AccordionContainer.tsx
> +      title: "eCR Metadata",
resolved

2024-02-06 19:24 UTC, nickbristow commented on containers/fhir-converter/CustomFilters/CustomFilters.cs
> +    public static string FooBar(string data)
I'll miss it

2024-02-06 19:26 UTC, nickbristow commented on containers/fhir-converter/Dockerfile
> +# RUN pwd && ls -la
yes

2024-02-06 19:31 UTC, nickbristow commented on containers/fhir-converter/CustomFilters/CustomFilters.cs
> +      list.Remove(firstElement);
Doesn't seem like it, there is a `RemoveAt` function? Which just removes at the index

```
string firstElement = list.First(); // Retrieve the first element
list.RemoveAt(0);
```

2024-02-06 20:12 UTC, BobanL requested changes
I think this breaks the sidenav with some of the refactor of accordion and removal of ids.

2024-02-06 20:12 UTC, BobanL commented on containers/ecr-viewer/src/app/view-data/components/AccordionContainer.tsx
> +  });
Could we just set id in each object to be more specific rather than just an number. Since you got rid of the span in the title the side nav breaks. 

so like for the eCR Metadata section the id would be `ecr-metadata`

https://github.com/CDCgov/phdi/assets/10108172/59a6c8f0-c3f0-4086-856a-efdec48e2ac1

2024-02-06 20:12 UTC, BobanL commented on containers/ecr-viewer/src/app/view-data/page.tsx
> -                <h2 className="margin-bottom-3" id="ecr-summary">
ID is needed for side nav

2024-02-06 20:12 UTC, BobanL commented on containers/ecr-viewer/src/app/view-data/page.tsx
> -                  <h2 className="margin-bottom-3" id="ecr-document">
same as above, ID is needed for side nav

2024-02-06 22:00 UTC, nickbristow commented on containers/ecr-viewer/src/app/view-data/page.tsx
> -                  <h2 className="margin-bottom-3" id="ecr-document">
woops, added back in

2024-02-06 22:01 UTC, nickbristow commented on containers/ecr-viewer/src/app/view-data/page.tsx
> -                <h2 className="margin-bottom-3" id="ecr-summary">
fixed

2024-02-06 22:01 UTC, nickbristow commented on containers/ecr-viewer/src/app/view-data/components/AccordionContainer.tsx
> +  });
fixed

2024-02-06 22:01 UTC, nickbristow commented on containers/fhir-converter/Dockerfile
> +RUN echo 'hello'
fixed

2024-02-06 22:01 UTC, nickbristow commented on containers/ecr-viewer/src/app/utils.tsx
> +  let headers: any[] = [];
yes, that makes more sense

2024-02-06 22:02 UTC, nickbristow commented on containers/ecr-viewer/package.json
> +    "local-dev": "docker-compose -f database-local-compose.yml up -d && docker-compose logs && export DATABASE_URL=postgres://postgres:pw@localhost:5432/ecr_viewer_db && next dev",
Fixed

2024-02-06 22:02 UTC, nickbristow commented on containers/ecr-viewer/docker-compose-local-dev.yml
> +version: "3.8"
Based on @BobanL's comments, i've removed this file and modified my start up script

2024-02-06 23:09 UTC, emmastephenson approved these changes
LGTM to me from the dev side! But @sarahtress will also need to do a design review - can you add screenshots for her to review?

2024-02-06 23:09 UTC, emmastephenson commented on containers/fhir-converter/CustomFilters/CustomFilters.cs
> +      list.Remove(firstElement);
Too bad, either the `remove` or `removeAt` seems fine then!

2024-02-07 13:50 UTC, BobanL approved these changes
Thanks for those changes! All looks good to me now!

2024-02-07 15:31 UTC, nickbristow commented
<img width="1162" alt="Next_js" src="https://github.com/CDCgov/phdi/assets/5296248/860432ab-7e82-4a62-9b77-b544796dacbf">
@sarahtress for design review

2024-02-07 16:53 UTC, sarahtress commented
@nickbristow just one tiny change, should be "Reason for Visit" (capital V), not "Reason for visit"

2024-02-07 17:08 UTC, nickbristow commented
Fixed @sarahtress 
<img width="1017" alt="Next_js" src="https://github.com/CDCgov/phdi/assets/5296248/2dd2cef8-ac14-4b41-8809-941486dd9e47">

2024-02-07 17:24 UTC, merged

2024-02-07 18:36 UTC, angelathe commented on containers/ecr-viewer/src/app/view-data/components/UnavailableInfo.tsx
>          renderSection("Symptoms and Problems", activeProblemsUnavailableData)}
@nickbristow So sorry this is late!! Think we're missing the Reason for Visit in the Unavailable Data section (should be rendered under the Symptoms and Problems sub-section). Can you confirm? Happy to make this small fix in my ticket if so.

<img width="382" alt="Screenshot 2024-02-07 at 10 35 25" src="https://github.com/CDCgov/phdi/assets/40042932/f9a6947d-c69a-45cd-87c1-ffed7e833dd3">

2024-02-07 18:42 UTC, nickbristow commented on containers/ecr-viewer/src/app/view-data/components/UnavailableInfo.tsx
>          renderSection("Symptoms and Problems", activeProblemsUnavailableData)}
Its there, its...just confusing now. Because of the naming convention