Rob/1196 write a docker compose file for the orchestration service
CDCgov/phdi pull request #1241
Opened 2024-02-02 21:27 UTC by robertandremitchell

# PULL REQUEST

## Summary
What changes are being proposed?

## Related Issue
Fixes #1196 

## Additional Information
Still puzzling through ecr-viewer; we might be able to postpone work on this aspect in the short run.

Also, the tests already use docker? https://github.com/CDCgov/phdi/blob/main/containers/orchestration/tests/integration/docker-compose.yaml
I need to figure out still what mods might be needed for the integration testing, what cleanup is needed here...

Also, I still need 

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-02-05 21:25 UTC, robertandremitchell commented
weirdly, the integration tests seem to be passing on git, but aren't for me locally... @bamader or @DanielPaseltiner , I'm curious if you have any trouble running either test, locally. In particular, because it deals with DB things, I'm wondering if it's because I'm lacking any particular local set up?

cc @gordonfarrell @emmastephenson

2024-02-05 21:26 UTC, robertandremitchell commented
If the tests work for others, before merging, I will remove `test.env` and the `tests/integration/docker-compose.yaml`. I've preserved them for now for ease of comparison, review.

2024-02-05 22:49 UTC, emmastephenson requested changes
I have a suggestion to tweak the database setup a bit, happy to chat more offline if you'd like!

2024-02-05 22:49 UTC, emmastephenson commented on containers/orchestration/docker-compose.yml
> +  ecr-viewer-db:
I think there's an opportunity to DRY this up with the ecr-viewer's docker-compose file. What if instead of copying the job, we created a separate docker-compose just for the database? It would include both the database setup (this job) as well as the seed-db job currently included in the viewer. Then this file and the ecr-viewer compose could both reference the database-setup compose.

2024-02-05 22:49 UTC, emmastephenson commented on containers/orchestration/docker-compose.yml
> +    depends_on:
If we do go the route of having a separate database-setup docker compose, we should make the database setup jobs another dependency here - I think you can [reference those jobs directly](https://docs.docker.com/compose/multiple-compose-files/include/#example).

2024-02-05 22:49 UTC, emmastephenson commented on containers/orchestration/tests/integration/conftest.py
> +    dotenv_path = Path(__file__).resolve().parent.parent.parent / ".env"
Probably would be best to delete the existing `docker-compose` file in the `test` folder as well - no need to have it around as dead code!

2024-02-06 15:18 UTC, DanPaseltiner reviewed
Looking really good. Thank @robertandremitchell. I think @emmastephenson sounds like the right approach here -- not that what you did was wrong.

2024-02-06 16:32 UTC, robertandremitchell commented on containers/orchestration/docker-compose.yml
> +    depends_on:
nice! yeah, I was struggling to get the logic for stringing together docker-composes, thank you for this resource. I agree that separating out the database work and seed-db work would work better separately. I will work to implement.

2024-02-07 15:11 UTC, robertandremitchell commented
@bamader , I know you've puzzled through these integration tests recently. I have 3 failing for what I suspect is the same reason. I can get `http://localhost:8080/process-message` to run after running `docker compose up` locally. however, I've been stuck on this assertionerror problem since yesterday afternoon.

As far as I can tell, the payload for the three tests failing should be up to date. Any clues why it might not be working?

cc @DanPaseltiner

2024-02-08 19:21 UTC, robertandremitchell commented
New docker-compose seems to be working. I am not entirely sure why the `include` logic does not seem to work on GitHub actions but does locally? https://docs.docker.com/compose/compose-file/14-include/

Curious if we want to try to get it to work or just delete `docker-compose-ecr-viewer.yml` for now in favor of the super-file? I can do some additional digging to see if there's any reason include would not work.

2024-02-08 21:45 UTC, DanPaseltiner commented
> New docker-compose seems to be working. I am not entirely sure why the `include` logic does not seem to work on GitHub actions but does locally? https://docs.docker.com/compose/compose-file/14-include/
> 
> Curious if we want to try to get it to work or just delete `docker-compose-ecr-viewer.yml` for now in favor of the super-file? I can do some additional digging to see if there's any reason include would not work.

@robertandremitchell I think we want `extends` instead of `include`, [these docs](https://docs.docker.com/compose/multiple-compose-files/extends/) might be helpful. Could you attempt to get this working? LMK if you'd like to pair.

2024-02-12 15:06 UTC, robertandremitchell commented
Argh! Still not working, but a promising clue, this time around:
```
Cannot extend service 'seed-db' in /home/runner/work/phdi/phdi/containers/orchestration/docker-compose-ecr-viewer.yml: services with 'depends_on' cannot be extended
```

2024-02-12 17:03 UTC, robertandremitchell commented
@DanPaseltiner  and @emmastephenson I got the `extend` logic to work!

LMK if this looks good. 🤞🏽

2024-02-12 20:08 UTC, DanPaseltiner approved these changes
LGTM. Is the intention here that we would eventually point this to a different docker compose file for the DB so we can eliminate `docker-compose-ecr-viewer.yml`?

Nice work here. I know this was a real slog with a lot of hair pulling. Thanks for sticking with it!

2024-02-12 20:34 UTC, robertandremitchell commented
> LGTM. Is the intention here that we would eventually point this to a different docker compose file for the DB so we can eliminate `docker-compose-ecr-viewer.yml`?
> 
> Nice work here. I know this was a real slog with a lot of hair pulling. Thanks for sticking with it!

Yeah. I don't think we can point to the `ecr-viewer` docker-compose.yml, at least in its current form, because you can't have an `extend` that also has a `depends_on`, which that file currently does.

2024-02-12 20:35 UTC, robertandremitchell commented on containers/orchestration/docker-compose.yml
> +    depends_on:
@emmastephenson , curious your thoughts on the current state with `extends`. As noted during our pairing, unfortunately at least at the moment, `includes` doesn't seem to play nicely with GitHub Actions.

2024-02-12 23:01 UTC, emmastephenson commented on containers/orchestration/docker-compose.yml
> +    depends_on:
Interesting! I think this will definitely work for now, and it's easy enough to follow, so 👍 from me on the PR overall.

I do wonder if @rin-skylight has run into this `includes` issue with GH actions before?

2024-02-13 14:42 UTC, merged