Add data-types to validation schema
CDCgov/phdi pull request #127
Opened 2022-11-17 19:52 UTC by nickbristow

Support data types in validation schema. 

Limits the supported data types to `bool`, `float`, and `string`

2022-11-21 16:33 UTC, m-goggins requested changes
Looks pretty good to me! I just requested a few changes (to ensure that the `valid_schema.json` and `valid_schema.yaml` files are consistent and had a question about how `data_type` will be implemented.

2022-11-21 16:33 UTC, m-goggins commented on tests/assets/valid_schema.yaml
> +        data_type: string
Make sure to add these to the `valid_schema.json` file as well...and the `tabulation_schema.yaml` file. We have too many test files but just want to keep them consistent for now before paring down.

2022-11-21 16:33 UTC, m-goggins commented on tests/assets/valid_schema.yaml
>    table 2A:
If `data_type` is required (from comment above), we should add data types for this table as well.

2022-11-21 20:34 UTC, bamader requested changes

2022-11-21 20:34 UTC, bamader commented on phdi/tabulation/validation_schema.json
> +                "data_type": {
I think the goal here is to make it not required, and to assume the data should just be treated as a string if no data is specified. At least, that's the assumption I'd make for the `write_data` component of this (which this PR isn't supporting quite yet). Interested in thoughts on that though!

2022-11-21 20:34 UTC, bamader commented on tests/assets/valid_schema.yaml
> +        data_type: string
_biiiiiiig_ ➕  here for this

2022-11-21 20:34 UTC, bamader commented on tests/assets/valid_schema.yaml
>    table 2A:
Also, regardless of if it's required or not, we should add some test cases to show what happens for fields that _don't_ specify a data_type. If it's not required, there should be no change or impact to the functionality, but if it is required, we want to see that throw the appropriate error.

2022-11-21 20:49 UTC, m-goggins commented on phdi/tabulation/validation_schema.json
> +                "data_type": {
I think optional makes sense; just need to add the appropriate error for when a user does not specify the data type and is writing to an already-created SQL table that has other data types so that they know where to add data types to the schema.

2022-11-22 18:27 UTC, BradySkylight commented on tests/assets/valid_schema.yaml
>    table 2A:
++

2022-11-25 20:42 UTC, nickbristow commented
@bamader @m-goggins i think this is good to go now. I changed some of the tests and updated them. I also updated the click up to note the need on the other ticket for additional tests.

2022-11-28 19:13 UTC, m-goggins commented on tests/fhir/tabulation/test_fhir_tabulation.py
> +        {"some-uuid", "John ", None, "123-456-7890", "123"},
Double checking that this is supposed to be a string and not a number as specified in the schema.

2022-11-28 19:14 UTC, m-goggins commented on tests/fhir/tabulation/test_fhir_tabulation.py
> +        {"some-uuid", "John ", None, "123-456-7890", "123"},
Just for my own clarification...when we update the functions (and not just the schema), these BuildingNumbers will be number type, right?

2022-11-28 19:51 UTC, bamader approved these changes
LGTM!

2022-11-28 20:10 UTC, merged