Updated doc strings to be uniform in the description of schema
CDCgov/phdi pull request #128
Opened 2022-11-17 20:55 UTC by BradySkylight

This PR covers this ticket and is meant to standardize the use and definition of schema within the Tabulation code.  It also updateds other areas of the doc string documentation where the params/return values, as well as general descriptions, were sometimes using 'dict' and other times 'dictionary'.  Params and return values should be 'dict' and in general descriptions 'dictionary'.

There were a few other areas where I made other slight changes to ensure the FHIR information was readable and understandable.  If there are areas that were missed please comment.

2022-11-17 23:01 UTC, m-goggins requested changes
Whew, lots of changes making the text better. I had mostly nit picky suggestions but looks good overall.

2022-11-17 23:01 UTC, m-goggins commented on phdi/tabulation/tables.py
> +    Given the path to a local YAML file containing a schema,
Given the path to a local YAML or JSON file containing a schema,

We added JSON capabilities after this was written.

2022-11-18 16:30 UTC, BradySkylight commented on phdi/fhir/tabulation/tables.py
> +    :return: A dict containing the mapping of a table and it's columns, grouped by
SMH...can't believe I didn't catch that.  Thank you!  LOL

2022-11-18 16:40 UTC, BradySkylight commented on phdi/tabulation/tables.py
> +    Given the path to a local YAML file containing a schema,
Nice catch!

2022-11-18 16:42 UTC, BradySkylight commented
> Whew, lots of changes making the text better. I had mostly nit picky suggestions but looks good overall.

Yes and I know it was a LOT to review and read through and I very much appreciate your feedback which was all great.  I've implemented the changes you requested.

2022-11-21 20:56 UTC, bamader requested changes
Solid stuff, just the one change in schema

2022-11-21 20:56 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +        invalid criteria for filtering.
I hate to come in at the end with changes, but I think this does miss some potentially salient parts of the schema around metadata and table properties. I like the syntax structure, but I think we could condense the language present while also mentioning some other things the schema defines about each table: `A declarative, user-defined specification, for one or more tables, that defines the metadata, properties, and columns of those tables as they relate to FHIR resources.` My worry is that as written now, the explanation is too focused on the fields that define the column properties, rather than the fields that define the table as a whole. But we're getting a bit into semantics so I'm okay if you'd rather push back on this suggestion.

2022-11-21 20:56 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +    :param return: A list of lists, without rows of data from the FHIR resources and
I would just add `derived` into this sentence between `data` and `from` (as written, there's no consequential relationship between data and why we're throwing any of it out)

2022-11-21 20:56 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +        that maps a FHIR resource and element to a specified column in a table.
Copy paste here

2022-11-21 20:56 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +        maps a FHIR resource and element to a specified column in a table.
Copy paste here

2022-11-21 20:56 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +        maps a FHIR resource and element to a specified column in a table.
Copy paste here

2022-11-22 18:22 UTC, m-goggins approved these changes
Looks good to me; just missed one schema def update in `load_schema`. Update that, and I think it should be good to go.

2022-11-22 18:22 UTC, m-goggins commented on phdi/tabulation/tables.py
> +    a FHIR resource and element to a specified column in a table.
I think you might have missed updating this schema definition.

2022-11-22 18:26 UTC, BradySkylight commented on phdi/tabulation/tables.py
> +    a FHIR resource and element to a specified column in a table.
Good catch!  Updated!

2022-11-23 16:50 UTC, bamader approved these changes
LGTM!

2022-11-23 17:33 UTC, merged