Adding pypi fields to pyproject toml. Also fixing the version for fhirpathpy
CDCgov/phdi pull request #13
Opened 2022-08-11 15:47 UTC by KennethSkylight

To upload our package to pypi, we want to include the readme and relevant links for users to see when they arrive on our pypi page

2022-08-11 16:29 UTC, spencer-skylight requested changes
Looks good - just a question about version I think we need to figure out.

2022-08-11 16:29 UTC, spencer-skylight commented on pyproject.toml
> +authors = [Kenneth Chow <kenneth@skylight.digital>, Brandon Mader <brandon@skylight.digital>, Spencer Kathol <spencer@skylight.digital>]
I think you need to wrap the list elements in double-quotes.

2022-08-11 16:29 UTC, spencer-skylight commented on pyproject.toml
> +version = "0.1.1"
Is it possible to keep the version at 0.1.0 (and does it permit the -dev prefix?) in this initial time before the pypi registration is actually complete? It currently disagrees with the documentation location.

I will also look in to how the version string and related tracking is normally managed, in an attempt to automate as much as possible.

2022-08-12 16:08 UTC, KennethSkylight commented on pyproject.toml
> +version = "0.1.1"
Looks like I can do 0.1.dev1

According to this: https://peps.python.org/pep-0440/#examples-of-compliant-version-schemes

Would that work?

2022-08-17 12:26 UTC, bamader reviewed
Agree with Spencer -- this looks good aside from the version change I'd like to see implemented, if that's possible.

2022-08-17 15:12 UTC, KennethSkylight commented on pyproject.toml
> +version = "0.1.1"
Ok changed

2022-08-17 16:02 UTC, spencer-skylight approved these changes
LGTM!

2022-08-17 16:11 UTC, bamader approved these changes

2022-08-17 19:58 UTC, merged