Refactor generate_tables for incremental approach
CDCgov/phdi pull request #130
Opened 2022-11-21 22:28 UTC by m-goggins

This PR refactors the `generate_tables` function to work incrementally, as outlined in the general approach of this [ticket](https://app.clickup.com/t/3pc6e55). Instead of extracting, tabulating, and writing each table into memory, we are extracting, tabualting, and writing each _incremental_ piece of each table so that we do not overwhelm memory in the case of a large table.

2022-11-22 18:43 UTC, bamader requested changes
Great work, there's just a couple places we could condense code and be a bit more efficient.

2022-11-22 18:43 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +    new_field_location = str()
I would just say `new_field_location = ""`

2022-11-22 18:43 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +
We shouldn't modify an iterator in place. We could instead just append directly to `new_field_location`, e.g.

```
if letter.isupper():
    new_field_location += "-"
new_field_location += letter.lower()
```

This won't do anything to letters that are already lowercase but will successfully prepend hypens without risking an iterator issue.

2022-11-22 18:43 UTC, bamader commented on phdi/fhir/tabulation/tables.py
Since we do multiple splits on `field_location` later, let's just get the constituent parts here:

```
direction, field_location = reference_location.split(":", 1)
resource, element_path = field_location.split(":", 1)
```

Then below, we just make the for loop over the letters in `element_path`, and then recombine `field_location` as `field_location = resource + ":" + new_field_location`

2022-11-22 18:43 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +            search_string += f"?{urlencode(query_params,True)}"
God this was so annoying to catch 😅

2022-11-22 18:43 UTC, bamader commented on phdi/fhir/tabulation/tables.py
>          )
We can actually condense this code to ditch the second set of repeated calls by preemptively setting next and kicking off the while loop:

```
for table_name, search_url in search_urls.items():
    next = search_url
    while next is not None:
        incremental_results, next = extract_data_from_fhir_search_incremental(
                search_url=urllib.parse.urljoin(fhir_url, next),
                cred_manager=cred_manager,
        )
        # Tabulate data for each set of incremental results
        [code just continues as normal]
```

2022-11-22 18:43 UTC, bamader commented on tests/assets/tabulation_schema.yaml
> +  results_per_page: 1000
One of these days we'll condense our asset files and actually standardize everything 👀

2022-11-22 18:55 UTC, BradySkylight commented on phdi/fhir/tabulation/tables.py
I like this.

2022-11-22 18:57 UTC, BradySkylight commented on tests/assets/valid_schema.yaml
> +      category: laboratory
Do we know why Spencer was using the full URL value for this here?

2022-11-22 19:12 UTC, bamader commented on tests/assets/valid_schema.yaml
> +      category: laboratory
Marcelle and I discussed this yesterday and we came to the conclusion that it was a page that enumerated the possible allowed values for an observation's category element. We then tested it with an actual FHIR server and the full URL didn't resolve to a successful query but truncating it to just `laboratory` did.

2022-11-22 19:16 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
> +
Yeah, good call.

2022-11-22 19:19 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
>          )
Ha of course! My brain did not compute this but it is definitely better.

2022-11-22 19:26 UTC, m-goggins commented on tests/assets/valid_schema.yaml
> +      category: laboratory
Yeah, I'm thinking that he would have changed it if it had been tested using the FHIR server and not mocked responses. As far as I can tell from the [documentation](https://build.fhir.org/searchparameter-registry.html), category should be a token type.

2022-11-22 19:50 UTC, BradySkylight commented on phdi/fhir/tabulation/tables.py
> +            search_string += f"?{urlencode(query_params,True)}"
Was this the solution to the issue where the url was not formatted correctly with a [''] scenario?

2022-11-22 20:24 UTC, BradySkylight commented on tests/assets/valid_schema.yaml
> +      category: laboratory
Makes sense.

2022-11-22 21:02 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
> +            search_string += f"?{urlencode(query_params,True)}"
Yes haha

2022-11-22 22:01 UTC, BradySkylight approved these changes
With the additional changes, this looks good.  Nice work!

2022-11-23 14:13 UTC, bamader approved these changes
Thanks for making those changes, looks good!

2022-11-23 16:39 UTC, merged