Update the Census Geocode tests to use a mocked census api call
CDCgov/phdi pull request #131
Opened 2022-11-29 23:02 UTC by BradySkylight

The intent of this PR is to ensure that we aren't relying on third-party applications to be available for our testing as well as speed up the testing process.  The mocked API call achieves the purpose of the test but doesn't make an actual call to the Census Geocode API.

2022-11-30 18:23 UTC, bamader approved these changes
LGTM, good catch!

2022-11-30 22:40 UTC, m-goggins requested changes
I think this PR looks pretty good! I made some suggestions to more closely align the Census tests with the mocking strategy for Smarty. I think it would be easier to debug Census and Smarty at the same time if their tests look alike.

2022-11-30 22:40 UTC, m-goggins commented on tests/geospatial/test_census_geocode_client.py
> +    patched_api_call.return_value = censusResponseFullAddress
Ditto here

2022-11-30 22:40 UTC, m-goggins commented on tests/geospatial/test_census_geocode_client.py
> +    patched_api_call.return_value = ambiguous_address_dict
And here

2022-11-30 22:40 UTC, m-goggins commented on tests/geospatial/test_census_geocode_client.py
> +def test_geocode_from_str(patched_api_call):
I don't think this is a dealbreaker but it is how we've implemented the Smarty tests so it might be nice to keep them consistent.

2022-11-30 23:19 UTC, BradySkylight commented on tests/geospatial/test_census_geocode_client.py
> +def test_geocode_from_str(patched_api_call):
I'll give it a go and ensure the tests all still work.  That seems like a good reason to make the change!  Thanks for the feedback!

2022-12-01 16:06 UTC, m-goggins approved these changes
Looks good to me!

2022-12-01 16:27 UTC, merged