Rob/1291 write request and response handling functions for message parser payloads
CDCgov/phdi pull request #1324
Opened 2024-02-14 18:59 UTC by robertandremitchell

# PULL REQUEST

## Summary
This adds the handler functions for message_parser.

## Related Issue
Fixes #1291

2024-02-15 15:12 UTC, DanPaseltiner requested changes
Thanks for getting this started and uncovering the messiness associated with handling requests and responses from `/parse_message` and `fhir_to_phdc` in the same functions. I think we should break this out into two functions for each endpoint (see comments below). Let me know if you'd like to discuss further.

2024-02-15 15:12 UTC, DanPaseltiner commented on containers/orchestration/app/handlers.py
> +def build_message_parser_request(
I think what we should do here is have a separate functions for the two endpoints on the message parser. We could have a `build_message_parse_message_request` and a `build_convert_fhir_to_phdc_request`. In `call_apis` based on the name of the step we'll be able to chose the correct handler functions.

2024-02-15 15:12 UTC, DanPaseltiner commented on containers/orchestration/app/handlers.py
> +        return {"phdc_report_type": "case_report"}
We need to include the actual data that will be parsed or converted to PHDC in these requests. [For both endpoints](https://cdcgov.github.io/phdi/latest/containers/message-parser.html#operation/fhir_to_phdc_endpoint_fhir_to_phdc_post) this is done by including a `message` key in the dict.

2024-02-15 15:12 UTC, DanPaseltiner commented on containers/orchestration/app/handlers.py
> +def build_message_parser_request(
Additionally, every one of the request builder functions need to have the same signature. They should be of the form `(
    input_msg: str, orchestration_request: OrchestrationRequest
) -> dict`. This will let us set `message` to `input_msg`.

2024-02-15 15:12 UTC, DanPaseltiner commented on containers/orchestration/app/handlers.py
> +def unpack_message_parser_response(response: Response) -> Tuple[int, str | dict]:
By having dedicated unpacking functions for each of the two relevant parse message endpoints we should be able to simplify this quite a bit.

2024-02-15 22:22 UTC, bamader requested changes
Looking good so far, let's just move that params signature into the handlers rather than the model input, and then double check the "response" accessors once we invoke `.json()` on the response

2024-02-15 22:22 UTC, bamader commented on containers/orchestration/app/handlers.py
> +) -> dict:
I think the idea is to put the params for the workflow directly into the function signature. The orchestration service doesn't have an overarching params list it maintains for each service, but with our new workflow files, we do pair those with each step of the workflow, so I think we should just assume the `call_apis` function will hand off the appropriate dict to the function. Here's how I structured mine:

```
def build_valiation_request(
    input_msg: str,
    orchestration_request: OrchestrationRequest,
    workflow_params: dict | None = None,
) -> dict:
```

2024-02-15 22:22 UTC, bamader commented on containers/orchestration/app/handlers.py
> +) -> dict:
This prevents us from having to alter the Orchestration Service's base model before we're ready to commit those changes (we really don't want to add or take away any params from it until we can do so all at once, so we don't disrupt the streamline team)

2024-02-15 22:22 UTC, bamader commented on containers/orchestration/app/handlers.py
> +    report_type = orchestration_request.get("params").get("phdc_report_type")
With the params moved into the signature, we can delete the comment here and just directly look up phdc report type.

2024-02-15 22:22 UTC, bamader commented on containers/orchestration/app/handlers.py
> +        converter_response = response.json().get("response")
The reason we need a `.get("response")` accessor in the fhir converter handlers is because of the converter itself. If you look at line 138 of fhir-converter/app/service.py, you'll see the result object is actually encapsulated in another dictionary. None of our other services do this (it's because of the way the command line tool returns 🙄 ), so we don't need the extra `.get("response")` here. Just calling `response.json()` is sufficient.

2024-02-15 22:22 UTC, bamader commented on containers/orchestration/app/handlers.py
> +            error_message = converter_response.get("text", "Unknown error")
I think the text of the message will be in the body of the response object proper, rather than the JSON serialization of it, so this should be `error_message = response.text` (which python's `Requests` module assures us will always exist so no need to use get)

2024-02-15 22:22 UTC, bamader commented on containers/orchestration/app/handlers.py
> +            parsed_message = converter_response.get("FhirResource")
Does the message parser output actually have a FhirResource key?

2024-02-15 22:22 UTC, bamader commented on containers/orchestration/app/handlers.py
> +                )
Same caveats as above, I don't think we need the extra `.get("response")` because of the object structure, and `.text` will be directly on the response object

2024-02-15 22:22 UTC, bamader commented on containers/orchestration/app/models.py
> +    )
We want this to be in the function signature rather than the request, since the params will change with each step of the workflow

2024-02-16 14:33 UTC, robertandremitchell commented on containers/orchestration/app/handlers.py
> +        converter_response = response.json().get("response")
I'm not sure I follow. without the `.get("response")` I get this:
```json
{
  "response": {
    "status_code": 200,
    "FhirResource": {
      "resourceType": "Bundle",
      "identifier": {
        "value": "a very contrived FHIR bundle"
      },
      "entry": [
        {
          "resource": {
            "resourceType": "Organization",
            "id": "some-org-we-dont-care-about"
          }
        },
        {
          "resource": {
            "resourceType": "Patient",
            "id": "some-uuid",
            "identifier": [
              {
                "value": "123456",
                "type": {
                  "coding": [
                    {
                      "code": "MR",
                      "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                      "display": "Medical record number"
                    }
                  ]
                },
                "system": "urn...no idea"
              }
            ],
            "name": [
              {
                "family": "doe",
                "given": [
                  "John ",
                  " Danger "
                ],
                "use": "official"
              }
            ],
            "birthDate": "1983-02-01",
            "gender": "female",
            "address": [
              {
                "line": [
                  "123 Fake St",
                  "Unit #F"
                ],
                "BuildingNumber": "123",
                "city": "Faketon",
                "state": "NY",
                "postalCode": "10001-0001",
                "country": "USA",
                "use": "home"
              }
            ],
            "telecom": [
              {
                "use": "home",
                "system": "phone",
                "value": "123-456-7890"
              },
              {
                "value": "johndanger@doe.net",
                "system": "email"
              }
            ]
          },
          "request": {
            "method": "GET",
            "url": "testing for entry with no resource"
          }
        }
      ]
    }
  }
}
```

so we would still need to access "response", unless I'm thinking of it wrongly.

2024-02-16 14:38 UTC, robertandremitchell commented on containers/orchestration/app/handlers.py
> +            parsed_message = converter_response.get("FhirResource")
erg, no. I got mixed up here that we need to be looking at a sample message_parser (which has "message" and "parsed_values" as keys. Will update this test.

2024-02-16 14:45 UTC, robertandremitchell commented on containers/orchestration/app/handlers.py
> +        converter_response = response.json().get("response")
nvm, I see what you're saying. I've gotten the FHIR and message parser mixed up 🤦🏽

2024-02-16 14:45 UTC, robertandremitchell commented on containers/orchestration/app/handlers.py
> +        converter_response = response.json().get("response")
updating!

2024-02-16 15:27 UTC, robertandremitchell commented on containers/orchestration/app/handlers.py
> +) -> dict:
moved

2024-02-16 15:27 UTC, robertandremitchell commented on containers/orchestration/app/handlers.py
> +    report_type = orchestration_request.get("params").get("phdc_report_type")
done

2024-02-16 15:28 UTC, robertandremitchell commented on containers/orchestration/app/handlers.py
> +        converter_response = response.json().get("response")
updated

2024-02-16 15:28 UTC, robertandremitchell commented on containers/orchestration/app/handlers.py
> +            error_message = converter_response.get("text", "Unknown error")
updated

2024-02-16 15:28 UTC, robertandremitchell commented on containers/orchestration/app/handlers.py
> +                )
fixed

2024-02-16 15:28 UTC, robertandremitchell commented on containers/orchestration/app/models.py
> +    )
removed

2024-02-16 16:49 UTC, robertandremitchell commented
updated error handling for unpacking after consulting with @DanPaseltiner , for context, @bamader. Curious your thoughts on re-review.

2024-02-16 18:03 UTC, bamader approved these changes
LGTM! Thanks for getting all those fixes in! I think the error logic being moved outside of the handler functions is part of the pattern we want. We want call_apis to be responsible for handling those as much as possible, as part of our strategy of percolating the error as high up the call chain as it'll go.

2024-02-16 18:07 UTC, DanPaseltiner approved these changes
🚀

2024-02-16 18:19 UTC, merged