Support list data type in data tabulation
CDCgov/phdi pull request #134
Opened 2022-12-02 22:45 UTC by nickbristow

Supports list types in data tabulation

2022-12-07 22:42 UTC, bryan-skylight requested changes
The code itself looks good, but the codecov bot is not pleased. Can you please update the tests to ensure we have proper coverage?

2022-12-07 22:42 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
> +            val[i] = _convert_list_to_string(v)
This bring up an edge case that I hadn't considered before regarding nested arrays. Because this function unnests the lists, do we risk losing context around certain data elements that have been previously "grouped" together? This isn't a blocking question, but we should make sure to ask Brady once he's back online.

2022-12-07 22:43 UTC, bryan-skylight commented
> The code itself looks good, but the codecov bot is not pleased. Can you please update the tests to ensure we have proper coverage?

If you look [here](https://app.codecov.io/gh/CDCgov/phdi/pull/134) you'll see the three lines of code where we don't currently have coverage.

2022-12-08 16:53 UTC, nickbristow commented on phdi/fhir/tabulation/tables.py
> +            val[i] = _convert_list_to_string(v)
Yeah, i wanted to check with @bamader but he's been busy

2022-12-08 16:53 UTC, nickbristow commented
> > The code itself looks good, but the codecov bot is not pleased. Can you please update the tests to ensure we have proper coverage?
> 
> If you look [here](https://app.codecov.io/gh/CDCgov/phdi/pull/134) you'll see the three lines of code where we don't currently have coverage.

I've added additional tests to get this to pass

2022-12-08 17:22 UTC, bamader requested changes
No need to repeat myself, my big concern is in the longer comment about what level we convert to string at

2022-12-08 17:22 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +                values = _convert_list_to_string(values)
I have a pretty strong preference to not do string conversion during the value extraction part of tabulation and instead keep type conversion strictly to writing. Bryan asked in a different comment whether we'll lose any blocking/contextual information by un-nesting part of the data, and I believe the answer to this is yes. More generally, from a pedagogical perspective, we made the conscious choice some time ago that we wanted to keep each phase of tabulation as "pure" as possible from the perspective of modifying data. I.e. we don't want to unnecessarily convert data into a different type early in the process, because a) that step doesn't _need_ the conversion, and b) users already deal with problems about upstream modifications to their data so we don't want to impose more of that. Third and finally, making this change to convert data at the tabulation level breaks workflows that don't terminate in a write. If a user were working in an interactive session, for example (using the BB in a notebook), then they're no longer able to do analysis on a tabulated result involving lists because they're now strings. I think we should _only_ be changing this type in the write function.

2022-12-08 17:22 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +            return _convert_dict_to_string(value)
I don't actually know if we can encounter any dictionaries at the point of value extraction? Lists, yes, because reverse pointers can accumulate multiple references per anchor, but I don't actually know under what conditions you'd get a list post-value extraction. Did you find any cases?

2022-12-08 17:22 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +            val[i] = _convert_list_to_string(v)
Yeah I think this is a dangerous approach, see my longer comment above about moving conversion to write instead of tabulate

2022-12-09 23:24 UTC, nickbristow commented
@bamader changes have been made

2022-12-12 22:28 UTC, bamader requested changes
Code logic looks good. Just some changes needed now to bring it into a pythonic style and in line with our repo guidelines.

2022-12-12 22:28 UTC, bamader commented on phdi/tabulation/tables.py
> +        tableList = tabulated_data[i]
You're gonna hate this lol but in python we avoid camel case variables like the plague. This needs to become `table_list`.

2022-12-12 22:28 UTC, bamader commented on phdi/tabulation/tables.py
> +        for n, v in enumerate(tableList):
Let's be more descriptive with the `v` in the enumeration (and I'd prefer the `n` as well). Since this is an iteration over a table row, I'd go with something like `for row, elt in enumerate(table_row)`.

2022-12-12 22:28 UTC, bamader commented on phdi/tabulation/tables.py
> +                tabulated_data[i][n] = _convert_dict_to_string(v)
It looks like the `_convert_dict_to_string()` function is just a one line cast to `str()`. If that's the case, let's delete the helper function and just call `str()` here.

2022-12-12 22:28 UTC, bamader commented on phdi/tabulation/tables.py
> +    to break down to the values to join into a string with a `,`.
We've got some rigid guidelines around docstring formatting and structure, so let's change this to the following: `Serializes a given list into a string, separating values with commas." (Rationale/explanation: We don't need tend to mention technical details in docstrings unless they're particularly relevant, so we can ditch the recursion point; there's no value checking on the input because we just assume that the input `val` is actually a list; small typos).

2022-12-12 22:28 UTC, bamader commented on phdi/tabulation/tables.py
> +    for use in CSV, SQL, etc
We can just say "a list," no need to mention it's an object. Also, all parameter and return docstring lines after the first should be prefaced with two spaces to simulate a half indent.

2022-12-12 22:28 UTC, bamader commented on phdi/tabulation/tables.py
> +            if isinstance(v, list):
Can you add a comment before this line that "some elements may themselves contain lists, if selection_criteria = all is used"? This way it's clear in the code we're not just directly calling the join here.

2022-12-13 14:41 UTC, nickbristow commented on phdi/tabulation/tables.py
> +        tableList = tabulated_data[i]
i hate that

2022-12-13 15:34 UTC, nickbristow commented
@bamader changes made

2022-12-13 18:46 UTC, bamader commented on phdi/tabulation/tables.py
> +        tableList = tabulated_data[i]
It is the python (and superior 😉 ) way

2022-12-13 18:48 UTC, bamader approved these changes
Looks better to me. Assuming Bryan has no issues with the code or the styling this should be good.

2022-12-14 15:00 UTC, bryan-skylight approved these changes
LGTM!

I'd prefer that the "serialization" functionality be in its own function, but I don't think that's a hard requirement, and certainly not worth keeping this PR open for. We can revisit later as a refactor ticket if we so choose.

2022-12-14 15:45 UTC, nickbristow commented
Ok, closing!

2022-12-14 15:46 UTC, merged