1356 auth middleware
CDCgov/phdi pull request #1370
Opened 2024-02-23 16:28 UTC by nickbristow

# PULL REQUEST

## Summary
Adds middleware to ecr viewer that stops api's from loading in production

## Related Issue
Fixes #

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-02-23 16:55 UTC, BobanL commented on containers/ecr-viewer/src/middleware.ts
> +    !pathname.startsWith("/api/auth")
You can remove this line (11), since there is no path `/api/auth` anymore

2024-02-23 17:50 UTC, BobanL requested changes
Since #1366 takes care of setting the cookie, some of that code can be removed from this PR.

2024-02-23 17:50 UTC, BobanL commented on containers/ecr-viewer/src/middleware.ts
> +      return NextResponse.redirect(new URL("/404", request.url));
It would probably be better to just return a response than a redirect. This would be similar to line 19. 

https://nextjs.org/docs/app/building-your-application/routing/middleware#producing-a-response

2024-02-23 17:50 UTC, BobanL commented on containers/ecr-viewer/src/app/view-data/page.tsx
> +
You won't need this once #1366 is in

2024-02-23 17:50 UTC, BobanL commented on containers/ecr-viewer/src/middleware.ts
> +  "-----BEGIN PUBLIC KEY-----\n" + "PLACEHOLDER\n" + "-----END PUBLIC KEY-----";
Can you replace placeholder with a `process.env.NBS_PUB_KEY` or something like that?

2024-02-23 17:50 UTC, BobanL commented on containers/ecr-viewer/src/middleware.ts
> +export async function middleware(request: NextRequest) {
can you put an empty space between import and this function?

2024-02-23 17:50 UTC, BobanL commented on containers/ecr-viewer/src/app/api/auth/route.ts
This file isn't needed. It's part of #1366

2024-02-23 17:50 UTC, BobanL commented on containers/ecr-viewer/package.json
>      "local-dev": "docker compose up db seed-db -d && docker-compose logs && export DATABASE_URL=postgres://postgres:pw@localhost:5432/ecr_viewer_db && next dev",
Will this also need `export NODE_ENV=development`?

2024-02-23 17:50 UTC, BobanL commented on containers/ecr-viewer/package.json
>      "local-dev": "docker compose up db seed-db -d && docker-compose logs && export DATABASE_URL=postgres://postgres:pw@localhost:5432/ecr_viewer_db && next dev",
Can you just replace `next dev` with `npm run dev`?

2024-02-23 17:50 UTC, BobanL commented on containers/ecr-viewer/src/middleware.ts
> +  const auth = request.cookies.get("authorization")?.value;
in #1366, the name of the cookie is `auth-token`

2024-02-26 19:20 UTC, nickbristow commented on containers/ecr-viewer/package.json
>      "local-dev": "docker compose up db seed-db -d && docker-compose logs && export DATABASE_URL=postgres://postgres:pw@localhost:5432/ecr_viewer_db && next dev",
👍

2024-02-26 21:15 UTC, emmastephenson commented on containers/ecr-viewer/src/middleware.ts
> +async function authorize_api(req: NextRequest) {
I'm kind of surprised this passes existing integration tests - shouldn't the auth trigger? Or does the CI runner automatically run in a "development" NODE_ENV?

2024-02-26 21:34 UTC, BobanL commented on containers/ecr-viewer/src/middleware.ts
> +async function authorize_api(req: NextRequest) {
So I was going to comment this somewhere else, but the default for [NODE_ENV is dev](https://nodejs.org/en/learn/getting-started/nodejs-the-difference-between-development-and-production#:~:text=Node.js%20assumes%20it%27s%20always%20running%20in%20a%20development%20environment.%20You%20can%20signal%20Node.js%20that%20you%20are%20running%20in%20production%20by%20setting%20the%20NODE_ENV%3Dproduction%20environment%20variable.). I think we need to update our dockerfile to set that variable to production so it will work when deployed.

2024-02-26 21:36 UTC, BobanL reviewed
There is one extra file and might need to update the dockerfile, but otherwise looks good to me.

2024-02-27 21:21 UTC, nickbristow commented on containers/ecr-viewer/src/middleware.ts
> +async function authorize_api(req: NextRequest) {
yeah, default is dev, you have to build it to get it to say production

2024-02-27 21:23 UTC, gordonfarrell approved these changes
Looks good!

2024-02-27 21:59 UTC, BobanL approved these changes

2024-02-28 16:21 UTC, merged