Group repeating question observations by organizer
CDCgov/phdi pull request #1385
Opened 2024-02-27 14:07 UTC by m-goggins

# PULL REQUEST

## Summary
This PR adds an `organizer` element to the repeating sections and groups observations from the `component` section of an Observation resource under a single organizer.

## Related Issue
Fixes #1369 

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-02-28 14:30 UTC, DanPaseltiner requested changes
Thanks for working through this @m-goggins! One question I'd like to discuss and one small change I think we should make before merging.

2024-02-28 14:30 UTC, DanPaseltiner commented on containers/message-parser/app/phdc/builder.py
> +            data = self.input_data.clinical_info
Since this function gets called in `_build_clinical_info` and `_build_social_history_info` could we have the selection of the data happen in those methods and then pass to this method by replacing  the `section_types` parameter with a `data` parameter? This method currently needs to do 2 things, select the appropriate data and then add the observations. By removing the responsibility for data selection we improve our separation of concerns, this method no longer needs to know what section it is adding observations to just how to add observations to a given section.

2024-02-28 14:30 UTC, DanPaseltiner commented on containers/message-parser/app/phdc/models.py
> +    )
This mixture of observation objects and lists of observation objects makes me a little nervous. Do we have any examples where we need to handle a single observation resource? In this case is there any reason why we use a list of observations with a length of 1? Having to constantly check type as we iterate through these values seems like a code smell to me. I could definitely be missing something here though.

2024-02-28 14:53 UTC, m-goggins commented on containers/message-parser/app/phdc/models.py
> +    )
I think the single observation comes up in the case where we don't have a `component` section but we can definitely change to a list length of 1. I agree that will make it simpler.

2024-02-28 14:54 UTC, m-goggins commented on containers/message-parser/app/phdc/builder.py
> +            data = self.input_data.clinical_info
Yep, that's a good suggestion!

2024-02-29 14:06 UTC, DanPaseltiner commented on containers/message-parser/app/phdc/builder.py
> +        return section
🚀

2024-02-29 14:09 UTC, DanPaseltiner approved these changes
Thanks @m-goggins!

2024-02-29 14:09 UTC, DanPaseltiner commented on containers/message-parser/app/phdc/builder.py
> +        return section
🚀

2024-02-29 14:39 UTC, merged