quick fix to re-use parquet writer for each increment of tabulated data
CDCgov/phdi pull request #139
Opened 2022-12-19 21:38 UTC by m-goggins

Per @DanielPaseltiner's catch, I updated `generate_tables` to re-use the same parquet writer for each incremental result of tabulated data. With this update, we now check once to see if the user has passed in a writer and if yes, return the same writer for re-use on each subsequent incremental chunk of tabulated data.

2022-12-19 21:56 UTC, DanPaseltiner reviewed
Thanks for addressing this @m-goggins! I do wonder if we want users to be able to pass in their own writer, or if it would be better for us to just handle everything to do with the writer internally. If the user passes in a writer for a different file than the one specified in  `output_params[table_name]["filename")` things could get wonky fast. I wasn't part of the entire design process on this work so I will defer to you and @bamader on this. 

I also think that we should make sure to close the writer, if there is one on each iteration of the for loop to ensure we are closing the file connections we open.

2022-12-20 16:08 UTC, m-goggins commented
Yes, I see your point about the writer and think it makes sense to handle it internally. When we initially developed `write_data` we hadn't yet conceived of the `output_params` file. I'll make those changes unless @bamader has a different opinion.

2022-12-20 16:38 UTC, bamader requested changes
I am absolutely for internal handling at this point. If our discovery brings up that users want to pass in their own writers, we can add that later, but major desire to avoid wonkiness with this right now. 

As for closing file connections, also agree with Dan on that. Since we're ostensibly re-using the same writer in each loop iteration, I think all we have to do is close the pq_writer at the end of the for loop before going on to the next table.

2022-12-20 16:50 UTC, DanPaseltiner commented on phdi/fhir/tabulation/tables.py
>                  db_tablename=output_params[table_name].get("db_filename", None),
Should this be:
`db_tablename=output_params[table_name].get("db_tablename", None)` ?

2022-12-20 17:36 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
>                  db_tablename=output_params[table_name].get("db_filename", None),
Oops, yes! good catch

2022-12-20 18:58 UTC, bamader approved these changes
Looks good. Thanks again for catching this, Dan! Probably saved all of us some rather head-smashing logic down the road.

2022-12-20 22:11 UTC, BradySkylight approved these changes
Great catches and discussions!

2022-12-21 18:28 UTC, merged