Generate parquet schema based on passed data type
CDCgov/phdi pull request #142
Opened 2023-01-03 20:32 UTC by nickbristow

Use passed data type to generate parquet data type. Default to string

2023-01-05 23:08 UTC, m-goggins requested changes
I think this looks good, though I will admit it has been a minute since I have looked at this section of tabulation. It would be helpful to have a docstring for the function you created and maybe a little more detail for the PR since I'm a little out of the loop.

2023-01-05 23:08 UTC, m-goggins commented on tests/tabulation/test_tables.py
>      # Batch 1 tests creating a new parquet file and returning a writer
I think we should also add an assert statement that we have returned the writer. Something like `pq_writer is not None`

2023-01-05 23:08 UTC, m-goggins commented on tests/tabulation/test_tables.py
>      # Batch 2 tests appending to existing parquet using previous writer
For this one, I would add an assertion that tests whether the additional data as has been added. Something like the length of the updated file's contents.

2023-01-13 18:05 UTC, nickbristow commented on phdi/tabulation/tables.py
> +def _create_pa_schema_from_table_schema(
Yes done

2023-01-13 18:06 UTC, nickbristow commented on tests/tabulation/test_tables.py
>      # Batch 1 tests creating a new parquet file and returning a writer
Yes, done

2023-01-19 21:22 UTC, m-goggins requested changes
A couple of return statements and docstrings need to be added, but the tests look much more robust and I'm glad we got them figured out last week 😄

2023-01-19 21:22 UTC, m-goggins commented on phdi/tabulation/tables.py
> +    :param row_data: A list that is made of multiple arrays
ditto `:return:`

2023-01-19 21:22 UTC, m-goggins commented on phdi/tabulation/tables.py
> +def _create_parquet_data(data: List[List], pq_schema: pa.Schema) -> List[List]:
ditto docstring

2023-01-19 21:22 UTC, m-goggins commented on tests/tabulation/test_tables.py
> +    # Batch 3 tests appending to existing parquet using previous writer
Do we need Bacth 3? How is it different than batch 2 above on line 210?

2023-01-24 17:16 UTC, m-goggins approved these changes
Made one suggestion but it looks good to me!

2023-01-24 17:16 UTC, m-goggins commented on tests/tabulation/test_tables.py
> +    # Batch 3 tests appending to existing parquet using previous writer
Gotcha, that makes sense!

2023-01-24 17:16 UTC, m-goggins commented on phdi/tabulation/tables.py
> +    :return: A list of lists.
```suggestion
    :return: A list of lists with data types specified in the pyarrow schema.
```

2023-01-31 19:17 UTC, bamader approved these changes
Wow this took me longer than I wanted to get back into lol. Code itself looks good. If possible, I might suggest adding some more inline comments to explain what's going on with the code flow (I know it's not necessary in some places, like the if/elif ladders handling specific cases, but parts of this feel sufficiently in the weeds to me so as to warrant inline clarification). That's non-blocking, however, so I'll leave that to your discretion. There's also one hanging commented line left in the code that I flagged for you to delete.

2023-01-31 19:17 UTC, bamader commented on phdi/tabulation/tables.py
> +        # parquet_data = tabulated_data
nit: remove comment

2023-01-31 19:30 UTC, nickbristow commented
@bamader added some extra comments

2023-03-06 17:39 UTC, emmastephenson commented
@nickbristow to try downloading the latest version of black and running via command line.

2023-03-06 19:03 UTC, merged