Boban/1343 no data
CDCgov/phdi pull request #1442
Opened 2024-03-11 15:45 UTC by BobanL

# PULL REQUEST

## Summary
Replace "N/A" with "No data"

## Related Issue
Fixes #1343 

## Additional Information
Some refactoring was done to make things simpler like just leaving "Value" as undefined for "N/A" options. 

## Demo
![image](https://github.com/CDCgov/phdi/assets/10108172/aff0f6e1-8b1a-487c-9b0e-d0ddab13027c)

2024-03-11 15:55 UTC, BobanL commented on containers/ecr-viewer/src/app/utils.tsx
> +  value?: string | React.JSX.Element;
This means the same thing

2024-03-11 15:55 UTC, BobanL commented on containers/ecr-viewer/src/app/utils.tsx
> +    return undefined;
Return undefined instead of "N/A" to make it more clear that it's not a date.

2024-03-11 15:55 UTC, BobanL commented on containers/ecr-viewer/src/app/utils.tsx
> +      );
If evaluate has no value, add formatting to the cell data.

2024-03-11 16:48 UTC, sarahtress commented
@BobanL this looks good to me, thanks!

2024-03-11 20:39 UTC, nickbristow requested changes
Can you add some JSDoc commenting to some of the major functions you've changed?

2024-03-12 13:23 UTC, BobanL commented on containers/ecr-viewer/src/app/view-data/components/tests/ActiveProblems.test.tsx
> +      returnProblemsTable(activeProblemsData, fhirPathMappings)!,
[The `!` is a non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator). This fixes the problem where the IDE was flagging that `render` only accepts `JSX.Elements` or `string` and not undefined.

2024-03-12 13:23 UTC, BobanL commented on containers/ecr-viewer/src/app/utils.tsx
> +  fhirBundle: Bundle,
Removed the option to send `undefined` since it should never be called with that value.

2024-03-12 13:23 UTC, BobanL commented on containers/ecr-viewer/src/app/utils.tsx
> +  resources: FhirResource[],
This was incorrectly typed to `React.JSX.Element[]` and should be a `FhirResource[]` instead.

2024-03-12 13:23 UTC, BobanL commented on containers/ecr-viewer/src/app/utils.tsx
> +  let headers = columns.map((column, index) => (
Replace `.forEach` with [`.map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) for clarity since we need the return from every value in `columns`.

2024-03-12 13:23 UTC, BobanL commented on containers/ecr-viewer/src/app/utils.tsx
> -      ) : (
Remove the `isFirstCell` logic because for [accessibility on a table with only one header only the first row or column needs to have the scope. ](https://www.w3.org/WAI/tutorials/tables/one-header/#table-with-ambiguous-data)

2024-03-12 13:23 UTC, BobanL commented on containers/ecr-viewer/src/app/utils.tsx
> +      new Date(a.onsetDateTime ?? "").getTime(),
The weird comma at the end is added by linter.

2024-03-12 13:23 UTC, BobanL commented on containers/ecr-viewer/src/app/utils.tsx
> +      new Date(b.onsetDateTime ?? "").getTime() -
Default to empty string since `new Date()` only accepts string and `Condition.onsetDateTime` can be string or undefined.

2024-03-12 14:33 UTC, merged