Implement double metaphone
CDCgov/phdi pull request #148
Opened 2023-01-10 16:38 UTC by bamader

This PR implements the double metaphone algorithm in the PHDI library via a collection of utilities, wrappers, and FHIR operations. The number of changes looks longer than it actually is because there were changes to the `.toml` and `.lock` files in poetry, which you don't actually need to look at.

2023-01-11 18:15 UTC, m-goggins requested changes
Looks pretty good! I would just add a couple more robustness checks/names that are more specific to LAC population and demonstrate how the function handles accented names.  I also left a more general comment on if/how we want to handle maiden names.

2023-01-11 18:15 UTC, m-goggins commented on phdi/fhir/harmonization/standardization.py
> +def double_metaphone_patient(patient: dict, dmeta=None) -> List[dict[str, List[str]]]:
Wondering if we would also want to consider maiden names? Or maybe how we might want to incorporate maiden names more generally?

2023-01-11 18:15 UTC, m-goggins commented on phdi/harmonization/standardization.py
> +    have been performed.
I don't think we need to include the referential stuff here. It can go in a tutorial/other documentation. Here's how I would change it: 

```
Performs the double metaphone algorithm on a given string. Returns a list holding the primary and secondary
    phonetic encodings of the given string (including None if there is no
    valid secondary encoding). This function expects basic text cleaning (e.g.
    removal of numeric characters, trimming of spaces, etc.) to already
    have been performed.
```

2023-01-11 18:15 UTC, m-goggins commented on tests/fhir/harmonization/test_fhir_harmonization.py
> +    )
Can we do a non-English sounding name? Maybe one that is representative of LAC patient pop? I'm also curious to see how it handles accented names vs non-accented, e.g.,  Jose vs José.

2023-01-11 18:32 UTC, DanPaseltiner commented on phdi/fhir/harmonization/standardization.py
> +    return dms
Should the encode strings just be returned in patient resources in a fhir bundle? Later on we won't have to constantly recompute.

2023-01-11 18:44 UTC, bamader commented on phdi/fhir/harmonization/standardization.py
> +def double_metaphone_patient(patient: dict, dmeta=None) -> List[dict[str, List[str]]]:
This actually will already consider maiden names. Maiden is one of the FHIR-recognized values for the `use` property in a `HumanName` object (https://build.fhir.org/datatypes.html#HumanName) so we'll already be covered with the DM representation of it.

2023-01-11 18:45 UTC, bamader commented on phdi/harmonization/standardization.py
> +    have been performed.
That's fair. The only reason I had it in there was because I think a lot of people have heard of SoundEx but most people may not have heard of double metaphone, even though it's developed by the same guy and he was improving on his work. But it's definitely not something relevant to the code functioning so I can move it elsewhere.

2023-01-11 18:50 UTC, bamader commented on tests/fhir/harmonization/test_fhir_harmonization.py
> +    )
Yeah that's a good idea. Good examples that come to mind (in addition to Jose) are Dominic, Alejandro, Diego, Xavier, Jorge, Eduardo, and Sofia vs Sophia. I think I'm definitely going to use the Sofia/Sophia as part of the similarity assertions, but any favorites for the more general processing part of the tests?

2023-01-11 19:16 UTC, m-goggins commented on phdi/fhir/harmonization/standardization.py
> +def double_metaphone_patient(patient: dict, dmeta=None) -> List[dict[str, List[str]]]:
Oh awesome. For some reason I thought it was stored differently, but you are correct.

2023-01-11 19:16 UTC, m-goggins commented on tests/fhir/harmonization/test_fhir_harmonization.py
> +    )
Those seem sufficient to me for now

2023-01-12 14:28 UTC, bamader commented on phdi/fhir/harmonization/standardization.py
> +    return dms
Just noting here that you and I spoke yesterday and then Brady and I spoke, and we've got an extension storage solution implemented. Great catch, and this is now solved.

2023-01-12 16:14 UTC, m-goggins approved these changes
I found one remaining typo to fix but other than that, it looks good to go!

2023-01-12 16:14 UTC, m-goggins commented on phdi/harmonization/standardization.py
> +    This function experts basic text cleaning (e.g. removal of numeric characters,
**expects

2023-01-12 16:51 UTC, bamader commented on phdi/harmonization/standardization.py
> +    This function experts basic text cleaning (e.g. removal of numeric characters,
Lol, function clearly not written by an expert 🤣

2023-01-12 17:05 UTC, merged