Convert to fhir
CDCgov/phdi pull request #15
Opened 2022-08-11 20:12 UTC by bamader

This PR adds a fast-follows util for converting incoming messages to FHIR. New logic is introduced that allows the function to automatically identify the data type and appropriate template of an incoming message so that file extensions no longer need be relied upon. This ticket has several dependencies on other work, however, and so as a result, there remain several outstanding TODOs:

1. Update the convert-to-fhir function with corrected implementations of both CredsManager and http_request_with_reuath, once those have been successfully migrated / revised into the new taxonomy
2. Write / port test cases for the convert_to_fhir function once 1 is accomplished above; currently, tests exist only for the parameter determining function

2022-08-16 18:36 UTC, bamader commented on phdi/fhir/utils.py
> +    template_mappings: dict = CCDA_CODES_TO_CONVERSION_RESOURCE,
I spoke with Bryan during office hours and we agreed to leave the CCDA template mappings _in_ but remove the ability for the user to specify a different set of template mappings. He mentioned that the helper function I'd set up was already what he was envisioning for a modularized "router" style function, so all that needed to be done was remove burden from the user to specify a mapping.

Also, we discussed whether to throw a key error if a message's root template doesn't map to something specified or whether to just use a default value of "CCD". We came to a middle ground of allowing a user to specify whether they should use a default value in the event a resource doesn't have an exact mapping template; this way there's no fail silently but also a user can press forward if they want.

2022-08-16 21:07 UTC, spencer-skylight requested changes
Looking good!  Just a few minor things to review.

2022-08-16 21:07 UTC, spencer-skylight commented on phdi/fhir/utils.py
> +            if "ClinicalDocument" in root.tag:
I think we should check the whole string here `{urn:hl7-org:v3}ClinicalDocument` because the namespace is meaningful and should always be set to that value for a valid CCDA message.

2022-08-16 21:07 UTC, spencer-skylight commented on phdi/fhir/utils.py
> +                        "code" in child.tag
Check full string including namespace here as well.

2022-08-17 12:00 UTC, bamader commented on phdi/fhir/utils.py
> +def convert_to_fhir(
LOL whoops I completely forgot about that 😂 . We literally just had an hour long meeting around this and it totally slipped my mind.

2022-08-17 12:01 UTC, bamader commented on phdi/fhir/utils.py
> +def convert_to_fhir(
We decided _not_ to put this in its own package directory, right? As in, we're not creating a `conversion` module which will contain an `__init__.py`?

2022-08-17 12:13 UTC, bamader commented on phdi/fhir/utils.py
> +        formatted_code = extracted_code.replace("^", "_")
Good call, thanks for this logic Spencer. I thought all HL7 messages would just conform to an easily swapped structure, but I'll chalk that up to my domain inexperience. I've implemented this change in the logic.

2022-08-17 12:14 UTC, bamader commented on phdi/fhir/utils.py
> +    except hl7.exceptions.ParseException:
Yeah the idea was to have this always operate on an individual message (since this is just the building blocks level, the user can build it out into their own batch pipeline if they want). I'll make the change with this piece of logic.

2022-08-17 14:45 UTC, spencer-skylight commented on phdi/fhir/utils.py
> +def convert_to_fhir(
Trying to think through this... if we make it like the other modules, I think we could put this in phdi/fhir/conversion/convert.py, and `import`, and set `__all__` in `__init__.py` in the same directory.  This would be roughly the same as phdi/fhir/linkage/link.py that Kenneth just created. Make sense?

2022-08-17 14:52 UTC, spencer-skylight reviewed
Almost there...

2022-08-17 14:52 UTC, spencer-skylight commented on phdi/fhir/conversion.py
> +            elif len(extracted_code_tokenized) == 2:
Nit/question: should we raise an exception if we can't derive message structure?

2022-08-17 14:52 UTC, spencer-skylight commented on phdi/fhir/conversion.py
> +            extracted_code_tokenized = extracted_code.split(parsed_msg.separators[3])
I'm probably being paranoid, but maybe we should create a unit test for when MSH-9.3 is set?

2022-08-17 15:26 UTC, bamader commented on phdi/fhir/conversion.py
> +            extracted_code_tokenized = extracted_code.split(parsed_msg.separators[3])
No I don't think that's being paranoid, it's being thorough. This is probably one of the most "high-risk" parts of the building blocks, in the sense that it's the most likely to be exposed to weird edge cases, so I'd rather document that our functionality works in those cases. I'll write a case for it.

2022-08-17 18:30 UTC, spencer-skylight approved these changes
LGTM!

2022-08-17 21:42 UTC, merged