Create new "dibbs" package
CDCgov/phdi pull request #1597
Opened 2024-04-04 20:36 UTC by nickclyde

# PULL REQUEST

## Summary
What changes are being proposed?

## Related Issue
Fixes #

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-04-04 22:22 UTC, robertmitchellv approved these changes
:shipit:

2024-04-04 22:47 UTC, m-goggins approved these changes
🚀

2024-04-05 13:59 UTC, DanPaseltiner requested changes
Thank you @robertmitchellv and @nickclyde for putting this together so quickly! 🚀 😲 I have left some comments on mostly relatively minor things I think we should consider. Before merging I'd like us to think through our release process. I see the advantages of building one common DIBBs base image, but there are some challenges. I think a shared understanding of what the future intended release process will look like should help us think through the relative pros and cons here.

2024-04-05 13:59 UTC, DanPaseltiner commented on .github/workflows/buildContainers.yaml
🚀

2024-04-05 13:59 UTC, DanPaseltiner commented on .github/workflows/createNewRelease.yaml
Love to see all these actions updates.

2024-04-05 13:59 UTC, DanPaseltiner commented on containers/dibbs/.gitignore
Should this live here or in the `.gitignore` at root level? I'm not opposed to this if there is a compelling reason, but want to be careful of the proliferation of `.gitignore` files.

2024-04-05 13:59 UTC, DanPaseltiner commented on containers/dibbs/Dockerfile
Could we throw a `pip` update in here to ensure we are always using the most current version?

2024-04-05 13:59 UTC, DanPaseltiner commented on containers/dibbs/dibbs/base_service.py
> +    "email": "dmibuildingblocks@cdc.gov",
I think we have a new official email now. I will see if I can track it down in slack and get follow up here.

2024-04-05 13:59 UTC, DanPaseltiner commented on containers/dibbs/dibbs/base_service.py
> +            return await call_next(request)
Could we add a doc string and type hints here?

2024-04-05 13:59 UTC, DanPaseltiner commented on containers/dibbs/pyproject.toml
> +description = "A short description of your project"
Could add our own description? just 1-2 sentences is fine.

2024-04-05 13:59 UTC, DanPaseltiner commented on containers/dibbs/requirements.txt
> +pydantic==1.10.9
Why are we locking the pydantic version here? I think if there are specific containers that need a specific pydantic version that should be handled at the individual container level. Ideally the base image is always pushing us to stay current.

2024-04-05 13:59 UTC, DanPaseltiner commented on containers/tefca-viewer/dev-requirements.txt
> +httpx
Is `httpx` truly only needed for dev? I though `pytest` somehow relied on it. Maybe I'm wrong or not remembering something correctly.

2024-04-05 14:00 UTC, DanPaseltiner commented on containers/dibbs/dibbs/base_service.py
> +    "email": "dmibuildingblocks@cdc.gov",
Found it!

```suggestion
    "email": "dibbs@cdc.gov",
```

2024-04-05 15:39 UTC, nickclyde commented on containers/dibbs/.gitignore
Yeah good call, I'll move to the root `.gitignore` 👍🏻

2024-04-05 15:41 UTC, nickclyde commented on containers/dibbs/requirements.txt
> +pydantic==1.10.9
All of the containers are currently locked to this version. I think there was a specific reason for that, but I don't remember what it was. I agree we should try to update, but maybe we should save it for another PR?

2024-04-05 15:42 UTC, nickclyde commented on containers/tefca-viewer/dev-requirements.txt
> +httpx
Yeah it's needed for some tests, but pytest is also only needed for dev! No need to bundle it into our containers

2024-04-05 18:48 UTC, DanPaseltiner approved these changes

2024-04-05 19:38 UTC, merged