Brady/date standardization
CDCgov/phdi pull request #163
Opened 2023-02-03 00:32 UTC by BradySkylight

This PR includes all functions necessary to standardize the birthDate within a bundle or a single patient resource.  The base function accepts a string dob as well as a format string (indicating the format in which the date will be supplied).  This date format is defaulted to the FHIR standard of YYYY-MM-DD, as we anticipate this function being used in conjunction with a FHIR bundle or single patient resource.  However, this function is flexible to look for other delimiters as well as the position in which each of the date components exist.  If the format does not use the one specified by FHIR (STu3 and R4) then it places it in the YYYY-MM-DD format and stores it in the bundle/resource.  If the date is null or the format doesn't match up with the date or garbage data is supplied an exception is logged (for now, we can go back and change this later) as well as the dob being updated to "" in the bundle/resource.  This function also ensures that the date is valid and is not > today.

2023-02-06 23:29 UTC, m-goggins requested changes

2023-02-06 23:29 UTC, m-goggins commented on phdi/harmonization/standardization.py
> +                index = index + 1
A lambda function in the wild! This code definitely works but I think we could make it slightly less dense by taking advantage of the fact that we have both the `raw_dob` and the `format` as well as the delimiter. I would create a list of the `raw_dob` and `format` and then iterate through both lists at the same time using `zip()` to create the `date_dict`. 

Something like:
```
raw_dob_values = raw_dob.split(delim)
format_values = format.replace("%","").lower().split(delim)

date_dict = {}
for format_value, dob_value in zip(format_values,raw_dob_values):
    date_dict[format_value] = dob_value
```

You could condense it further (if you still think it is understandable) to something like:
```
date_dict = {}
for format_value, dob_value in zip(format.replace("%","").lower().split(delim),raw_dob.split(delim)):
    date_dict[format_value] = dob_value
```

2023-02-06 23:29 UTC, m-goggins commented on phdi/harmonization/standardization.py
> +            if _validate_date(date_dict["year"], date_dict["month"], date_dict["day"]):
If you make the changes that I suggest above, you would need to change this to `_validate_date(date_dict["y"], date_dict["m"], date_dict["d"])1

2023-02-06 23:29 UTC, m-goggins commented on phdi/harmonization/standardization.py
> +                    + date_dict["day"]
ditto changes here to "y","m","d"

2023-02-06 23:29 UTC, m-goggins commented on phdi/harmonization/standardization.py
> +                error_msg = f"Invalid birth date supplied: {raw_dob}"
Instead of an if/else statement with an error message, we should use a try/except statement that raises an error if it doesn't work. See examples of this in the `load_schema` function in phdi.tabulation.tables

2023-02-06 23:29 UTC, m-goggins commented on phdi/harmonization/standardization.py
> +        logging.exception(error_msg)
I'm not 100% but I've seen in other TODO statements elsewhere in our code that we are (or were at some point) moving away from logging and instead just using exceptions. I'm not sure if this still applies.

2023-02-06 23:29 UTC, m-goggins commented on phdi/harmonization/standardization.py
> +            is_valid_date = False
I would add a couple more checks: 

- Is the month value between 1 and 12?
- Is the days less than 32? We could add more sophisticated checks around 28, 29, 30, and 31 day checks for specific months if you think it's vital, but less than 32 should catch the egregious data entry errors for now.

2023-02-06 23:30 UTC, m-goggins commented on phdi/harmonization/standardization.py
> +            is_valid_date = False
I actually think that maybe we should add the specific day checks since it's not too hard and the chances of us coming back to this any time soon are low.

2023-02-06 23:56 UTC, BradySkylight commented on phdi/harmonization/standardization.py
> +        or a null value
This is way more paired down, which I am all for.  Thank you and your suggestions make sense.

2023-02-06 23:57 UTC, BradySkylight commented on phdi/harmonization/standardization.py
> +    if raw_dob and raw_dob.strip():
Yes, I was checking to see if the raw_dob was empty or null or just whitespace.  When I was testing I was getting some errors.  I can remove these and see if the tests are still working etc...  Thanks!

2023-02-07 13:35 UTC, bamader requested changes
Agree with Marcelle on most of the pythonic comments, but of larger concern to me is the lockfile, which shouldn't be feeling changes of that magnitude for a single package addition. Something funky is definitely going on, and it's not the Funky Chicken coffee in my mug.

2023-02-07 13:35 UTC, bamader commented on phdi/harmonization/standardization.py
> +            is_valid_date = False
Marcelle I would agree with you here, but I think the `datetime.datetime` constructor actually handles that for us. I looked at the documentation for the constructor and it says that if an argument outside a valid range is given, it will throw a `ValueError` (https://docs.python.org/3/library/datetime.html#datetime-objects). So I believe the code is already checking for those things.

2023-02-07 13:35 UTC, bamader commented on phdi/harmonization/standardization.py
> +    error_msg = ""
Ironically I think he does need them here not because he's initializing them, but because he's conditionally assigning them. `output` gets returned at the bottom of the function, but outside of this statement, the only time it gets set is line 257 which is in an `if` statement. A similar thing happens with `error_msg` only being set in some `else` clauses. Granted there's a lot of comments in this area of github so my ability to tell what's indented and what's not is basically shot lol, but I think he does need these as defaults to make tests happy (though if everything runs without them being default assigned up top, that works too).

2023-02-07 13:35 UTC, bamader commented on phdi/harmonization/standardization.py
> +    if raw_dob and raw_dob.strip():
I definitely see how you could be getting an error if `raw_dob` was a `None` type. You can't call string manipulation functions on `None`. I'd be fine leaving the `if raw_dob` check in, but I agree with Marcelle there should be no need to check if `raw_dob.strip()` exists because most string operations shouldn't fail on an empty string, they should just do nothing. If you keep seeing errors when you take out that part of the check, I'm okay leaving it in.

2023-02-07 13:35 UTC, bamader commented on phdi/harmonization/standardization.py
> +        delim = detect(format.strip("%"))
^^^ this is the way

2023-02-07 13:35 UTC, bamader commented on phdi/harmonization/standardization.py
> +                index = index + 1
I'm normally a secret fan of lambda functions, but I agree with Marcelle here that this one--running some key sorting inside of a conditional for loop--is just a bit too big brain for me 🧠 . I really like the first snippet Marcelle gave where we explicitly create and zip the two objects. I'm not normally a fan of `zip` either (no fault of its own, it's an archaic dislike I have lol 😅 ), but in this case our guaranteed ordering of the date parts as well as the clarity of the code makes it a much better alternative to me.

2023-02-07 13:35 UTC, bamader commented on phdi/harmonization/standardization.py
> +                error_msg = f"Invalid birth date supplied: {raw_dob}"
Bonus perk of try/except is that it _might_ get rid of the conditional default assignments to `output` and `error_msg` depending on how the code is structured (though not sure)

2023-02-07 13:35 UTC, bamader commented on phdi/harmonization/standardization.py
> +        logging.exception(error_msg)
We are! I was going to leave this comment like six times here, but we made an architectural decision to just raise exceptions and let the caller set up any kind of logging and reporting they wanted to. I think all you need to do within the appropriate try/except block is raise an exception (of the correct type--probably lots of `ValueError` here though this list will tell you what's most appropriate https://docs.python.org/3/library/exceptions.html#concrete-exceptions) that has meaningful information content.

2023-02-07 13:35 UTC, bamader commented on poetry.lock
> -black = []
Just leaving the comment here, but _all_ of these metadata files changes are very concerning to me. The lock file shouldn't be changing with this much of an impact just by adding one package. By way of comparison, I ran `poetry add detect-delimiter`, grabbed the same version, and got only a very small change in the lockfile, with none of these metadata changes with it. I think something is up with the way your virtual environment is trying to push cached versions of these packages into the repo.

2023-02-07 17:58 UTC, BradySkylight commented on phdi/harmonization/standardization.py
> +    error_msg = ""
Yes, precisely...however, I may be able to subvert this by some of the other changes I'm making based upon all your feedback.  I'll see if these are needed.

2023-02-07 20:27 UTC, BradySkylight commented on poetry.lock
> -black = []
This is concerning.  I only performed poetry add detect-delimiter and I don't see why it would need all those additional packages.  Any thoughts on how to untangle this?  I have a new machine and thereby a new VE, so this shouldn't be a problem going forward.  However, would you be willing to update this file in this branch with the detect_delimiter included @bamader ?

2023-02-07 21:18 UTC, BradySkylight commented on phdi/harmonization/standardization.py
> +        delim = detect(format.strip("%"))
Done!

2023-02-07 22:37 UTC, m-goggins commented on phdi/harmonization/standardization.py
> +            is_valid_date = False
Oh totally missed that. Whew! I was worried that we were trying to handle dates on our own.

2023-02-07 22:39 UTC, m-goggins commented on poetry.lock
> -black = []
@BradySkylight I have had success with `poetry lock --no-update` after I added a package to the .toml file.

2023-02-08 02:06 UTC, BradySkylight commented on phdi/harmonization/standardization.py
> +                error_msg = f"Invalid birth date supplied: {raw_dob}"
Do we want an exception to be raised that will stop processing a bundle if the dob is invalid?

2023-02-08 02:16 UTC, BradySkylight commented on phdi/harmonization/standardization.py
> +                index = index + 1
This tremendously simplifies things.  Ugh... I was looking for something like zip() that would handle the scenario so did the best with the tools I had available.  It worked at least...but thank you so much because this is much cleaner and simple.

2023-02-08 02:33 UTC, BradySkylight commented on phdi/harmonization/standardization.py
> +            is_valid_date = False
Correct.  This was the 'best practice', at least from what I could find about validating dates.  It's easier than writing our own code to validate the days and months etc...

2023-02-09 17:08 UTC, bamader requested changes
The tests look fine to me, but I do still have lingering concerns around the lockfile changes. More generally though I think it might be worth talking about the scope of work entailed by this PR. I was under the impression we would be standardizing a broader inputs of dates into a uniform output as well as validating, but this PR does validation while stipulating that input dates already have a certain format, which seems to me to be less useful to us if we want to accept broader data.

2023-02-09 17:14 UTC, BradySkylight commented on phdi/harmonization/standardization.py
> +def _validate_date(year: str, month: str, day: str) -> bool:
Will do.  That makes sense to me.

2023-02-09 17:15 UTC, BradySkylight commented on phdi/harmonization/standardization.py
> +def standardize_birth_date(raw_dob: str, format: str = "%Y-%m-%d") -> str:
That is the style of formatting used by the Python date, datetime functions though.  I guess we could 'add' them back in when actually applying the format?  I don't like that though...but also understand your point.  Any thoughts?

2023-02-09 17:22 UTC, BradySkylight commented on pyproject.toml
> +pyarrow = "^11.0.0"
I did this change manually to resolve the issue I was running into.

2023-02-09 17:24 UTC, BradySkylight commented on phdi/harmonization/standardization.py
> +        )
I could definitely reform this to utilize regex (I love them btw...), but was just trying to get something pretty basic out.  My understanding was that this was specifically for DOB with the flexibility to be reutilized for other date formatting down the road.  Though, I must point out, that most dates are standardized already during the 'convert to fhir' BB/process prior to the standardizations.   Let me have a short convo with you and discuss this.

2023-02-09 17:31 UTC, BradySkylight commented on phdi/harmonization/standardization.py
> +        )
The variants of the different order of date components should be handled however.

2023-02-10 20:24 UTC, bamader approved these changes
WE GOT THERE. This looks much better to me and delivers on what we talked about very well. I'm also now convinced that the lockfile changes here are real changes that are valid parts of adding `detect-delimiter` lol

2023-02-10 20:27 UTC, m-goggins approved these changes

2023-02-10 20:27 UTC, merged