Show the Orginal Timezone
CDCgov/phdi pull request #1678
Opened 2024-04-22 19:20 UTC by JNygaard-Skylight

# PULL REQUEST

## Summary
What changes are being proposed?

## Related Issue
Fixes #

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-04-24 15:28 UTC, JNygaard-Skylight commented
@sarahtress This is ready for design review: 
<img width="1468" alt="image" src="https://github.com/CDCgov/phdi/assets/141273852/3c19886f-f5dd-4c07-a0ae-d8565495e67e">
<img width="1470" alt="image" src="https://github.com/CDCgov/phdi/assets/141273852/00cec428-99bf-4123-849f-310593b60211">

2024-04-24 18:05 UTC, nickbristow requested changes

2024-04-24 18:05 UTC, nickbristow commented on containers/ecr-viewer/src/app/format-service.tsx
> +    return `${month}/${day}/${year} ${hours12}:${minutes} ${suffix} ${timeZone === undefined ? "UTC" : timeZone}`;
you can rewrite the second part as
```${timeZone || "UTC"}```

2024-04-24 18:05 UTC, nickbristow commented on containers/ecr-viewer/src/app/view-data/components/tests/__snapshots__/LabInfo.test.tsx.snap
> +                      undefined/undefined/09/28/2022 2:00 PM PD
Whats this undefined? Is that intentional?

2024-04-24 18:07 UTC, BobanL commented on containers/ecr-viewer/src/app/format-service.tsx
> +export const formatDateTime = (dateTimeString: string): string => {
Can you write a jsdoc for this function and include the example format you expect dateTimeString to be in?

2024-04-29 14:33 UTC, nickbristow approved these changes

2024-04-29 16:06 UTC, merged