Add function to refine eCR messages
CDCgov/phdi pull request #1691
Opened 2024-04-25 13:13 UTC by m-goggins

# PULL REQUEST

## Summary
Given an optional string of sections to include (e.g., "social history, labs", we can now use the `refine` function to return an eCR with only the specified sections. The `refine` function uses XPaths to decide which sections of the eCR should be included. 

There is still work to do to ensure that the "headers" of an eCR are included in the output (e.g., the assigned author section etc.) but I created a separate ticket for that work (#1684).

## Related Issue
Fixes #1555 

## Additional Information
There might be a better way to store the test assets as a single file and to deal with the namespaces but I wanted to get feedback on the `refine` function itself rather than let those details hold up the PR. Once this PR has merged, it will be much easier for multiple people to work on the refiner work simultaneously.

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-04-25 14:28 UTC, DanPaseltiner requested changes
Thanks for getting this going @m-goggins. Really exciting to see eCR filtering actually happening in code after so much talk. There are a few things I think we can improve on, but generally I really like this approach.

2024-04-25 14:28 UTC, DanPaseltiner commented on containers/message-refiner/app/main.py
> +        sections_xpath_expression = "or".join(
This `or` is pretty slick!

2024-04-25 14:28 UTC, DanPaseltiner commented on containers/message-refiner/app/main.py
> +        sections = validate_sections_to_include(sections_to_include)
I wonder if the call to `validate_sections_to_include` should not be nested within `refine`, but instead called in `refine_ecr` before `refine`. First, less nesting is ofter easier to reason about, but more importantly by validating the sections early and independently we have an opportunity to return a `422` response to the client if they have given us sections we don't know how to handle.

2024-04-25 14:28 UTC, DanPaseltiner commented on containers/message-refiner/app/main.py
> +    if sections_to_include is None:
We are checking whether `sections_to_include` is null here and on line 41. I think we can probably do this just once.

2024-04-25 14:28 UTC, DanPaseltiner commented on containers/message-refiner/app/main.py
> +        refined_data = refine(data, sections_to_include)
If we make this line `data = refine(data, sections_to_include)`. Then we can else below and simply `return Response(content=data, media_type="application/xml")`

2024-04-25 15:03 UTC, m-goggins commented on containers/message-refiner/app/main.py
> +    }
Yeah, expecting LOINCs is more robust. I wasn't sure if that was a reasonable expectation but I like the idea of providing the documentation to ensure we get LOINCs

2024-04-25 20:07 UTC, DanPaseltiner commented on containers/message-refiner/app/main.py
> +                )
I don't think we should raise an exception here because that will kill things and ultimately result in the client receiving a `500 internal server error` response. I think this function should return `section_loincs` as well as something like `error_message`. Then in `refine_ecr` if `error_message != ""` we can return a 422 and include the message we currently creating.

2024-04-25 20:08 UTC, DanPaseltiner commented on containers/message-refiner/app/main.py
> +                )
If you'd like to handle this in another PR that works for me. I don't want to keeping blocking this PR for something that can be addressed separately.

2024-04-25 20:10 UTC, DanPaseltiner approved these changes
Thanks for the additional refinements on the refiner (haha). Left one more comment about validation of section codes. We could address in another PR. If you would like to do this @m-goggins could you please add a ticket to the backlog so we don't loose sight of it?

2024-04-26 14:39 UTC, DanPaseltiner commented on containers/message-refiner/app/main.py
> +    raw_message = ET.fromstring(raw_message)
Sorry to keep coming back with other things. We should probably have some error handling here in case we can't successfully parse to etree. I wonder if this should get pulled out into it's own function so that we can easily return a `400` to the client if they send us a message we can't parse.

2024-04-26 14:45 UTC, m-goggins commented on containers/message-refiner/app/main.py
> +    raw_message = ET.fromstring(raw_message)
That's a good point! I'm going to add it as a ticket to the backlog

2024-04-26 15:11 UTC, merged