Getting Clinical Services from SNOMED
CDCgov/phdi pull request #1795
Opened 2024-05-06 20:55 UTC by robertandremitchell

# PULL REQUEST

## Summary
This implements the helper function that will be needed to take SNOMED condition codes provided by a user and return them in a structure (defined here: https://app.zenhub.com/workspaces/skylight-dibbs-viper-6480ba23b5a07644e0e46d23/issues/gh/cdcgov/phdi/1788) that will allow us to use the API endpoint for the ecr-refiner.

## Related Issue
Fixes #1756 

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-05-07 22:01 UTC, akintner commented on containers/vocab-mapper/app/utils.py
> +pprint.pprint(get_clinical_service_dict("276197005, junk"))
If this is a relic from the mob session earlier, you'll probably want to remove eventually.

2024-05-08 12:40 UTC, robertandremitchell commented on containers/vocab-mapper/app/utils.py
> +pprint.pprint(get_clinical_service_dict("276197005, junk"))
ha, yeah, good catch, thanks! 😅  
removed!

2024-05-08 18:16 UTC, DanPaseltiner requested changes
Super cool to see this working! Thank you @robertandremitchell and Vocabulizer team for your work here. A few thoughts below on how I think we can refactor things a bit.

2024-05-08 18:16 UTC, DanPaseltiner commented on containers/vocab-mapper/app/utils.py
> +        cursor.execute(sql_query, snomed_id)
I believe `sqlite3` automatically handles sanitization when using `execute` like this. Therefore, I think we can rename and simply `sanitize_inputs_to_list` to just handle transforming a comma delimited string into a `list`.

2024-05-08 18:16 UTC, DanPaseltiner commented on containers/vocab-mapper/app/utils.py
> +        }
Could we flatten things out a bit here to have each function do ideally only one thing and make the input of  `get_clinical_service_dict` be a list of snomed codes? Meaning we would call `sanitize_inputs_to_list` and then pass the return value into this function as a param?

2024-05-08 18:16 UTC, DanPaseltiner commented on containers/vocab-mapper/app/utils.py
> +            clinical_service_dict.pop(type, None)
Could we pull each of these steps out into their own functions that get called with the output of this function? I guess that will also require renaming this function. We are just doing a lot of different things in here and from testing and reusability standpoints breaking things up into smaller units that are decouple will likely benefit us.

2024-05-08 19:45 UTC, bamader commented on containers/vocab-mapper/app/utils.py
> +        }
Big +1 to this, I like keeping the input signature as small as possible. The function that submits the query to the DB shouldn't have to worry about the typing, imo.

2024-05-08 20:06 UTC, DanPaseltiner commented on containers/vocab-mapper/app/utils.py
> +            clinical_service_dict.pop(type, None)
I'm happy to have a single format function that is called with the data in whatever form it comes back from the query. Really I just don't want formatting to be coupled to the query. I think we should

1. Prepare list of conditions codes
2. Pass list of conditions codes into a function to query the DB
3. Take the data that comes back from the DB and format as needed

3 functions that can be composed as opposed to called within each other. 

If we need to change how to format this data we should not have to touch the logic for querying the DB.

2024-05-08 20:17 UTC, robertandremitchell commented on containers/vocab-mapper/app/utils.py
> +        }
makes sense. new push has this split out a bit more.

2024-05-08 20:20 UTC, robertandremitchell commented on containers/vocab-mapper/app/utils.py
> +        return [value.strip()]  # No delimiter found, return the single value
I used to be a big into using `re` for a lot of string stuff I've needed to do. `re.sub` was my bestie

2024-05-08 20:23 UTC, robertandremitchell commented on containers/vocab-mapper/app/utils.py
> +    :param clinical_services: List of clinical service types to keep
yeah, this is a good call out, I had a tough time trying to find the right way to frame. It may make sense to rename, but not sure what I'd change to. I changed up this description a little to try to make it clearer that by default all 6 will be kept.

2024-05-08 20:29 UTC, robertandremitchell commented on containers/vocab-mapper/app/utils.py
> +            clinical_service_dict.pop(type, None)
I've decoupled a bit more in the latest pushes, which has put it more in the layout I think Dan describes. Curious your thoughts; I could definitely see linking these more, particularly because the formatting from list of tuples to nested dict is something we will presumably always do, so I could see that becoming a helper function.

2024-05-08 20:36 UTC, robertandremitchell commented on containers/vocab-mapper/app/utils.py
> +        cursor.execute(sql_query, snomed_id)
makes sense. I redid some of the cleaning here

2024-05-08 21:02 UTC, robertandremitchell commented on containers/vocab-mapper/app/utils.py
> +    :param clinical_services: List of clinical service types to keep
lmk what you think of `filter_clinical_services`, I think this was my best idea so far.

2024-05-08 21:07 UTC, robertandremitchell commented
@DanPaseltiner and @bamader , new version of code ready for review, curious your thoughts. I also merged with main to get this moved over to `trigger-code-reference`

2024-05-08 21:13 UTC, nickclyde approved these changes
Looks great Rob, now that the function concerns are a bit more separated, I think this is much more readable 👍🏻

2024-05-08 21:13 UTC, nickclyde commented on containers/trigger-code-reference/app/utils.py
> +                return [val.strip() for val in value.split(delimiter) if val.strip()]
Gotta love a good list comprehension 🔥

2024-05-09 13:07 UTC, DanPaseltiner approved these changes
Thanks for the refactors here @robertandremitchell. Two minor suggestions and some ramblings about DB connection management below, none of which are blocking from my perspective.

2024-05-09 13:57 UTC, robertandremitchell commented on containers/trigger-code-reference/app/utils.py
> +def sanitize_inputs_to_list(value: Union[list, str, int, float]) -> list:
makes sense. updating

2024-05-09 13:57 UTC, robertandremitchell commented on containers/trigger-code-reference/app/utils.py
> +        return clean_snomed_code
makes sense. updating

2024-05-09 14:01 UTC, robertandremitchell commented on containers/trigger-code-reference/app/utils.py
> +    return clinical_services_list
Good call out. I can play around with this section a bit more this morning. I think having a context manager makes sense and mirrors what I see in other parts of the code.

Yeah, that's a good point re: the opening/closing. I could see moving the sql connection to a separate function that might allow us to run multiple calls.

2024-05-09 15:38 UTC, robertandremitchell commented on containers/trigger-code-reference/app/utils.py
> +    return clinical_services_list
switched to `with`.  reading up one some other options to keep the connection open if needed, but I think to your point it may make more sense to revisit once we know better what this scaling might look like on the `ecr-refiner`.

2024-05-09 17:17 UTC, merged