Linkage Module
CDCgov/phdi pull request #18
Opened 2022-08-12 20:39 UTC by KennethSkylight

This PR moves the linkage module into the new file path. The tests are moved as well

2022-08-15 17:17 UTC, spencer-skylight commented on .vscode/settings.json
> +    "python.formatting.provider": "black"
I think we should delete from source control at least for now (it may be a good idea to explicitly add `/.vscode/settings.json` it to `.gitignore`).  

We could still add recommended vscode settings to the repository in the future, but if/when we do that, we should synchronize all settings documented in `CONTRIBUTING.md`. I'm also not sure what would happen if users wanted to modify this file with their own desired extensions that we don't necessarily want in the repo, so that's something else to figure out.

2022-08-15 19:19 UTC, spencer-skylight requested changes
A few minor suggestions.

2022-08-15 19:19 UTC, spencer-skylight commented on phdi/linkage/README.md
> +This package contains functions useful in the geocoding of raw input data (i.e. strings and dictionaries having no particular formatting standard). The `__init__.py` file defines the abstract `Geocod
This still has content for geospatial, and should be updated.

2022-08-15 19:19 UTC, spencer-skylight commented on phdi/linkage/__init__.py
> +def _get_one_line_address(address: dict) -> str:
IMO this should be moved to `phdi.fhir.utils` and made public. This is the exact same implementation as in `phdi.fhir.geospatial`, and since we are calling it from 2 submodules at this point, and seems like something that could be useful to STLTs as a standalone function, we could make it public (remove the leading _).

@bamader I wanted to get your opinion as well. What do you think?

2022-08-16 21:37 UTC, spencer-skylight commented on .vscode/settings.json
> +    "python.formatting.provider": "black"
I went ahead and made this change.

2022-08-17 12:39 UTC, spencer-skylight commented on phdi/linkage/__init__.py
> +def _get_one_line_address(address: dict) -> str:
After chatting with Brandon - this makes sense to him as well.

2022-08-17 15:22 UTC, KennethSkylight commented on phdi/linkage/__init__.py
> +def _get_one_line_address(address: dict) -> str:
Moved

2022-08-17 16:04 UTC, spencer-skylight approved these changes
LGTM!

2022-08-17 20:50 UTC, merged