Adding TCR to message-refiner DockerFile
CDCgov/phdi pull request #1833
Opened 2024-05-13 20:46 UTC by robertandremitchell

# PULL REQUEST

## Summary
This updates and creates a docker-compose.yml that starts up the message-refiner and trigger-code-reference services. I've carried over a lot of the checks/syntax from `orchestration`; I'm not sure if we will want/need to add additional services, so it's probably a little overkill right now, but I figured it'd be better to overcommit in the event we needed to add additional services down the line.

## Related Issue
Fixes #1822 

## Additional Information
I wasn't sure whether to give these services unique port numbers, or follow the orchestration model of having the base service (message-refiner) be 8080, then increment by 1 for the additional services.

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-05-14 17:59 UTC, DanPaseltiner requested changes
Looks good. I think we just need to clean up how we are using environment variables (comments below). Happy to discuss further if you would like.

2024-05-14 17:59 UTC, DanPaseltiner commented on containers/message-refiner/.env
All of this networking should be handled within the docker compose file. Record linkage and orchestration offer examples of this.

2024-05-14 17:59 UTC, DanPaseltiner commented on containers/message-refiner/Dockerfile
> +ENV TRIGGER_CODE_REFERENCE_URL=$TRIGGER_CODE_REFERENCE_URL
As with the comment above we can set environment variables in the docker compose file. Having values for environment variables should be a requirement to run the service not build an image for it.

2024-05-14 19:14 UTC, robertandremitchell commented on containers/message-refiner/Dockerfile
> +ENV TRIGGER_CODE_REFERENCE_URL=$TRIGGER_CODE_REFERENCE_URL
makes sense, updated!

2024-05-15 02:22 UTC, DanPaseltiner commented on containers/message-refiner/docker-compose.yml
> +      - MESSAGE_REFINER_URL=http://message-refiner-service:8080
Does the message refiner need to know it's own URL?

2024-05-15 02:22 UTC, DanPaseltiner commented on containers/message-refiner/docker-compose.yml
> +      - TRIGGER_CODE_REFERENCE_URL=http://trigger-code-reference-service:8080
I think this can be simplified to `message-refiner-service:8080`. Record linkage is a good example of this, but docker compose makes networking between containers relatively easy.

2024-05-15 12:40 UTC, robertandremitchell commented on containers/message-refiner/docker-compose.yml
> +      - MESSAGE_REFINER_URL=http://message-refiner-service:8080
blah, no, updated!

2024-05-15 12:40 UTC, robertandremitchell commented on containers/message-refiner/docker-compose.yml
> +      - TRIGGER_CODE_REFERENCE_URL=http://trigger-code-reference-service:8080
updated!

2024-05-15 12:43 UTC, robertandremitchell commented on containers/message-refiner/docker-compose.yml
> +      - TRIGGER_CODE_REFERENCE_URL=http://trigger-code-reference-service:8080
blah, nevermind, update didn't take, one sec...

2024-05-15 12:48 UTC, robertandremitchell commented on containers/message-refiner/docker-compose.yml
> +      - TRIGGER_CODE_REFERENCE_URL=http://trigger-code-reference-service:8080
okay, should be good!

2024-05-15 14:48 UTC, DanPaseltiner approved these changes
Send it!

2024-05-15 15:04 UTC, merged