Akintner add get-value-set enpoint
CDCgov/phdi pull request #1853
Opened 2024-05-15 17:00 UTC by akintner

# PULL REQUEST

## Summary
Add an endpoint to return all value sets associated with a provided SNOWMED code

## Related Issue
Fixes #1788

2024-05-15 18:06 UTC, robertandremitchell requested changes
thanks @akintner ! a few minor notes, please let me know if you have any q's!

2024-05-15 19:08 UTC, akintner commented on containers/trigger-code-reference/app/main.py
> +        clean_snowmed_code = get_clean_snomed_code(condition_code)
Oh good callout, didn't see this.

2024-05-15 19:24 UTC, akintner commented on containers/trigger-code-reference/app/main.py
> +        values = get_clinical_services_dict(clinical_services_list)
Since I'm new to Python, I will defer adding a new class to `models.py` for a later pass at this and just add the optional param for now.

2024-05-15 20:02 UTC, robertandremitchell requested changes
mostly good, just need to change up filter_clinical_services a little.

2024-05-15 20:02 UTC, robertandremitchell commented on containers/trigger-code-reference/app/main.py
> +            clinical_services_list, filter_clinical_services=None
we don't need `=None` here, just `filter_clinical_services`. 

We want to add `filter_clinical_services: list = None` on this line, after `condition_code`: https://github.com/CDCgov/phdi/blob/573aceba19a66f0a1bbf07918c96e05a0886ae37/containers/trigger-code-reference/app/main.py#L49.

This will set the filter to none by default, but a person could still provide a list of clinical services to filter out, which would then be picked up on lines 66-67 if needed.

2024-05-15 20:15 UTC, DanPaseltiner commented on containers/trigger-code-reference/app/main.py
> +    return {"value_set": values}
Do we need to nest `values` in another dict or can we simply `return values`?

2024-05-15 20:20 UTC, robertandremitchell commented on containers/trigger-code-reference/app/main.py
> +    return {"value_set": values}
I don't see a reason. I think I'm pro just returning values, as well @akintner .

2024-05-15 20:49 UTC, akintner commented on containers/trigger-code-reference/app/main.py
> +            clinical_services_list, filter_clinical_services=None
Alright, moved it and updated.

2024-05-15 21:08 UTC, robertandremitchell approved these changes
looks good to me! thank you for your work on this 😄

2024-05-16 12:59 UTC, bamader reviewed
Looks good!

2024-05-16 12:59 UTC, bamader commented on containers/trigger-code-reference/app/main.py
> +    else:
nit: `else` isn't needed here because if the `if` triggered, we'd return back to the caller

2024-05-16 13:56 UTC, robertandremitchell commented
@bamader or @DanPaseltiner , do you recognize the error on the message-refiner and trigger-code-reference checks? I'm unable to replicate either locally, but I recall this being a problem in the past, just now how we actually resolved it...

2024-05-16 18:09 UTC, akintner commented
I'm obviously unaware of which integrations fail and at what regularity in this repo or this codebase, but the `trigger-code-reference` one began regularly failing after I removed the `else:` as @bamader requested, FYI.

2024-05-16 18:50 UTC, robertandremitchell commented
> I'm obviously unaware of which integration tests fail and at what regularity in this repo or this codebase, but the `trigger-code-reference` one began regularly failing after I removed the `else:` as @bamader requested, FYI.

weird! if that's all that's killing it, I would probably add back and confirm that the test passes.

2024-05-17 17:09 UTC, akintner commented
For both Nick and I, the docker containers associated with the integration tests were insisting on an install of `python-multipart`, so we added that as a requirement and it got everything passing (locally and here) without a hitch. Nick plans to sync with Dan about this sometime next week to try and figure out where this dependency requirement stems from in the code, which wasn't readily apparent to us when pairing just now.

2024-05-17 17:11 UTC, merged