Adding TCR Refinement to message-refiner
CDCgov/phdi pull request #1864
Opened 2024-05-16 18:56 UTC by robertandremitchell

# PULL REQUEST

## Summary
This would add further refinement to the message-refiner service that would look at the eCR for condition codes provided by the user. These condition codes would be looked up in the TCR service to get the relevant clinical services. XPaths will then be generated for those clinical services and then we will search each section for those relevant clinical service codes.

## Related Issue
Fixes #1823

## Additional Information
We will likely need to create additional xpaths for the vaccineCode to look at Immunization and valueCodeableConcept to look further at Observation. 

I initially thought we would look at each component then determine which xpath we would use. So we could try to do that or generate a whole bunch of xpaths that have these even if they're not Immunization or Observation? Or generate those additional xpaths if their clinical service type is one of the 3 immunization types only?

Still slightly blocked from testing, so will ideally be able to check further how performant it is to throw so many xpaths to check...

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-05-23 21:53 UTC, robertmitchellv commented on containers/message-refiner/app/main.py
> +def add_root_element(header: bytes, elements: list) -> str:
i like breaking this out into its own function

2024-05-23 22:10 UTC, robertmitchellv approved these changes
this looks good 👍🏻  i'll need to think through the `refine` function now that there's an additional parameter that can be used with `sections_to_include` 🤔 may pick you brain on that!

2024-05-24 20:41 UTC, robertandremitchell commented
@DanielPaseltiner , updates made to break up the clinical services code and switch the TCR half to async

2024-05-28 14:30 UTC, DanPaseltiner requested changes
This is really coming a long. A couple things I think we should tweak before merging. Thanks for continuing push this a long @robertandremitchell!

2024-05-28 16:08 UTC, robertandremitchell commented on containers/message-refiner/app/main.py
>              return Response(content=error_message, status_code=422)
updated!

2024-05-28 16:09 UTC, robertandremitchell commented on containers/message-refiner/app/main.py
> +TCR_URL = "http://trigger-code-reference-service:8080"
sorry, missed this one the other day. should be updated now!

2024-05-28 17:46 UTC, bamader approved these changes
Looks pretty sick!

2024-05-28 17:46 UTC, bamader commented on containers/message-refiner/app/main.py
>      return (section_loincs, error_message) if section_loincs else (None, error_message)
Unrelated to the PR, but I think we might be able to get rid of the ternary in this line. Because `section_loincs` is set to `None` on 110 if the section to lookup isn't in our pre-made list, and then there's a `break`, the second the program errors we'll just drop to the `return` statement and the value of `(section_loincs, error_message)` would already be equivalent.

2024-05-28 17:46 UTC, bamader commented on containers/message-refiner/app/main.py
> +    return (clinical_services_list, error_message)
Is the `error_message` we return here ever updated? Unless the `response` object somehow automatically manipulates it I can't see where this will ever be anything but the empty string.

2024-05-28 18:21 UTC, robertandremitchell commented on containers/message-refiner/app/main.py
>      return (section_loincs, error_message) if section_loincs else (None, error_message)
makes sense. I had to rewrite parts of `refine` that influenced this function, so I think it's worth simplifying. lmk what you think of the update!

2024-05-28 18:42 UTC, DanPaseltiner commented on containers/message-refiner/app/main.py
> +    return (clinical_services_list, error_message)
Agreed @bamader

2024-05-28 19:06 UTC, robertandremitchell commented on containers/message-refiner/app/main.py
> +    return (clinical_services_list, error_message)
makes sense. I've refactored this step a little to not require error_message; instead, it returns the whole response, checks the status code, then will tag out to 503 if all responses are not 200. otherwise, it proceeds as usual with creating clinical_service_xpaths. lmk your thoughts!

2024-05-28 19:10 UTC, robertandremitchell commented on containers/message-refiner/app/main.py
> +    return (clinical_services_list, error_message)
makes sense. with some of the other work I did, I think this works a bit more elegantly, but curious your thoughts.

2024-05-28 19:22 UTC, bamader commented on containers/message-refiner/app/main.py
>      return (section_loincs, error_message) if section_loincs else (None, error_message)
Yep, cleaner now!

2024-05-29 13:55 UTC, DanPaseltiner commented on containers/message-refiner/app/config.py
> +    return Settings(_env_file=".env").dict()
Thank for moving this over the env var. Unfortunately, we can't use a ".env" file because when these services get deployed we need to be able to set the environment variables at the container level. I think the record linkage service is a good example of how we typical handle environment variables. For testing purposes these values should be set in the docker-compose file.

2024-05-29 14:12 UTC, DanPaseltiner commented on containers/message-refiner/app/main.py
>      section_loincs = []
I think these lines can be removed.

2024-05-29 14:12 UTC, DanPaseltiner commented on containers/message-refiner/app/main.py
> +    if sections_to_include is None:
We should probably handle `None` or `""`

2024-05-29 14:12 UTC, DanPaseltiner commented on containers/message-refiner/app/main.py
> +    return (section_loincs, error_message)
What about something like this? Since the function should exit whenever the if condition is met we can simply return early, eliminating the need for `break` and `else`. Furthermore, I don't think we need to set `section_loincs` to `None` in the if block. It doesn't hurt, but does it really do anything for us? Our logic in the parent function is to check the value of `error_message` and if there is an error we effectively ignore `section_loincs`.

```suggestion
    section_loincs = []
    sections = sections_to_include.split(",")
    for section in sections:
        if section not in section_LOINCs:
            error_message = f"{section} is invalid. Please provide a valid section."
            return (section_loincs, error_message)
        section_loincs.append(section)

    return (section_loincs, "")
```

2024-05-29 20:22 UTC, robertandremitchell commented on containers/message-refiner/app/config.py
> +    return Settings(_env_file=".env").dict()
updated!

2024-05-29 20:23 UTC, robertandremitchell commented on containers/message-refiner/app/main.py
> +    if sections_to_include is None:
added!

2024-05-29 21:00 UTC, DanPaseltiner approved these changes
🚀 Nice work on this!

2024-05-29 21:55 UTC, merged