Adding Models, samples to ECR Refiner
CDCgov/phdi pull request #1909
Opened 2024-05-30 20:45 UTC by robertandremitchell

# PULL REQUEST

## Summary
What changes are being proposed?

## Related Issue
Fixes #1906 

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-05-31 21:41 UTC, bamader approved these changes
This looks good to me. I agree with your reasoning around the response model in terms of going from formatted string to raw bytes dump, so I think I'd be good to leave this as is. Would be curious to hear from @DanPaseltiner before merging though to see if the vision should be different.

2024-06-03 14:53 UTC, DanPaseltiner requested changes
I think we are overcomplicating things by moving to JSON formatted requests and responses with serialized XML.

2024-06-03 14:53 UTC, DanPaseltiner commented on containers/message-refiner/app/models.py
> +    )
These should continue to be query parameters. I'm not actually sure we should deviate from just putting the XML in the body of the request and this adds burden on the client to transform their data and work with a mix of JSON and XML.

2024-06-03 14:53 UTC, DanPaseltiner commented on containers/message-refiner/app/models.py
> +    refined_message: str = Field(description="Refined XML as a string.")
Again here I think we should just just return an XML response because we are working with XML data. What makes the API easiest for a Rhapsody developer to connect to? It may be that there isn't really a need for request and response models here as long as we can get Pydantic to validate that the they are formatted as XML.

2024-06-03 20:59 UTC, robertandremitchell commented on containers/message-refiner/app/models.py
> +    refined_message: str = Field(description="Refined XML as a string.")
makes sense. this update switches back to using just XML as the response and more simplified error messaging.

2024-06-03 21:01 UTC, robertandremitchell commented on containers/message-refiner/app/models.py
> +    )
I think that makes sense. The main issue I'm running into, however, is trying to use an kind of Model with raw XML. The only working version uses `Response`, but FastAPI does not permit annotation of `Response` for...reasons, so I'm unable to add in the examples. I've tried a few workarounds and changes, but I'm a bit stumped as to how essentially allow the raw XML string but also in /redoc produce documentation.

Right now, the optional params are documented, we just don't have a way to display example API calls or show an example XML body

2024-06-04 13:07 UTC, DanPaseltiner commented on containers/message-refiner/app/models.py
> +    )
Let's review the existing docs during our 1:1 I don't know that we need to have a model per se as long as we can clearly state the input should be an eICR.

2024-06-04 18:53 UTC, DanPaseltiner approved these changes
🚀 Nice work!

2024-06-04 19:28 UTC, merged