Preserve trigger code elements within sections
CDCgov/phdi pull request #2005
Opened 2024-06-20 23:01 UTC by robertmitchellv

# PULL REQUEST

> this is still a WIP

## Summary
There are potentially four ways that an eICR can flag an element within a section as containing the data that triggered the message to a STLT. The elements are all nested in slightly different ways based on the main section that they belong to. In some cases it is nested 3 levels down from the `<entry>` after a `<text>` element within a section and in other cases it is exactly _at_ the `<entry>` level already.

To handle this, we're:
- extending the `section_loincs.json` file to include metadata about the `templateId`s for the trigger code templates.
- changing the way this object is unpacked in `refine.py` so that we can also easily grab the OIDs that are used as `root` in their respective `templateId`s.
- _more to follow_

## Related Issue
Fixes #1883 
- #1883 

[//]: # (PR title: Remember to name your PR descriptively!)

2024-07-26 14:28 UTC, nickbristow approved these changes
This looks good to me, but i haven't worked on refiner before

2024-07-26 15:07 UTC, m-goggins approved these changes
Looks good to me! Thanks for the clear description of the 4 cases we might encounter

2024-07-29 19:21 UTC, robertandremitchell requested changes
hi Robert, great overview and definitely a lot to review and unpack. Overall, looks great, just had a few minor questions and notes.

2024-07-29 19:21 UTC, robertandremitchell commented on containers/message-refiner/app/refine.py
> +def _get_entries_for_section(
does this get used outside of tests?

2024-07-29 19:21 UTC, robertandremitchell commented on containers/message-refiner/app/refine.py
> +    if callable(section):
I know with some of the message-parser code, we ended up rueing the args/kwargs for future visibility. Especially because of how complex this is, I wonder if we want to address now or have a tech debt ticket for how we might resolve in the future.

2024-07-29 19:21 UTC, robertandremitchell commented on containers/message-refiner/app/refine.py
> +    :param
it looks like this didn't get complete :param: and :return:?

2024-07-29 19:21 UTC, robertandremitchell commented on containers/message-refiner/app/refine.py
> +def _analyze_structure(path: List[etree.Element]) -> List[Dict[str, object]]:
also i didn't see where this was used outside of tests

2024-07-29 21:27 UTC, robertmitchellv commented on containers/message-refiner/app/refine.py
> +def _analyze_structure(path: List[etree.Element]) -> List[Dict[str, object]]:
ah, right, good catch! this was more of a helper function i used when trying to figure out how to get this to work and `find_path_to_entry` is the final version that is used. i'll remove this

2024-07-29 21:31 UTC, robertmitchellv commented on containers/message-refiner/app/refine.py
> +def _get_entries_for_section(
yeah this was initially used but there was just too much iteration and looping over lists and it was simpler to search a combination of all XPaths with a section rather than a list of `<entry>`s that are individually searched. `_get_observations` was using it until i figured out how to bypass this function and simplify. i can take it out

2024-07-29 21:32 UTC, robertmitchellv commented on containers/message-refiner/app/refine.py
> +    :param
good catch! thanks!

2024-07-29 21:45 UTC, robertmitchellv commented on containers/message-refiner/app/refine.py
> +    if callable(section):
yeah, that's a fair point. since we're pretty sure that we'll be calling/using a function in a really specific way i suppose we don't need to have all of the functions building off of the `_get_sections` callable. these were really useful early on trying to figure out how to get things to work.

@DanielPaseltiner what are your thoughts on this one?

2024-07-30 12:25 UTC, bamader approved these changes
Phew, this was an absolute bear to get through but looks amazing! Thanks so much for all your hard work (and probably lost sleep 😴 ) on this, Robert. The only suggestion I'd have is agreement with Rob around paring down some of the kwargs/callables related to `_get_sections()`. I think the assessment that so many functions get used in such specific ways is the right one, so I'd personally opt for reducing kwarg reliance and just making the functions more direct. However, I'm also not the one who was absolutely guts deep in these trenches, so if you think there's a legitimate reason for keeping that modularity around I'm all for it. I also think we could address that in a future tech debt ticket if we just want to get this closed. Either way, amazing work!

2024-07-30 21:52 UTC, robertmitchellv commented on containers/message-refiner/app/refine.py
> +    if callable(section):
with @bamader also agreeing i think it makes sense to make those changes; it was actually a lot simpler because i was already specifically calling them with section parameters inside `refine`. this was really a hold over from trying to figure out how to get the desired outcome and working through it interactively. thanks for the helpful comments!

2024-07-30 21:55 UTC, robertmitchellv commented on containers/message-refiner/app/refine.py
> +    if callable(section):
@robertandremitchell do you want to take another look and make sure your changes were folded in?

2024-07-31 13:33 UTC, robertandremitchell approved these changes

2024-07-31 16:08 UTC, merged