Add Interpretation to Lab Observation Value
CDCgov/phdi pull request #2020
Opened 2024-06-24 16:52 UTC by JNygaard-Skylight

# PULL REQUEST

## Summary
Appends lab observation interpretation to  value. 

## Related Issue
Fixes #1973 

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-07-03 19:52 UTC, nickbristow approved these changes

2024-07-03 19:52 UTC, nickbristow commented on containers/ecr-viewer/src/middleware.ts
> +  console.log("test: " + isTest);
probably don't need

2024-07-03 20:08 UTC, BobanL commented on containers/ecr-viewer/docker-compose.yml
> -      - ./src/app:/app
I think this is required for Dockerfile dev. Locally when running this docker compoose I get an error
![image](https://github.com/CDCgov/phdi/assets/10108172/dab18008-7f6c-4829-b3b4-2665e8364076)

2024-07-03 20:08 UTC, BobanL requested changes
I think normal docker-compose is broken now.

2024-07-08 16:48 UTC, JNygaard-Skylight commented on containers/ecr-viewer/docker-compose.yml
> -      - ./src/app:/app
I think I fixed this, can you check this again?

2024-07-08 17:19 UTC, BobanL approved these changes
Looks good to me! 
Just as a note - I do get an error, but it seems like it is an issue with main too. It has to do with how the shared services are being bundled, which is being worked on now.

![image](https://github.com/CDCgov/phdi/assets/10108172/dbd669a4-00c9-4941-b927-14273c4314a9)

2024-07-08 17:29 UTC, merged