Boban/1999 medication refactor
CDCgov/phdi pull request #2038
Opened 2024-06-27 20:15 UTC by BobanL

# PULL REQUEST

## Summary
What changes are being proposed?

## Related Issue
Fixes #

## Additional Information
Anything else the review team should know?

## Demo
New: http://localhost:3000/view-data?id=1dd10047-2207-4eac-a993-0f706c88be5d#treatment-details
<img width="777" alt="image" src="https://github.com/CDCgov/phdi/assets/10108172/6770b408-0826-406e-9e52-211804212bf8">

New: http://localhost:3000/view-data?id=6100896d-b520-497c-b2fe-1c111c679274#treatment-details
<img width="777" alt="image" src="https://github.com/CDCgov/phdi/assets/10108172/dc835de8-a181-4176-bd86-f6d17c649741">

New: http://localhost:3000/view-data?id=cf9e1db8-fcc5-4cbc-96cd-043d3fd65bac#treatment-details
<img width="777" alt="image" src="https://github.com/CDCgov/phdi/assets/10108172/672117fe-e3b1-48ab-8c22-e0dc96258037">

New: http://localhost:3000/view-data?id=df33f075-83a1-4d28-ba63-05bcc3339c21#treatment-details
<img width="777" alt="image" src="https://github.com/CDCgov/phdi/assets/10108172/8d2b1d4e-ed65-4d40-a142-2a9f0ac9bcea">
<img width="777" alt="image" src="https://github.com/CDCgov/phdi/assets/10108172/934bb528-2c08-4d79-a916-9e4332617eb8">

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-07-02 20:53 UTC, angelathe commented on containers/ecr-viewer/src/app/view-data/components/AdministeredMedication.tsx
> +  if (administeredMedicationReferences?.length > 0) {
Tiny nit: Thoughts on checking `if {administeredMedicationReferences?.length == 0} (return undefined)` first? Might make it slightly more readable by avoiding wrapping the rest of the code inside the current if statement.

2024-07-02 20:53 UTC, angelathe commented on containers/ecr-viewer/src/app/view-data/components/common.tsx
> +        <AdministeredMedication fhirBundle={fhirBundle} mappings={mappings} />
I was checking this [eCR](http://localhost:3000/view-data?id=1.2.840.114350.1.13.478.3.7.8.688883.252732#treatment-details) that has no Admin Medications, and from logs, it seems that the <AdministeredMedications> component isn't returning undefined? Is this something you can cross-reference on your end? I think this is what's causing the extra divider line in the eCR (under Treatment Details)

2024-07-02 20:53 UTC, angelathe commented on containers/ecr-viewer/src/app/view-data/components/AdministeredMedication.tsx
> +      </Table>
I think this is a case where we could use `EvaluateTable`? This could be pretty similar to how `returnImmunizations` uses the component

2024-07-03 19:44 UTC, JNygaard-Skylight commented on containers/ecr-viewer/package.json
> +    "typescript": "^5.5.2"
Why was this needed?

2024-07-03 19:55 UTC, BobanL commented on containers/ecr-viewer/package.json
> +    "typescript": "^5.5.2"
Typescript version 5.5 has a introduced a change to help improve type inference. This is just making sure we all have that latest version. 

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-5.html#inferred-type-predicates

2024-07-03 20:38 UTC, BobanL commented on containers/ecr-viewer/src/app/view-data/components/common.tsx
> +        <AdministeredMedication fhirBundle={fhirBundle} mappings={mappings} />
That is right, returning undefined/null from a react component like this does not evaluate to null. The only way to do that is with conditional rendering like the new version has.

2024-07-03 20:51 UTC, nickbristow requested changes

2024-07-03 20:51 UTC, nickbristow commented on containers/ecr-viewer/src/app/view-data/components/common.tsx
> +  console.log(administeredMedication);
here

2024-07-03 20:51 UTC, nickbristow commented on containers/ecr-viewer/src/app/view-data/components/common.tsx
> +        if (medication?.code?.coding?.[0]?.display) {
Can we take this nested if out? I don't think it needs to be in the if block. Its just harder to read like this

2024-07-10 14:12 UTC, nickbristow approved these changes

2024-07-10 14:27 UTC, merged