add <br> to string concat
CDCgov/phdi pull request #2049
Opened 2024-07-01 22:20 UTC by nickbristow

# PULL REQUEST

## Summary
Instead of concating strings with " " use "<br/>" instead

## Related Issue
Fixes #1974

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-07-02 19:05 UTC, BobanL requested changes
Hide comment is showing up in every lab result, but everything else looks ok!

2024-07-02 19:35 UTC, nickbristow commented on containers/orchestration/docker-compose.yml
> +    platform: linux/amd64
i had trouble loading it when i didn't have this set

2024-07-02 19:48 UTC, nickbristow commented on containers/ecr-viewer/src/app/view-data/components/EvaluateTable.tsx
> +    if (rowCellData && column.hiddenBaseText) {
i think i get what your saying? hows this

2024-07-03 14:23 UTC, BobanL approved these changes
👏

2024-07-03 14:54 UTC, merged