Add HAPI Server with Synthetic data for testing
CDCgov/phdi pull request #2089
Opened 2024-07-09 18:05 UTC by m-goggins

# PULL REQUEST

## Summary
This PR adds functionality to spin up a HAPI FHIR server and load it with synthetic data for testing. I add this functionality in `docker-compose-dev.yaml` because I think we only want to spin up this FHIR server for testing and not when we build the actual service for production. I'm happy to change this set up back to all in one docker compose file if folks feel differently because users of the service would connect to their own server/QHIN, not the HAPI server. 

To run spin up the dev environment, run `docker compose -f .\docker-compose-dev.yaml up`. It takes a second for the server to spin up and another two minutes for the data to populate in the server. You can check that everything works by going to `localhost:8080/fhir/Patient` in your browser.

## Related Issue
Fixes #1583 

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-07-09 21:20 UTC, robertandremitchell reviewed
having some issues with the HAPI server initializing
```bash
tefca-fhir-server-1  |  ✓ Ready in 4.6s
tefca-data-loader-1  | Server is not healthy after 120 seconds.
tefca-data-loader-1 exited with code 1
```

I am exploring the hapi stuff but not having much luck. I'll review again tomorrow / can give more context if it would be helpful.

2024-07-10 21:12 UTC, robertandremitchell reviewed
I _finally_ got a version to work! However, I needed to increase the memory size of Java. 

```yaml
  tefca-fhir-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: "hapiproject/hapi:latest"
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx2g -Xms512m
    command:
      [
        "sh",
        "-c",
        "ulimit -c unlimited && java $JAVA_OPTS -jar /app/main.war"
      ]
    depends_on:
      - tefca-viewer
```

however, even this is proving really finnicky to re-spin up, I really am at a loss for why it's proving so difficult to spin up. So I think you could not add this, especially if I'm the only one who's having this issue, but it's possible we need to add code to explicitly install and set a java version to the Dockerfile maybe? that was the only other recommendation I came across beyond just increasing the memory

2024-07-11 19:02 UTC, alismx commented
> I _finally_ got a version to work! However, I needed to increase the memory size of Java.
> 
> ```yaml
>   tefca-fhir-server:
>     build:
>       context: .
>       dockerfile: Dockerfile.dev
>     image: "hapiproject/hapi:latest"
>     ports:
>       - "8080:8080"
>     environment:
>       - JAVA_OPTS=-Xmx2g -Xms512m
>     command:
>       [
>         "sh",
>         "-c",
>         "ulimit -c unlimited && java $JAVA_OPTS -jar /app/main.war"
>       ]
>     depends_on:
>       - tefca-viewer
> ```
> 
> however, even this is proving really finnicky to re-spin up, I really am at a loss for why it's proving so difficult to spin up. So I think you could not add this, especially if I'm the only one who's having this issue, but it's possible we need to add code to explicitly install and set a java version to the Dockerfile maybe? that was the only other recommendation I came across beyond just increasing the memory

To solve this, I'd try increasing the total amount of memory that docker can consume.

2024-07-11 19:21 UTC, robertmitchellv approved these changes
forgot to approve yesterday after testing locally that it works; great job!

2024-07-11 20:23 UTC, robertandremitchell approved these changes
thanks for the suggestion @alismx !

This seems to have done the trick, though, I still had to pull the image before getting it to work. Not sure if we should explicitly add a `FROM` to the dockerfile.dev to pull the image. If it already worked for everyone else, it's probably fine.

2024-07-11 20:29 UTC, alismx requested changes

2024-07-11 20:29 UTC, alismx commented on containers/tefca-viewer/docker-compose-dev.yaml
> +      dockerfile: Dockerfile.dev
I think this file is being used for the `tefca-data-loader` service, not for this one, I think this build context should be removed. I think that'll solve @robertandremitchell issue.

2024-07-11 20:51 UTC, m-goggins commented on containers/tefca-viewer/docker-compose-dev.yaml
> +      dockerfile: Dockerfile.dev
Good catch, thanks! I just fixed. @robertandremitchell will you let me know if you're still having the same issue?

2024-07-11 21:16 UTC, robertandremitchell commented on containers/tefca-viewer/docker-compose-dev.yaml
> +      dockerfile: Dockerfile.dev
thanks! That did the trick for me 😁 
Sorry for the journey on this one 😅

2024-07-11 21:36 UTC, m-goggins commented on containers/tefca-viewer/docker-compose-dev.yaml
> +      dockerfile: Dockerfile.dev
Yay! Thank you both @alismx @robertandremitchell!

2024-07-11 21:52 UTC, alismx approved these changes

2024-07-11 22:06 UTC, merged