Cloud module storage
CDCgov/phdi pull request #21
Opened 2022-08-17 12:27 UTC by spencer-skylight

Create the CloudContainerConnection interface and related Azure implementation.

2022-08-17 15:14 UTC, bryan-skylight commented on phdi/cloud/azure.py
> +    This class implements the PHDI credential manager interface for connecting to Azure.
The use of "interface" in this context is confusing. Interfaces serve as the blueprint for classes, which classes then implement. In this scenario, BaseCredentialManager is the interface, and AzureCredentialManager is the implementation. I'd recommend we remove the word "interface" from the doctstring. I'm also not sure that we need to call it "the PHDI credential manager". I don't know why, but it gives me a weird reaction when I read it. Like hearing people refer to it as The Ohio State University.

2022-08-17 15:19 UTC, bryan-skylight commented on phdi/cloud/core.py
> +class CloudContainerConnection(ABC):
We need to come up with a common naming convention for implementing interfaces in our code base. Currently, we have "BaseCredentialManager" and this interface with no prefix. 

Python's PEP8 doesn't have recommendations on this, but in general interfaces are named `I<Name>`. I'd recommend we either go that route, or we stick with `Base<Name>`. Either way, we should do something to indicate that it's an interface.

2022-08-17 15:22 UTC, bryan-skylight commented on phdi/cloud/core.py
> +        :return: The `stream` parameter, if supplied. Otherwise a new stream object
I thought the consensus on docstrings was that we no longer included the `return` field?

2022-08-17 15:24 UTC, bryan-skylight commented on phdi/cloud/core.py
> +        :param container_name: Storage container name.
This parameter description is not very helpful in my opinion. Perhaps we could change it to something like "The name of the container where the object should be stored"?

2022-08-17 15:26 UTC, bryan-skylight commented on phdi/cloud/core.py
> +        :param filename: Location of file within storage container.
Similarly, this description could possibly be something like "The filename to use for the object being uploaded". As it's currently written, it almost sounds as if the object should already exist in the storage container.

2022-08-17 15:30 UTC, bryan-skylight commented on phdi/cloud/core.py
> +        :param message_json: The content of a message a json-formatted dict.
This description is missing a word I think. "The content of a message _as_ a json-formatted dict". Although, I'd also point out that JSON-formatted dict is redundant and we might be better off saying "The content of a message in JSON format".

In addition, I believe our human-centered design principles state that the data should be the first parameter in a function, meaning `message_json` and `message` should come before `container_name` and `filename`.

2022-08-17 15:30 UTC, bryan-skylight commented on phdi/cloud/azure.py
> +    This class implements the PHDI credential manager interface for connecting to Azure.
The use of "interface" in this context is confusing. Interfaces serve as the blueprint for classes, which classes then implement. In this scenario, BaseCredentialManager is the interface, and AzureCredentialManager is the implementation. I'd recommend we remove the word "interface" from the doctstring. I'm also not sure that we need to call it "the PHDI credential manager". I don't know why, but it gives me a weird reaction when I read it. Like hearing people refer to it as The Ohio State University.

2022-08-17 15:58 UTC, bamader commented on phdi/cloud/azure.py
> +    This class implements the PHDI credential manager interface for connecting to Azure.
What about something simple like "this class defines a credential manager for connecting to Azure"? In Spencer's defense, I think the sentence construction he has written is logical if both "the" and "interface" remain in the syntax. The implication is that PHDI will provide one credential manager for connecting to Azure, and this class is that credential manager. The other alternative is to replace "the" with "a", since you can't drop the article entirely without it being syntactically incorrect, and that one strikes me as equally valid (it just doesn't have the implication of single provision that using "the" does).

2022-08-17 16:01 UTC, bamader commented on phdi/cloud/core.py
> +class CloudContainerConnection(ABC):
I think technically it's not even an interface in the formal sense, since it can define a constructor and its own instance variables / properties. I would actually really push back against prefixing these with an I as I think it impairs readability and provides no additional value since ABC is used in the same line as every name definition. I personally would also not opt for using a `Base<Name>` convention either, since for things like `FhirGeocodeClient` that gets clunky and again I think the ABC in the definition is doing that work for us. But, if I were forced to choose between these two, I would opt for Base over I.

2022-08-17 16:05 UTC, bamader commented on phdi/cloud/core.py
> +        :return: The `stream` parameter, if supplied. Otherwise a new stream object
The SDK team agreed unanimously before we started taxonomy porting that we wanted to add it back for the new ports. We don't have any of the types specified, as Sphinx can auto-parse those, but we felt it was important from a design perspective to add some specific details around returned values, which could be clarifying to a user. Since it doesn't break up the code flow at all we felt it was a non-harmful add that conferred some additional value for users.

2022-08-17 16:10 UTC, bamader reviewed
Most of the code looks good to me aside from the parameter things Bryan pointed out. Once we get those cleaned up I'm good to approve, but let's also discuss any conventions we want around AbstractBaseClasses

2022-08-17 16:10 UTC, bamader commented on phdi/cloud/azure.py
> +        https://docs.microsoft.com/en-us/azure/developer/python/sdk/authentication-overview#sequence-of-authentication-methods-when-using-defaultazurecredential
This might need a `#noqa` to avoid flake getting angry

2022-08-17 18:37 UTC, spencer-skylight commented on phdi/cloud/azure.py
> +    This class implements the PHDI credential manager interface for connecting to Azure.
I went with Brandon's suggestion here on the simple comment.

2022-08-17 18:38 UTC, spencer-skylight commented on phdi/cloud/core.py
> +class CloudContainerConnection(ABC):
Prefixed with `Base`.

2022-08-17 18:47 UTC, spencer-skylight commented on phdi/cloud/core.py
> +        :return: The `stream` parameter, if supplied. Otherwise a new stream object
Per Slack conversation, removed `return` comments from this PR.
Ticket added to circle back on previously merged code: https://app.clickup.com/t/3bukhp7

2022-08-17 18:51 UTC, spencer-skylight commented on phdi/cloud/core.py
> +        :param container_name: Storage container name.
Updated each container_name comment.

2022-08-17 18:59 UTC, spencer-skylight commented on phdi/cloud/core.py
> +        :param message_json: The content of a message a json-formatted dict.
Comment updated as suggested.

As currently defined, the `message_json` and `message` parameters are optional, and can't be listed before required parameters. This could be refactored in a few different ways to make this more in line with HCD principles. I've got a few opinions on this, but thinking this might be a task to circle back on.  Is it OK to create a separate ticket for this?

2022-08-17 19:00 UTC, spencer-skylight commented on phdi/cloud/azure.py
> +        https://docs.microsoft.com/en-us/azure/developer/python/sdk/authentication-overview#sequence-of-authentication-methods-when-using-defaultazurecredential
Flake seems to be happy.  I think it is more lenient about URLs.

2022-08-17 21:46 UTC, bamader approved these changes
LGTM. I left one question around converting those `logging` statements into raised exceptions--they occur in three back to back places in one file, and the lift seemed small enough to merit just doing now. However, if you'd rather keep this strictly as a port, I won't block, so giving approval in case you decide to merge later or make the change and I've gone offline.

2022-08-17 21:46 UTC, bamader commented on phdi/cloud/azure.py
> +        logging.warning(f"Attempted to store preexisting resource: {response_filename}")
Maybe it's a nit or beyond PR scope, but how would you feel about just changing these into raised Exceptions as part of this PR work? I know it's technically just a port but I've been doing that in mine and it honestly seems small enough to merit just doing here. If you'd rather ticket that later that's okay with me though.

2022-08-17 22:03 UTC, spencer-skylight commented on phdi/cloud/azure.py
> +        logging.warning(f"Attempted to store preexisting resource: {response_filename}")
In some cases it's not as straightforward how we should be reacting in certain error scenarios, but this seems relatively cut and dry that we can allow the caller to handle. I went ahead and removed the exception handling here.

2022-08-18 12:28 UTC, bryan-skylight commented on phdi/cloud/core.py
> +        :param message_json: The content of a message a json-formatted dict.
Yup, you're right, I completely spaced on the optional vs required parameter positioning. Agreed that this should be a separate ticket and followed-up on.

2022-08-18 12:37 UTC, bryan-skylight requested changes
Overall, this looks great. I just have a couple of blocking things, one of which is a question and the other is a requested change.

2022-08-18 12:37 UTC, bryan-skylight commented on phdi/cloud/azure.py
> +        Downloads a blob from storage. The `stream` parameter, if supplied.
The description here doesn't make sense after moving the return description to here. Can we tweak this to read a little better?

2022-08-18 12:37 UTC, bryan-skylight commented on phdi/cloud/azure.py
> +    message: str,
`message` should be the first parameter.

2022-08-18 13:01 UTC, spencer-skylight commented on phdi/cloud/core.py
> +        :param message_json: The content of a message a json-formatted dict.
Created ticket. https://app.clickup.com/t/3c06bt8

2022-08-18 13:16 UTC, spencer-skylight commented on phdi/cloud/azure.py
> +    message: str,
Updated.

2022-08-18 13:17 UTC, spencer-skylight commented on phdi/cloud/azure.py
> +        return stream
There are a few cases I wanted to support:
* Binary type documents (e.g. images, PDF)
* Writing to file stream (avoiding the requirement to keep downloaded content in memory)
* Avoids us needing to handle character encoding.  In other places, right now we assume UTF-8, but ISO 8859-1 and Windows-1252 are also common. 

If you don't think these functions fit in to our use cases (after all, we only support uploading as UTF-8 text currently), I can change to return content converted to a string.

2022-08-18 13:26 UTC, spencer-skylight commented on phdi/cloud/azure.py
> +        Downloads a blob from storage. The `stream` parameter, if supplied.
Updated.

2022-08-23 19:02 UTC, bryan-skylight requested changes
For the most part, this looks really good. I have a question about the inclusion of `store_message_and_response` that I'd like to hash out before merging, but otherwise this looks like it's good to go.

2022-08-24 11:39 UTC, spencer-skylight commented on phdi/cloud/azure.py
> +def store_message_and_response(
TLDR - I agree, removing.

I agree it's more implementation-specific and not a building block per se. I see it as a utility function and a suggestion of how a STLT might store a response error in conjunction with ingested message content. It is still the best option I can think of in the absence of another PII-safe logging or error management framework. On the other hand, it's clunky and has significant limitations in terms of error reporting and management. It might be better to encourage STLTs to brainstorm and implement something more robust. If they do end up implementing a similar approach, the function is so simple, they wouldn't need to spend much time recreating it.

2022-08-24 11:39 UTC, spencer-skylight commented on phdi/cloud/azure.py
> +        print(self.storage_account_url)
Just left behind from testing. Thanks for catching this!

2022-08-24 11:40 UTC, spencer-skylight commented on phdi/cloud/azure.py
> +        Obtain an access token from the Azure identity provider.  The access token,
Good catch - updated.

2022-08-24 11:50 UTC, spencer-skylight commented on phdi/cloud/azure.py
> +        return stream
> I'm not sure how this approach helps us avoid keeping downloaded content in memory.

I converted the StringIO stream test case to a file-based test case `test_download_object_pass_file` to illustrate this.  This should cause the downloader to send the content directly to the file stream as it's being downloaded.

> I would say that this is not accurate. It avoids us needing to handle character encoding immediately, but eventually we'll need to convert those bytes into an object in order to interact with it, at which point we'll need to worry about the encoding.

I should have clarified this approach makes it possible for the caller to simply and efficiently handle encoding. I added a test case `test_download_object_pass_cp1251encoded` to prove this functionality works.  The content is downloaded as an encoding-agnostic byte stream, and a TextIOWrapper wraps that byte stream and interprets the file characters with the supplied encoding property. It also tests that attempting to read the same content as utf-8 does not work.

2022-08-24 17:51 UTC, spencer-skylight commented on phdi/cloud/azure.py
> +        return stream
As discussed, we now return a string from `download_object`. I also added support for using a specified encoding.

2022-08-24 18:35 UTC, bryan-skylight approved these changes
![flourish of approval](https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Krul.svg/220px-Krul.svg.png)

2022-08-24 18:35 UTC, bryan-skylight commented on phdi/cloud/azure.py
> +        :param encoding: Encoding applied downloaded content.
typo: "Encoding applied downloaded content." -> "Encoding applied to the downloaded content."

nit: Some parameter descriptions end in bullets, but some don't. I'm indifferent to which one we use, but we should be consistent.

2022-08-24 19:43 UTC, spencer-skylight commented on phdi/cloud/azure.py
> +        :param encoding: Encoding applied downloaded content.
Updated.  I think periods should be used to end a sentence, but not a sentence fragment. I created a ticket to decide on this and update our documentation.  https://app.clickup.com/t/3cq92a1

2022-08-24 19:44 UTC, merged