[DRAFT] Modify eCR Library Table Formatting Part II
CDCgov/phdi pull request #2290
Opened 2024-07-31 17:17 UTC by angelathe

# PULL REQUEST
Co-authored w/ @BobanL and @joshnygaard 

## Summary
**Modifies eCR Library table formatting:**
- Adds drop shadow below table header & below table (above pagination) -- (Y offset: -4px, Blur: 4px, Color: 000000 15% opacity)
- Make the size of the pagination banner at the bottom match the Figma designs
- Alternating grey and white rows, starting with white
- Table spans the whole browser width and height (not including the top header and bottom pagination banner).
- Table is responsive to resizing when the browser is resized
- Set table height with scrolling on the inside of the table (not the whole page)
    - Sticky DIBBs header & table header
- Add min widths for each column such that the column header stays on one line when making the table narrower. When the user makes the browser narrower than the min width, the table should not get any narrower (they would scroll right and left on the page to see the full page/table).

## Related Issue
Fixes #2244

## Checklist
- [ ] See original ticket for testing scenarios

[//]: # (PR title: Remember to name your PR descriptively!)

2024-07-31 20:07 UTC, angelathe commented
@sarahtress Let me know if you want me to attach screenshots or a loom for design review!

2024-08-01 14:17 UTC, sarahtress commented
> @sarahtress Let me know if you want me to attach screenshots or a loom for design review!

screen recording or pairing live works for me - whatever is easiest for you!

2024-08-01 14:45 UTC, BobanL requested changes
I tested the app and it looks great! Accessibility passed and noticed no problems with zooming or anything like that. When I went through turning off some css on and offI noticed some CSS that might not need to be there? You might have a different experience or know more why those are needed, but left some suggestions there. 

Then just generally speaking, I know we have a conversation later today at 4 est where we are going to talk about css with the whole team. I left some comments with some bigger changes, that we should hold off until that meeting.

Generally, I think I just prefer using the [built in utility classes](https://designsystem.digital.gov/utilities/) wherever possible.

Pros: 
* Easier to read/understand what css is being applied in JSX files
* Snapshots become more valuable
* Knowing for sure making a change to one class won't break something else that is also using it
* Actual reuse of classes

Cons:
* Super wordy
  * This `className="ecr-library-viewer-container"` becomes `className="display-flex flex-column maxh-viewport overflow-hidden"`
* USWDS kind of lacks a bunch of steps that [something like tailwind](https://nerdcave.com/tailwind-cheat-sheet)** has. If we look at [min width](https://designsystem.digital.gov/utilities/height-and-width/#minw), it steps by 1/2 a rem at each step until 5 rem and then has one more at 7.5 rem. If we need to use another value we would have to create it.

Another possible approach would be to create multiple `.scss` files that would relate to each specific `.tsx` file and we could import it specifically in that file. (That would def be out of scope for this ticket though)

** Tailwind uses a ratio of 1/4 rem and USWDS uses 1/2 rem. So Margin top of 8 px would be `m-2`,`margin-1` respectively. I know in our code we use things like `margin-1` in a bunch of places so we would likely have to replace all of those with the tailwind equivalent.

2024-08-01 14:45 UTC, BobanL commented on containers/ecr-viewer/src/styles/custom-styles.scss
>    }
Similar to above, I would suggest doing this in the JS is easier for me to understand. 
```css
.minw-20 {
  min-width: 10rem;
}

.minw-1605 {
  min-width: 8.25rem;
}

.minw-1705 {
  min-width: 8.75rem;
}

.minw-2305 {
  min-width: 11.75rem;
}

.minw-23 {
  min-width: 11.5rem;
}
```
```jsx
  const header = [
    { value: "Patient", className: "minw-20" },
    { value: "Received Date", className: "minw-1605" },
    { value: "Encounter Date", className: "minw-1705" },
    { value: "Reportable Condition", className: "minw-2305" },
    { value: "RCKMS Rule Summary", className: "minw-23" },
  ];
  \\ other stuff
    {header.map((column) => (
    <th
      key={`${column.value}`}
      scope="col"
      className={column.className}
    >
      {column.value}
    </th>
  ))}
```

2024-08-01 14:45 UTC, BobanL commented on containers/ecr-viewer/src/styles/custom-styles.scss
> +  z-index: 999;
Maybe we don't need the z-index?

2024-08-01 14:45 UTC, BobanL commented on containers/ecr-viewer/src/styles/custom-styles.scss
> +  background-color: white;
I don't know if we need this either?

2024-08-01 14:45 UTC, BobanL commented on containers/ecr-viewer/src/styles/custom-styles.scss
>    display: flex;
Tested removing `display: flex`, `align-items: center`, `justify-content: center` and wasn't able to notice any difference.

2024-08-01 14:45 UTC, BobanL commented on containers/ecr-viewer/src/styles/custom-styles.scss
> +  bottom: 0px;
These two might be able to be removed?

2024-08-01 14:55 UTC, angelathe commented on containers/ecr-viewer/src/styles/custom-styles.scss
> +  border-collapse: separate;
This was necessary for keeping the table header bottom border sticky, otherwise it disappers when you scroll

2024-08-01 15:16 UTC, angelathe commented on containers/ecr-viewer/src/styles/custom-styles.scss
>    }
@BobanL Was there a numbering system to the classnames above or was that random? I couldn't match these with the utilities in USWDS

2024-08-01 15:16 UTC, angelathe commented
@BobanL Ah sorry!! I tested these all individually at one point and they were necessary at the time, but recent changes made these unecessary. Fixing now and thanks for finding!

2024-08-01 15:53 UTC, angelathe commented on containers/ecr-viewer/src/styles/custom-styles.scss
>    }
FYI, I ended up naming each class by pixel size that's equiv. to the min-width rem

2024-08-01 17:18 UTC, BobanL commented on containers/ecr-viewer/src/styles/custom-styles.scss
>    }
Sorry for the late reply, but the values provided were not random random, this just continued to follow the USWDS standards of 1 = 1/2 rem; I think we should probably stick with that naming scheme than moving to pixels.

2024-08-01 19:15 UTC, angelathe commented on containers/ecr-viewer/src/styles/custom-styles.scss
>    }
Got it! Changed it back

2024-08-02 18:27 UTC, angelathe commented
@BobanL I applied as many USWDS utility classes as I could, but kept running into some problems: 
1) I couldn't find utility classes for a few things (i.e., [font size w/o specifying family](https://designsystem.digital.gov/utilities/font-size-and-family/)? [border collapse=separate](https://designsystem.digital.gov/utilities/border/#utilities-section)?), 
2) Using the utility classes would be ineffective bc they would get overwritten by `usa-<>` classes, and 
3) I would've had to apply the classes to each item (i.e., adding classes to each `<td>` in a `<tr>`

I pushed my latest code, lmk if you have thoughts

2024-08-02 18:41 UTC, BobanL approved these changes
One small nit, but otherwise looks great. Thank you for your hard work on this!

2024-08-02 18:41 UTC, BobanL commented on containers/ecr-viewer/src/styles/custom-styles.scss
>    }
This looks like it's in the `table-ecr-library` class. Can we move it to the top level?

2024-08-02 19:03 UTC, merged