Add backend pagination
CDCgov/phdi pull request #2389
Opened 2024-08-14 22:02 UTC by lina-roth

# PULL REQUEST

## Summary
- Add date_created to fhir_metadata
- Update listEcrDataService to only pull from fhir_metadata (remove code refrencing s3 or postgres) 
- Update tests 
- Update listEcrData() to paginate using info passed from frontend 

## Related Issue
Fixes #2272

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-08-15 17:13 UTC, gordonfarrell requested changes
Looks great Lina, just one update needed to a comment section. Thanks!

2024-08-15 17:13 UTC, gordonfarrell commented on containers/ecr-viewer/src/app/api/services/listEcrDataService.ts
>   */
This comment block is a bit out of date now and needs some updates

2024-08-15 17:48 UTC, BobanL commented on containers/ecr-viewer/src/app/api/tests/listEcrDataService.test.tsx
> +        Promise.resolve<EcrMetadataModel[]>([
Could this type here be replaced with just `EcrMetadataModel`?
```suggestion
      database.manyOrNone<EcrMetadataModel> = jest.fn(() =>
        Promise.resolve<EcrMetadataModel[]>([
```

2024-08-15 17:48 UTC, BobanL commented on containers/ecr-viewer/src/app/api/tests/listEcrDataService.test.tsx
> +      }> = jest.fn(() =>
same as above, can this type be replaced by `EcrMetadataModel`?     
```suggestion
      database.manyOrNone<EcrMetadataModel> = jest.fn(() =>
```

2024-08-15 17:56 UTC, BobanL commented on containers/ecr-viewer/src/app/tests/components/__snapshots__/EcrTable.test.tsx.snap
Something looks like it went wrong with this snapshot test, the test should only request 25 items. Possibly an incorrect db mock somewhere is returning the 51 results

2024-08-16 11:54 UTC, BobanL approved these changes
just one super quick thing but otherwise looks good!

2024-08-16 11:54 UTC, BobanL commented on containers/ecr-viewer/src/app/api/services/listEcrDataService.ts
> +  let number = await database.manyOrNone("SELECT count(*) FROM fhir_metadata");
sorry, didn't see this earlier, but I think this can just be `one` instead of `manyOrNone` since count should only ever return 1 value.
```suggestion
  let number = await database.one("SELECT count(*) FROM fhir_metadata");
```

2024-08-16 13:19 UTC, BobanL commented on containers/ecr-viewer/src/app/api/services/listEcrDataService.ts
> +  return number[0].count;
sorry, didn't see this earlier, but I think this can just be `one` instead of `manyOrNone` since count should only ever return 1 value.
```suggestion
export const getTotalEcrCount = async (): Promise<number> => {
  let number = await database.one("SELECT count(*) FROM fhir_metadata");
  return number.count;
```

2024-08-20 20:55 UTC, gordonfarrell approved these changes

2024-08-20 21:08 UTC, merged