Added fatal error type to error messages
CDCgov/phdi pull request #240
Opened 2023-03-03 22:27 UTC by nickbristow

2023-03-06 19:27 UTC, KennethSkylight requested changes
A few minor changes needed

2023-03-06 19:27 UTC, KennethSkylight commented on phdi/validation/validation.py
> +    msgs = {"fatal": [], "error": [], "warning": [], "information": []}
can we use the full word messages instead of abbreviation

2023-03-06 19:27 UTC, KennethSkylight commented on phdi/validation/validation.py
> +        message_type = (
Having an error type should be required by our function, so this should be added to the validate_config... But I think it's already there?

2023-03-06 20:14 UTC, BradySkylight commented on phdi/validation/validation.py
> +    msgs = {"fatal": [], "error": [], "warning": [], "information": []}
Correct, I am using the full word instead of abbreviations.

2023-03-06 20:27 UTC, BradySkylight commented on phdi/validation/validation.py
> +        message_type = (
There already is a step to validate the error types passed in at the container level.  We can move this down to a lower level if you would like, as perhaps the SDK version will be used and not just at the container level.  Let me know your thoughts.

2023-03-06 20:28 UTC, BradySkylight commented on phdi/validation/validation.py
> +            information=msgs["information"],
I love this!  Much cleaner and easier to use as well as more organized.  Was happy to introduce this into my branch!  Nice work Nick!

2023-03-06 20:30 UTC, BradySkylight reviewed
Just a few comments and questions!  Overall, it looks good!

2023-03-06 20:30 UTC, BradySkylight commented on phdi/validation/validation.py
> +        message_type = (
Also, I think we will have to always include fatal errors at this time.  No filtering should be allowed for fatal errors, which should make the validation fail anyway.  Thoughts there as well?

2023-03-06 22:51 UTC, BradySkylight approved these changes
LGTM!

2023-03-07 17:43 UTC, KennethSkylight approved these changes

2023-03-07 17:46 UTC, merged