Add metadata to save fhir data api
CDCgov/phdi pull request #2455
Opened 2024-08-28 17:33 UTC by JNygaard-Skylight

# PULL REQUEST

## Summary
Updates the `save-fhir` endpoint to also save metadata

## Related Issue
Fixes #2367 

## Acceptance Criteria
- [ ] Create a new endpoint on the eCR Viewer to "save metadata" or similar
- [ ] New endpoint will take in a set of metadata from the message parsing service and a blob of FHIR data
- [ ] Endpoint will save blob data to S3 or Postgres, depending on user configuration (as happens today in `save-fhir-data-service.ts`) 
- [ ] After the blob storage is saved, ID or URL location of the blob is kept
- [ ] If running non-integrated viewer: data is then written out to the metadata table(s)
     - [ ] A link to the S3 URL or Postgres ID is also saved on this table
- [ ] This ticket is only focusing on the Postgres implementation of the core metadata (not the extended metadata version)

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-09-05 16:57 UTC, angelathe commented on containers/ecr-viewer/src/app/api/save-fhir-data/save-fhir-data-service.ts
> -    );
I think this message is used/mentioned in the Technical Acceptance Testing Guide to confirm a successful pipeline run -- any particular reason for removing?

2024-09-05 19:26 UTC, angelathe commented on containers/ecr-viewer/src/app/api/save-metadata/route.ts
> +          "Save location is undefined. Please provide a valid value for 'saveSource' (postgres or s3).",
Oops, missed this. Should this say (postgres, s3, or azure)?

2024-09-06 14:19 UTC, angelathe commented on containers/orchestration/app/custom_configs/philadelphia-ecr-viewer.json
> -        "saveSource": "s3"
Just a note (maybe out of scope for this ticket): Should we eventually change all references of "postgres" to "db" or something? To be agnostic to all the SQL flavors that jurisdictions may use
@emmastephenson

2024-09-06 15:00 UTC, angelathe requested changes

2024-09-06 15:14 UTC, emmastephenson commented on containers/ecr-viewer/src/app/api/save-metadata/route.ts
> +    return saveToAzure(metadata, ecrId);
Good catch - we wouldn't ever save metadata to either S3 or Azure, only to a relational database. But, the FHIR bundles should always be saved to blob storage, not the relational db. The logic chain should look more like this:
```
if (saveSource == POSTGRES_SOURCE) {
saveToPostgres(metadata, ecrID);
}

saveToPostgres(metadata, eCRID) {
// do the metadata pg writes
if (blobSaveSource == S3_SOURCE) {
saveBlobToS3(eCR);
} else if (blobSaveSource == AZURE) {
saveBlobToAzure()
}
```

2024-09-06 15:16 UTC, emmastephenson commented on containers/orchestration/app/custom_configs/philadelphia-ecr-viewer.json
>        "params": {
Yep, that's right Angela! We'll need to save the fhir data to S3 and then also save the metadata to the database.

2024-09-06 16:45 UTC, angelathe commented on containers/ecr-viewer/src/app/api/save-metadata/route.ts
> +    return saveToAzure(metadata, ecrId);
Sorry, one more clarifying question @emmastephenson! Should the `/save-metadata` endpoint also call the `/save-fhir-data` endpoint, or should saving the metadata & bundle to blob storage be separate steps in the Philly config?

2024-09-09 15:41 UTC, emmastephenson commented on containers/ecr-viewer/src/app/api/save-metadata/route.ts
> +    return saveToAzure(metadata, ecrId);
I think that's a but of an open question! It could be done either way, to be honest. I'd maybe have a slight preference for `/save-metadata` to just call `/save-fhir-data` directly, since I don't think there's ever going to be a scenario where you want to save the relational data but not the blob storage.

2024-09-11 15:05 UTC, JNygaard-Skylight commented on containers/ecr-viewer/src/app/api/save-metadata/route.ts
> +}
I've added metadata as an optional parameter to the FHIR endpoint.

2024-09-11 17:19 UTC, angelathe commented on containers/ecr-viewer/src/app/api/save-fhir-data/save-fhir-data-service.ts
> + * @function saveToS3
Function needs to be renamed

2024-09-11 17:19 UTC, angelathe commented on containers/orchestration/app/custom_configs/philadelphia-ecr-viewer.json
> +        "saveSource": "postgres"
Oops the `saveSource` might need to get reverted back to `s3` now since that only refers to the `save-fhir-data`

2024-09-11 17:19 UTC, angelathe commented on containers/ecr-viewer/src/app/api/save-fhir-data/save-fhir-data-service.ts
> +      { status: 500 },
Curious why you changed these to `500`?

2024-09-11 18:13 UTC, JNygaard-Skylight commented on containers/ecr-viewer/src/app/api/save-fhir-data/save-fhir-data-service.ts
> +      { status: 500 },
400 errors are client errors, 500 errors are server-side errors.  [Link.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)

2024-09-12 20:02 UTC, angelathe approved these changes
LGTM! Thanks so much Josh for all your work on this!!

2024-09-13 16:28 UTC, merged