Create harmonization tutorial
CDCgov/phdi pull request #25
Opened 2022-08-19 18:25 UTC by bamader

This PR creates the harmonization tutorial and two readmes in the harmonization package directories. The structure and content of these files mirrors that of the previously developed geospatial documentation. The geospatial tutorial has also had a few minor typos corrected, as well as formatting applied to in-line markdown code blocks.

2022-08-22 19:41 UTC, KennethSkylight commented on tutorials/harmonization-tutorial.md
> +The HL7 functioanlity of harmonization can enable pre-processing of one or more messages for storage or possbible conversion to FHIR, while the normalization functionality can operate on either raw d
functionality is mispelled

2022-08-22 19:47 UTC, KennethSkylight reviewed
Just some mispellings

2022-08-22 19:47 UTC, KennethSkylight commented on tutorials/harmonization-tutorial.md
> +The HL7 functioanlity of harmonization can enable pre-processing of one or more messages for storage or possbible conversion to FHIR, while the normalization functionality can operate on either raw d
possible is mispelled

2022-08-22 19:47 UTC, KennethSkylight commented on tutorials/harmonization-tutorial.md
> +If we choose not to pass in a parameter of countries, the standardization function will autmatically attempt to parse using the United States' country code. If we wish to attempt standardizing using
country is mispelled. automatically is mispelled

2022-08-23 15:17 UTC, bamader commented
Wow I really fat-fingered this one

2022-08-23 18:00 UTC, spencer-skylight requested changes
Just a few minor suggestions that shouldn't take long to clean up.

2022-08-23 18:00 UTC, spencer-skylight commented on tutorials/harmonization-tutorial.md
> +This guide serves as a tutorial overview of the functionality available in both `harmonization/` and `fhir.harmonization`. It will cover concepts such as data type basics, imports, and common uses in
Same nit as above - `phdi.harmonization` and `phdi.fhir.harmonization`?  There are a few more similar occurrences of this in this document as well that I won't comment on individually, but may make sense to consider together.

2022-08-23 18:00 UTC, spencer-skylight commented on tutorials/harmonization-tutorial.md
> +>>> "MSH|^~\\&|WIR11.3.2^^|WIR^^||WIRPH^^|20200514010000||VXU^V04"|2020051411020600-0400|P^|2.4^^|||ER"
You've got a stray double-quote in here.

2022-08-23 18:00 UTC, spencer-skylight commented on tutorials/harmonization-tutorial.md
> +```python
This isn't actually python code.

2022-08-23 18:00 UTC, spencer-skylight commented on tutorials/harmonization-tutorial.md
> +```python
Likewise, not actually python.

2022-08-23 18:00 UTC, spencer-skylight commented on tutorials/harmonization-tutorial.md
> +If we choose not to pass in a parameter of countries, the standardization function will automatically attempt to parse using the United States' country code. If we wish to attempt standardizing using
I looked at the code and found that US is always appended to the country list, even if there are other countries listed.  From my reading, if the number already starts with `+` and a country code, it will ignore the country list and parse the number using that country code.

2022-08-23 18:00 UTC, spencer-skylight commented on tutorials/harmonization-tutorial.md
> +assert cleaned_patient.get("name").get("given") == ["JOHN", "DANGER"]
Danger is my middle name. :laughing:

2022-08-23 19:01 UTC, bamader commented on tutorials/geospatial-tutorial.md
> +This guide serves as a tutorial overview of the functionality available in both `geospatial/` and `fhir.geospatial/`. It will cover concepts such as data type basics, imports, and common uses invocat
This is probably a good practice to get into for these tutorials, so I'm going to implement this change throughout both of the tutorials.

2022-08-23 19:10 UTC, bamader commented on tutorials/harmonization-tutorial.md
> +If we choose not to pass in a parameter of countries, the standardization function will automatically attempt to parse using the United States' country code. If we wish to attempt standardizing using
Description modified to reflect this, good catch

2022-08-23 19:10 UTC, bamader commented on tutorials/harmonization-tutorial.md
> +assert cleaned_patient.get("name").get("given") == ["JOHN", "DANGER"]
I'm glad someone picks up on these little snippets I throw into the examples 😂 . We gotta keep it fun for the users (definitely not just for ourselves...)

2022-08-24 12:17 UTC, spencer-skylight approved these changes
Looks great! Awesome work as always! :)

2022-08-24 12:17 UTC, spencer-skylight commented on tutorials/harmonization-tutorial.md
> +assert cleaned_patient.get("name").get("given") == ["JOHN", "DANGER"]
:100:

2022-08-24 15:58 UTC, merged