Probabilistic enhancements MVP
CDCgov/phdi pull request #250
Opened 2023-03-08 14:12 UTC by bamader

This PR adds the MVP of probabilistic enhancement to our algorithm as an optional boolean parameter. It uses precomputed log odds and some new decision functions to make this work, as well as introduces a graphical profiler for determining the separation boundary between the two bimodal distributions of matches and non-matches.

2023-03-08 21:38 UTC, m-goggins requested changes
I added a few clarifying questions and removed some commented out sections.  I noticed that the code coverage decreased a bit so you may want to check the misses.

2023-03-08 21:38 UTC, m-goggins commented on examples/Record-Linkage-sample-data/evaluate_lac.py
> +    # calculate_log_odds
```suggestion

```

2023-03-08 21:38 UTC, m-goggins commented on examples/Record-Linkage-sample-data/evaluate_lac.py
> +    # profile_log_odds,
```suggestion

```

2023-03-08 21:38 UTC, m-goggins commented on examples/Record-Linkage-sample-data/evaluate_lac.py
>  # end = time.time()
```suggestion

```

2023-03-08 21:38 UTC, m-goggins commented on examples/Record-Linkage-sample-data/evaluate_lac.py
>  # matches = lac_validation_linkage(data, None)
```suggestion
```

2023-03-08 21:38 UTC, m-goggins commented on examples/Record-Linkage-sample-data/evaluate_lac.py
> +# )
```suggestion
```

2023-03-08 21:38 UTC, m-goggins commented on phdi/linkage/link.py
> +        raise KeyError("Cutoff threshold for true matches must be passed.")
Do we want to add this as an explicit input?

2023-03-08 21:38 UTC, m-goggins commented on phdi/linkage/link.py
> +    plt.show()
This is a blocking function, which could prevent users from proceeding if they do not manually close the window. We could instead save off the graph, use a fig and add `plt.close(fig)`, or use `plt.ion()`. I haven't used the last option before but it [looks like](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.ion.html) it might make it easier to use `.close()` and `.show()`

2023-03-08 21:38 UTC, m-goggins commented on examples/Record-Linkage-sample-data/evaluate_lac.py
> +            8: feature_match_log_odds_exact,
This one is `sex` right? I think we should remove in light of the conversation with LAC last week. It might also be nice to add comments about which columns the `funcs` apply to.

2023-03-08 21:38 UTC, m-goggins commented on examples/Record-Linkage-sample-data/evaluate_lac.py
> +        true_match_threshold=16.5,
The `true_match_threshold` is coming from the log_odds ratio JSON, right?

2023-03-14 17:47 UTC, bamader commented on examples/Record-Linkage-sample-data/evaluate_lac.py
> +    # calculate_log_odds
For the commented code on the `evaluate_lac.py` script, I left it in in case someone wanted to just run some of the functions (i.e. calculate new probabilities, etc) without needing to worry about imports. They could just comment/uncomment the parts of the code they were using. I have no problem taking it out if you'd rather do that though?

2023-03-14 17:49 UTC, bamader commented on phdi/linkage/link.py
> +        raise KeyError("Cutoff threshold for true matches must be passed.")
The reason I didn't is because our other `eval_` function doesn't use it as a parameter at all, or even accept it. If we made it an explicit param here, then we'd have to make it an explicit param in the `eval_perfect_match` function which didn't make sense to me (and the reason we'd have to mirror the two signatures is because the linkage pass function just does a handoff call to whatever eval function the user supplies, so doing all of the params except the vector of comparisons via `kwargs` allows us to preserve that modularity).

2023-03-14 17:53 UTC, bamader commented on phdi/linkage/link.py
> +    plt.show()
I guess my thinking was it actually _should_ be a blocking function. The only reason to create the histogram is so that you can visually inspect where the two bimodal distributions separate to figure out the best cutoff score (which I think should also leverage matplotlib's built in graph zooming functionality). I didn't envision a use case where a user would call this function and then leave the histogram up while trying to do other stuff.

That being said, just because I didn't envision it doesn't mean the user won't do it lol. It looks like the link you pasted goes to docs around parameters for interactive mode--wouldn't that be the same kind of blocking function you want to avoid?

2023-03-14 17:53 UTC, bamader commented on examples/Record-Linkage-sample-data/evaluate_lac.py
> +            8: feature_match_log_odds_exact,
Yeah it is, and yeah I can definitely do both of those things

2023-03-14 17:57 UTC, bamader commented on examples/Record-Linkage-sample-data/evaluate_lac.py
> +        true_match_threshold=16.5,
No, that threshold needs to be selected by the user by looking at the overlap between the bimodal distributions of true match scores and non match scores. I guess we could store it in the JSON file after it's been experimentally determined, which would make some sense, but I was envisioning it to be easier for users to have a constant at the top of their script that they would just write the value into after they figured it out. No strong feelings either way so I'm happy to shove it into the JSON if desired!

2023-03-14 18:31 UTC, m-goggins commented on examples/Record-Linkage-sample-data/evaluate_lac.py
> +    # calculate_log_odds
Your reasoning makes sense to me. I'm good to keep it in.

2023-03-14 18:31 UTC, m-goggins commented on phdi/linkage/link.py
> +        raise KeyError("Cutoff threshold for true matches must be passed.")
Gotcha, that makes sense!

2023-03-14 18:33 UTC, m-goggins commented on examples/Record-Linkage-sample-data/evaluate_lac.py
> +        true_match_threshold=16.5,
At the top is fine by me, I think we just need to make that clearer/implement in our script.

2023-03-14 18:35 UTC, m-goggins commented on phdi/linkage/link.py
> +    plt.show()
hmm I'm not sure what I meant to post or what I thought you might get out of those docs ha. I think it's okay to leave for now since I don't anticipate a rush of users but we may want to revisit if this kind profiling is ever rolled into a pipeline.

2023-03-14 20:11 UTC, bamader commented on phdi/linkage/link.py
> +    plt.show()
Yeah good call. I'll leave a comment with a note to that effect.

2023-03-14 21:10 UTC, m-goggins approved these changes
Looks good to me!

2023-03-15 12:13 UTC, merged