Add Facility Details section to encounter info
CDCgov/phdi pull request #2614
Opened 2024-09-23 21:32 UTC by gordonfarrell

# PULL REQUEST

## Summary
Update the Encounter section, creating a facility data subsection with some data from the previous encounter info section and a new Facility Contact Address field

## Related Issue
Fixes #2506

## Acceptance Criteria
- [ ] New `Facility Details` section is added to `Encounter Info` 
- [ ] The following fields are added to that section in the order specified below:
    - [ ] Facility Name
    - [ ] Facility Address
    - [ ] Facility Contact
    - [ ] Facility Contact Address
    - [ ] Facility Type
    - [ ] Facility ID
- [ ] The data in the fields should match the data found in the `componentOf > encompassingEncounter > location > healthCareFacility` section of the xml
- [ ] If these fields are not present in the eCR document, they are added to the `Unavailable Info` section

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-09-24 20:50 UTC, sarahtress commented
@gordonfarrell I think this looks good to me. it's a bit hard to do a full check because I don't have the source eCR xmls for what I'm looking at in the viewer, but I think the best way to check that will actually just be QAing all of the fields once the MVP changes are all done, rather than on a ticket by ticket basis

2024-09-25 14:55 UTC, gordonfarrell commented
> @gordonfarrell I think this looks good to me. it's a bit hard to do a full check because I don't have the source eCR xmls for what I'm looking at in the viewer, but I think the best way to check that will actually just be QAing all of the fields once the MVP changes are all done, rather than on a ticket by ticket basis

Sounds good thanks Sarah!

2024-09-25 18:36 UTC, angelathe requested changes
Looks good, just a couple of small changes!

Also, since this ticket had some FHIR conversion, we probably want to update the `data.sql` file (`npm run convert-seed-data -- --build`)

2024-09-25 18:36 UTC, angelathe commented on containers/ecr-viewer/src/app/view-data/components/AccordionContent.tsx
>            providerData.availableData.length > 0 ? (
probably want to also check the length of facilityData here:
```
 {encounterData.availableData.length > 0 ||
facilityData.availableData.length > 0 ||                    /* <--- here */
          providerData.availableData.length > 0 ? (
```

2024-09-25 18:36 UTC, angelathe commented on containers/fhir-converter/Templates/eCR/Header.liquid
> +      {% include 'Reference/Encounter/ServiceProvider' ID: encounterId, REF: fullServiceProviderId, LOC: msg.ClinicalDocument.componentOf.encompassingEncounter.location.healthCareFacility.serviceProv
Looking at `Reference/Encounter/SeviceProvider`, I don't think they take a LOC attr (this might've just been accidentally copied over from Line 25?)

2024-09-25 18:36 UTC, angelathe commented on containers/ecr-viewer/src/app/view-data/components/UnavailableInfo.tsx
For consistency, we should probably add a `facilityUnavailableData` const in `Unavailable.test.tsx` to update the snapshot with these new fields?

2024-09-25 18:36 UTC, angelathe commented on containers/ecr-viewer/src/app/api/fhirPath.yml
>  facilityLocation: "Bundle.entry.resource.where(resourceType = 'Encounter')[0].location[0].location.reference"
Are there any paths here that aren't used anymore that we can clean up? A bit confusing to have these named similarly but also from slightly different sources

2024-09-25 19:08 UTC, gordonfarrell commented on containers/ecr-viewer/src/app/api/fhirPath.yml
>  facilityLocation: "Bundle.entry.resource.where(resourceType = 'Encounter')[0].location[0].location.reference"
I dont think so, despite being very similar Contact address info and location address info can be different

2024-09-26 03:45 UTC, angelathe approved these changes
LGTM!

2024-09-26 14:08 UTC, merged