Disable Pool Client SSL Configuration for tefca
CDCgov/phdi pull request #2641
Opened 2024-09-30 14:59 UTC by robertandremitchell

# PULL REQUEST

## Summary
Does 2 things:
1. Disables SSL to remove it as a potential confound for AWS connection
2. Restores `tefca.env` and amends `npm run dev` to work correctly for local development

## Related Issue
Fixes SSL issue that appears to be impact 

## Acceptance Criteria
Please copy the acceptance criteria from your ticket and paste it here for your reviewer(s)

## Additional Information
I would test both docker compose up and npm run dev to confirm both are still able to connect.

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-09-30 15:31 UTC, fzhao99 commented on containers/tefca-viewer/src/app/database-service.ts
> +console.log("Connection String:", process.env.DATABASE_URL);
would there be any world where we'd log out secrets here?

2024-09-30 15:33 UTC, fzhao99 approved these changes
left one q but otherwise lgtm! local dev spins up as expected

2024-09-30 15:33 UTC, robertandremitchell commented on containers/tefca-viewer/src/app/database-service.ts
> +console.log("Connection String:", process.env.DATABASE_URL);
oops, no, that's a leftover from when I was testing what was happening with local. removing now!

2024-09-30 15:35 UTC, DanPaseltiner requested changes
Getting the `dev` script running again is a good thing, but I'm concerned about taking steps within the app to disable SSL. This hasn't been and issue previously and creates a security issue for us.

2024-09-30 15:35 UTC, DanPaseltiner commented on containers/tefca-viewer/docker-compose.yaml
> -      - DATABASE_URL=postgres://postgres:pw@db:5432/tefca_db
No change should be needed here since this only matters when we run on our locals and this is working just fine

2024-09-30 15:35 UTC, DanPaseltiner commented on containers/tefca-viewer/src/app/database-service.ts
> -// import dotenv from "dotenv";
I don't believe we should be using dotenv here as we aren't going to supply a dotenv file for any deployment beyond running locally.

2024-09-30 15:35 UTC, DanPaseltiner commented on containers/tefca-viewer/src/app/database-service.ts
> +  ssl: false, // Disable SSL explicitly
Disable SSL seems highly suspect to me.

2024-09-30 15:35 UTC, DanPaseltiner commented on containers/tefca-viewer/package.json
> +    "dev": "docker-compose -f docker-compose-dev.yaml up -d && npx next dev",
I don't believe `npx` is required here. `...&& next dev` is sufficient on my machine

2024-09-30 16:34 UTC, robertandremitchell commented on containers/tefca-viewer/src/app/database-service.ts
> -// import dotenv from "dotenv";
this was added back to support running locally. the dev compose file doesn't have a URL, so we need some way of supplying it in the event that it's not in a docker file, so I just restored the dotenv that had been used previously.

2024-09-30 16:34 UTC, robertandremitchell commented on containers/tefca-viewer/package.json
> +    "dev": "docker-compose -f docker-compose-dev.yaml up -d && npx next dev",
weird, I had needed it at one point, but yeah, seems fine.

2024-09-30 20:04 UTC, robertandremitchell commented on containers/tefca-viewer/src/app/database-service.ts
> +  ssl: false, // Disable SSL explicitly
swapped to enable, which seems to be working fine locally.

2024-09-30 20:35 UTC, robertandremitchell commented on containers/tefca-viewer/src/app/database-service.ts
> -// import dotenv from "dotenv";
I think I'm okay getting rid of it if we want to test this solution. We will just have to backburner a better way to get local development working, because it was a real headache not having working local development, but we can remove tefca.env again to get AWS working..

2024-10-01 14:53 UTC, DanPaseltiner commented
@robertandremitchell why have we checked in an entire Postgres DB? I could very well be missing something here.

2024-10-01 15:02 UTC, robertandremitchell commented
> @robertandremitchell why have we checked in an entire Postgres DB? I could very well be missing something here.

I've been having trouble getting the playwright tests to pass, so was just trying to chase down that error.

I went from:
```
[WebServer] db-1            | postgres: could not access the server configuration file "/var/lib/postgresql/data/postgresql.conf": No such file or directory
```

to:

```
[WebServer] db-1            | 2024-10-01 14:50:01.851 UTC [11] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
db-1            | 2024-10-01 14:50:01.851 UTC [11] HINT:  The server must be started by the user that owns the data directory.
```

with this change, so hoping that once I figure that out, I can then remove pgdata/ or limit it to just pgdata.conf.

2024-10-02 14:16 UTC, closed without merging