fix immunization name bug
CDCgov/phdi pull request #2805
Opened 2024-10-23 13:39 UTC by BobanL

# PULL REQUEST

## Summary
- Add both translation and original code in order to get the proper display name

## Related Issue
Fixes #2754 

## Acceptance Criteria
Please copy the acceptance criteria from your ticket and paste it here for your reviewer(s)

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-10-23 17:32 UTC, JNygaard-Skylight requested changes
Would it be possible to add or update a test to test the change in the fhir-converter?

2024-10-24 15:50 UTC, mcmcgrath13 commented on containers/fhir-converter/Templates/eCR/Resource/_Immunization.liquid
> +                                { {% include 'DataType/Coding', Coding: manufacturedProduct.manufacturedMaterial.code.translation -%} },
is the translation here always one item? in the meds, I'm seeing it can be multiple. In #2816 I create an array out of the code and translations and iterate through them all

2024-10-24 15:51 UTC, mcmcgrath13 commented on containers/fhir-converter/Templates/eCR/Resource/_Immunization.liquid
> +                                { {% include 'DataType/Coding', Coding: manufacturedProduct.manufacturedMaterial.code.translation -%} },
you could also use `DataType/CodableConcept` here instead of hardcoding the `"coding"`. I've updated it in that PR to accept an array

2024-10-24 15:52 UTC, mcmcgrath13 commented on containers/fhir-converter/Templates/eCR/Resource/_Immunization.liquid
>                          "vaccineCode":{ {% include 'DataType/CodeableConcept' CodeableConcept: manufacturedProduct.manufacturedMaterial.code -%} },
do we want the if/else here or just always get the code and translation? seems like this branch is redundant

2024-10-30 12:16 UTC, BobanL commented on containers/fhir-converter/Templates/eCR/Resource/_Immunization.liquid
>                          "vaccineCode":{ {% include 'DataType/CodeableConcept' CodeableConcept: manufacturedProduct.manufacturedMaterial.code -%} },
Fixed in #[add39dd](https://github.com/CDCgov/phdi/pull/2805/commits/add39dd48f4aeb03de6e571b62581c33868f9007)

2024-10-30 12:16 UTC, BobanL commented on containers/fhir-converter/Templates/eCR/Resource/_Immunization.liquid
> +                                { {% include 'DataType/Coding', Coding: manufacturedProduct.manufacturedMaterial.code.translation -%} },
Used it in [add39dd](https://github.com/CDCgov/phdi/pull/2805/commits/add39dd48f4aeb03de6e571b62581c33868f9007)

2024-10-30 13:30 UTC, mcmcgrath13 commented on containers/fhir-converter/Templates/eCR/Resource/_Immunization.liquid
> +                    "vaccineCode":{ {% include 'DataType/CodeableConcept' CodeableConcept: manufacturedProduct.manufacturedMaterial.code -%} },
should we include both the code and the translations?

2024-10-30 15:18 UTC, mcmcgrath13 approved these changes
a couple small questions, but overall lgtm!

2024-10-30 15:18 UTC, mcmcgrath13 commented on containers/fhir-converter/Templates/eCR/Resource/_Immunization.liquid
> +                    {% assign translations = manufacturedProduct.manufacturedMaterial.code.translation | to_array -%}
given this is now more reliable, does the `note.text` field still make sense?

2024-10-30 15:18 UTC, mcmcgrath13 commented on containers/fhir-converter/tests/integration/test_FHIR-Converter.py
> +        Path(__file__).parent.parent / "test_files/snapshot" / dir_name / "CDA_eICR.xml"
is the hardcoded slash here windows safe? or does it not matter due to docker reliance?

2024-10-30 15:29 UTC, JNygaard-Skylight approved these changes

2024-10-30 18:12 UTC, BobanL commented on containers/fhir-converter/tests/integration/test_FHIR-Converter.py
> +        Path(__file__).parent.parent / "test_files/snapshot" / dir_name / "CDA_eICR.xml"
I can confirm this works on windows!

2024-10-30 18:20 UTC, merged