More dynamic sizing of library columns for larger windows
CDCgov/phdi pull request #2824
Opened 2024-10-28 15:16 UTC by gordonfarrell

# PULL REQUEST

## Summary
Updates CSS around sizing of eCR library columns so they're more even in larger windows

## Related Issue
Fixes #2309

## Acceptance Criteria
When resizing the browser width, Reportable Condition, RCKMS Rule Summary, and Patient columns should all resize responsively. 

The two date columns should always stay at a constant width.

Refer to designs for relative proportions for each column width

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-10-29 19:58 UTC, BobanL requested changes
Some funkiness with the date columns growing.

2024-10-29 19:58 UTC, BobanL commented on containers/ecr-viewer/src/styles/custom-styles.scss
> +}
So I think these are growing larger than 8.3 rem because they end up taking the remaining space since the other columns are only taking up a total of 81.8%. I tested locally and setting width to 0% and the others grew by the remaining space instead. I _think_ it has to do with the [table layout being fixed](https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout#fixed), but I'm not totally sure.

2024-11-04 16:37 UTC, gordonfarrell commented
This should be good for a merge now that I've spoken with Ashton and slightly altered the AC to fit what came out of our convo. When built out to the original AC it looked kinda funky without the right date column growing.

2024-11-04 16:37 UTC, gordonfarrell commented on containers/ecr-viewer/src/styles/custom-styles.scss
> +}
See note below

2024-11-04 21:44 UTC, BobanL approved these changes
👍

2024-11-04 23:11 UTC, merged