Create a new orchestration config to save bundles to ecr-viewer
CDCgov/phdi pull request #2853
Opened 2024-11-01 16:09 UTC by JNygaard-Skylight

# PULL REQUEST

## Summary
Created a new orchestration configuration to save a fhir bundle to the database (the same as the current configuration minus conversion) so that if the seed data script finds a directory with just a bundle it can still save it to the database.

## Related Issue
Fixes # n/a

## Acceptance Criteria
1) Add a directory to `containers/ecr-viewer/seed-scripts/baseECR` with a FHIR bundle called `bundle.json`.
2) Run `npm run convert-seed-data `.
3) Check if the eCR from the bundle is in the database.

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-11-04 21:34 UTC, austin-hall-skylight requested changes

2024-11-04 21:34 UTC, austin-hall-skylight commented on containers/ecr-viewer/seed-scripts/create-seed-data.py
> +    subfolders = ["ME"]
This needs to be changed back.

2024-11-04 21:34 UTC, austin-hall-skylight commented on containers/ecr-viewer/seed-scripts/create-seed-data.py
> +        "--force_convert",
I like the idea of being able to skip conversion to speed up seeding, but I typically use convert-seed-data to test my FHIR conversion changes so I would lean towards converting by default and having a flag to skip. I'd be interested in hearing the opinions of the other engineers though.

2024-11-04 21:45 UTC, BobanL commented on containers/ecr-viewer/seed-scripts/create-seed-data.py
> +    subfolders = ["ME"]
Should we just let it generate everything now?

2024-11-04 21:45 UTC, angelathe commented on containers/ecr-viewer/seed-scripts/create-seed-data.py
> +        "--force_convert",
^ I like this idea!

2024-11-04 21:46 UTC, BobanL commented on containers/ecr-viewer/seed-scripts/create-seed-data.py
> +        "--force_convert",
I would agree with Austin, default should regenerate the bundles and then we can add the flag to skip.

2024-11-07 18:11 UTC, JNygaard-Skylight commented on containers/ecr-viewer/seed-scripts/create-seed-data.py
> +    subfolders = ["ME"]
I've reverted this to just LA.

2024-11-07 19:06 UTC, austin-hall-skylight approved these changes

2024-11-07 19:35 UTC, merged