ci: add data conversion github action
CDCgov/phdi pull request #2910
Opened 2024-11-15 16:35 UTC by mcmcgrath13

# PULL REQUEST

## Summary
What changes are being proposed?

## Related Issue
Fixes #

## Acceptance Criteria
Please copy the acceptance criteria from your ticket and paste it here for your reviewer(s)

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-11-19 19:29 UTC, BobanL approved these changes
👏 👏 👏 👏

2024-11-19 21:03 UTC, BobanL requested changes
Thought of a change that needs to be made to the npm scripts!

2024-11-19 21:03 UTC, BobanL commented on containers/ecr-viewer/seed-scripts/docker-compose-seed.yml
> +  - ../docker-compose.yml
Actually - I think this causes issues in the `npm run local-dev` script. After running `convert-seed-data`, the DB is is empty for `local-dev` because the DB volume is created for a different service. 

If we want to keep this pattern, I _think_ a new seed profile will need to be added this whole file and add that to `convert-seed-data`. `local-dev` and `clear-local` should point this docker-compose file.

2024-11-19 22:10 UTC, mcmcgrath13 commented on containers/ecr-viewer/seed-scripts/docker-compose-seed.yml
> +  - ../docker-compose.yml
nice catch! I was able to fix this by having both composes work in the same `name` space, so the volume is named consistently during conversion and use

2024-11-19 22:44 UTC, mcmcgrath13 commented on containers/ecr-viewer/README.md
> +1. Delete the current volume used by your DB: `docker compose -f ./seed-scripts/docker-compose-seed.yml --profile "*" down -v`
```suggestion
1. Delete the current volume used by your DB: `docker compose -f ./docker-compose.yml --profile "*" down -v`
```

2024-11-20 00:14 UTC, BobanL commented on containers/ecr-viewer/seed-scripts/docker-compose-seed.yml
> +  - ../docker-compose.yml
Never knew about the `name` property! Nice find!

2024-11-20 00:14 UTC, BobanL approved these changes
👏 👏 👏 👏 👏  for real this time

2024-11-20 13:22 UTC, merged