Update parsing and saving of multiple rule summaries for one condition
CDCgov/phdi pull request #2923
Opened 2024-11-18 16:04 UTC by gordonfarrell

# PULL REQUEST

## Summary
Updates parsing to return lists of summaries per condition

## Related Issue
Fixes #2922

## Acceptance Criteria
- [ ] The message parser returns an array of rule summaries per condition
- [ ] Metadata saving loops through all arrays and saves conditions and rules along with their relationships

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-11-21 16:37 UTC, JNygaard-Skylight requested changes

2024-11-21 16:37 UTC, JNygaard-Skylight commented on containers/ecr-viewer/sql/extended.sql
> +    test_type_system                       VARCHAR(MAX),
A suggestion made on my PR was to reduce the size of test_type_system. While this is a URI and URIs do not technically have a maximum size, I think a size like 255 should be sufficient?

2024-11-22 17:20 UTC, gordonfarrell commented on containers/ecr-viewer/sql/extended.sql
> +    test_type_system                       VARCHAR(MAX),
I had actually already changed this to match your PR, probably right as you typed this haha

2024-11-22 17:20 UTC, gordonfarrell commented on containers/ecr-viewer/src/app/api/save-fhir-data/save-fhir-data-service.ts
> +    console.log("Error connecting to MS SQL Server: ", error);
I grabbed your try catch for this block as well

2024-11-22 17:22 UTC, JNygaard-Skylight approved these changes
LGTM

2024-11-22 17:52 UTC, merged