Conditions Endpoint
CDCgov/phdi pull request #2934
Opened 2024-11-19 16:05 UTC by JNygaard-Skylight

# PULL REQUEST

## Summary
Adds `/api/conditions` endpoint to get a list of the conditions in ecr-viewer.

## Related Issue
Fixes #2749 

## Acceptance Criteria
Please copy the acceptance criteria from your ticket and paste it here for your reviewer(s)

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2024-11-20 21:41 UTC, mcmcgrath13 commented on containers/ecr-viewer/docker-compose.yml
> +      - SQL_SERVER_HOST=${SQL_SERVER_HOST}
```suggestion
      - SQL_SERVER_HOST=${SQL_SERVER_HOST:-sqlserver}
```

2024-11-20 21:57 UTC, mcmcgrath13 commented on containers/ecr-viewer/src/app/api/conditions/service.ts
> +        text: 'SELECT DISTINCT "condition" FROM ecr_rr_conditions',
do we want to sort these?

2024-11-20 21:59 UTC, mcmcgrath13 commented on containers/ecr-viewer/src/app/api/save-fhir-data/route.ts
> +  let saveSource = requestBody.saveSource || process.env.SOURCE;
```suggestion
  const saveSource = requestBody.saveSource || process.env.SOURCE;
```

2024-11-20 22:06 UTC, mcmcgrath13 reviewed
not super familiar with the part of the code base, so just commenting

2024-11-20 22:06 UTC, mcmcgrath13 commented on containers/ecr-viewer/src/app/api/save-fhir-data/save-fhir-data-service.ts
> +              sql.VarChar(sql.MAX),
the leap from 50 to max here is a lot - do we really need all the chars?

2024-11-20 22:06 UTC, mcmcgrath13 commented on containers/ecr-viewer/src/app/api/save-fhir-data/save-fhir-data-service.ts
> +      console.log(metadata);
is this a debug print?

2024-11-20 22:06 UTC, mcmcgrath13 commented on containers/ecr-viewer/src/app/api/save-fhir-data/save-fhir-data-service.ts
> +      console.log("Saving metadata to SQL Server");
just checking these logs are left on purpose

2024-11-20 23:26 UTC, JNygaard-Skylight commented on containers/ecr-viewer/src/app/api/save-fhir-data/save-fhir-data-service.ts
> +              sql.VarChar(sql.MAX),
Surely we'll never see a URI larger than 255 characters, right? Right?

2024-11-20 23:26 UTC, JNygaard-Skylight commented on containers/ecr-viewer/src/app/api/save-fhir-data/save-fhir-data-service.ts
> +      console.log(metadata);
Yep

2024-11-20 23:26 UTC, JNygaard-Skylight commented on containers/ecr-viewer/src/app/api/save-fhir-data/save-fhir-data-service.ts
> +      console.log("Saving metadata to SQL Server");
Nope.

2024-11-22 12:26 UTC, BobanL requested changes
Looks good, but just a couple of small nits.

2024-11-22 12:26 UTC, BobanL commented on containers/ecr-viewer/seed-scripts/sql/extended.sql
Instead of copying this file here, can we update the docker-compose to copy the real one? I believe you'll need to update  `test_type_system` and   `test_result_qualitative` in that one too.
```yaml
- ./sql/extended.sql:/var/opt/mssql/scripts/extended.sql
```

2024-11-22 12:26 UTC, BobanL commented on containers/ecr-viewer/src/app/api/conditions/route.ts
> +      return NextResponse.json({ message: "Invalid source" }, { status: 500 });
since we have another variable called "source", could we update this error to specifically say `Invalid metadata database type`?

2024-11-22 16:01 UTC, BobanL commented on containers/ecr-viewer/src/app/api/conditions/service.ts
> +  });
Since we initialize this connection in this file and in [save-fhir-data-service.ts](https://github.com/CDCgov/phdi/pull/2934/files#diff-0468423247e989196d5fe517d4f19e1652b5d42670d6ffa4da69cf3ea0a1aeaa) can we just pull this out into a single file like we do for postgres?

2024-11-25 17:00 UTC, BobanL approved these changes
Thanks for the cleanup!

2024-11-25 19:49 UTC, merged