Add alcohol use, intake, and comment
CDCgov/phdi pull request #3043
Opened 2024-12-12 16:27 UTC by lina-roth

# PULL REQUEST
<img width="1705" alt="Screenshot 2024-12-05 at 12 51 41 PM" src="https://github.com/user-attachments/assets/3aee81cc-fb5d-4182-856e-df92e3b435d1" />

## Summary
- [ ] Add/update fhir paths for alcohol use, intake, comment
- [ ] Add evaluateAlcoholUse to display any existing values
- [ ] Add relevant tests

## Related Issue
Fixes #2725

2024-12-12 16:30 UTC, ashton-skylight commented
Looking good, Lina! Many thanks

2024-12-12 16:48 UTC, mcmcgrath13 commented on containers/ecr-viewer/src/app/api/fhirPath.yml
> +patientAlcoholComment: "Bundle.entry.resource.where(resourceType='Observation').where(code.coding.display='Alcohol Comment').valueString"
these should all be able to just be `.value` and let `evaluateValue` handle the pulling out the thing (/were you seeing otherwise?)

2024-12-12 16:48 UTC, mcmcgrath13 commented on containers/ecr-viewer/src/app/services/evaluateFhirDataService.ts
> +  let alcoholComment: string | undefined = evaluate(
```suggestion
  const alcoholUse = evaluateValue(fhirBundle, fhirMappings.patientAlcoholUse);
  const alcoholIntake = evaluateValue(fhirBundle, fhirMappings.patientAlcoholIntake);
  let alcoholComment: string | undefined = evaluateValue(
```

2024-12-12 16:48 UTC, mcmcgrath13 commented on containers/ecr-viewer/src/app/tests/services/evaluateFhirDataServices.test.ts
> +        "Comment: 1-2 drinks 2 to 4 times a month",
```suggestion
      "Intake (standard drinks/week): .29/d\n" +
      "Comment: 1-2 drinks 2 to 4 times a month",
```

2024-12-12 16:48 UTC, mcmcgrath13 commented on containers/ecr-viewer/src/app/tests/services/evaluateFhirDataServices.test.ts
> +        "Comment: 1-2 drinks 2 to 4 times a month",
(though maybe this is linting and moot - it just looks funny to my eye)

2024-12-12 17:15 UTC, lina-roth commented on containers/ecr-viewer/src/app/tests/services/evaluateFhirDataServices.test.ts
> +        "Comment: 1-2 drinks 2 to 4 times a month",
yeah this is linting

2024-12-12 17:15 UTC, lina-roth commented on containers/ecr-viewer/src/app/api/fhirPath.yml
> +patientAlcoholComment: "Bundle.entry.resource.where(resourceType='Observation').where(code.coding.display='Alcohol Comment').valueString"
what is the benefit of doing this and using evaluateValue vs what I am currently doing

2024-12-17 17:21 UTC, mcmcgrath13 commented on containers/ecr-viewer/src/app/services/evaluateFhirDataService.ts
> +  ).toString();
what's the case where this isn't a string?

2024-12-17 17:43 UTC, lina-roth commented on containers/ecr-viewer/src/app/services/evaluateFhirDataService.ts
> +  ).toString();
if its just string, it complains on alcoholComment = toSentenceCase(alcoholComment)

TS2322: Type string | undefined is not assignable to type string
Type undefined is not assignable to type string

2024-12-17 18:29 UTC, mcmcgrath13 approved these changes
LGTM!

2024-12-17 19:16 UTC, mcmcgrath13 commented on containers/fhir-converter/Dockerfile
> +RUN git clone https://github.com/skylight-hq/FHIR-Converter.git --branch v7.0-skylight-18 --single-branch /build/FHIR-Converter
sorry I didn't catch this before! fhir standard says the value needs to be a decimal - we should try to fix this another way 🙏 https://www.hl7.org/fhir/r4b/datatypes.html#Quantity

2024-12-17 19:22 UTC, mcmcgrath13 requested changes
https://www.hl7.org/fhir/json.html#decimal

2024-12-17 21:28 UTC, lina-roth commented on containers/fhir-converter/Dockerfile
> +RUN git clone https://github.com/skylight-hq/FHIR-Converter.git --branch v7.0-skylight-18 --single-branch /build/FHIR-Converter
fixed in FHIR-Converter

2024-12-17 21:32 UTC, austin-hall-skylight approved these changes

2024-12-17 21:36 UTC, mcmcgrath13 commented on containers/fhir-converter/Dockerfile
> +RUN git clone https://github.com/skylight-hq/FHIR-Converter.git --branch v7.0-skylight-18 --single-branch /build/FHIR-Converter
should this now be 19?

2024-12-17 21:37 UTC, lina-roth commented on containers/fhir-converter/Dockerfile
> +RUN git clone https://github.com/skylight-hq/FHIR-Converter.git --branch v7.0-skylight-18 --single-branch /build/FHIR-Converter
nope. i deleted the tags and release. 18 is correct

2024-12-17 21:37 UTC, mcmcgrath13 commented on containers/fhir-converter/tests/integration/__snapshots__/test_FHIR-Converter.ambr
> +              'value': '8',
these need to be re-updated

2024-12-17 21:42 UTC, mcmcgrath13 approved these changes
thanks!

2024-12-17 21:43 UTC, mcmcgrath13 commented on containers/fhir-converter/Dockerfile
> +RUN git clone https://github.com/skylight-hq/FHIR-Converter.git --branch v7.0-skylight-18 --single-branch /build/FHIR-Converter
nice! That might mess with github actions caching, but hopefully it just works

2024-12-17 21:46 UTC, mcmcgrath13 commented on containers/fhir-converter/Dockerfile
> +RUN git clone https://github.com/skylight-hq/FHIR-Converter.git --branch v7.0-skylight-18 --single-branch /build/FHIR-Converter
no dice

2024-12-17 21:52 UTC, merged