add playwright init and tests
CDCgov/phdi pull request #3067
Opened 2024-12-16 17:48 UTC by BobanL

# PULL REQUEST

## Summary
What changes are being proposed?

## Related Issue
Fixes #

## Acceptance Criteria
Please copy the acceptance criteria from your ticket and paste it here for your reviewer(s)

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2025-01-03 16:14 UTC, mcmcgrath13 commented on containers/ecr-viewer/docker-compose.yml
> +      - SQL_SERVER_HOST=sqlserver
what if the user isn't using the dockerized sql server?

2025-01-03 16:18 UTC, JNygaard-Skylight requested changes

2025-01-03 16:18 UTC, JNygaard-Skylight commented on containers/ecr-viewer/package.json
Can the Cypress commands be removed?

2025-01-03 16:18 UTC, JNygaard-Skylight commented on containers/ecr-viewer/playwright.config.ts
> +    /* Test against mobile viewports. */
If we're not likely to use these the comments should be removed.

2025-01-03 16:42 UTC, JNygaard-Skylight requested changes
Could you add some documentation on how to run the Playwright tests in a readme?

2025-01-03 20:56 UTC, mcmcgrath13 commented on .github/workflows/container-ecr-viewer.yaml
> +        run: npm run convert-seed-data
could we limit this to a smaller number of ecrs to save time?

2025-01-06 14:08 UTC, BobanL commented on .github/workflows/container-ecr-viewer.yaml
> +        run: npm run convert-seed-data
I think that's a little out of scope for this work now since it would impact the seed script file. We do have some [exiting tech debt](https://github.com/CDCgov/phdi/issues/2689) that would handle this.

2025-01-06 16:10 UTC, BobanL commented on containers/ecr-viewer/docker-compose.yml
> +      - SQL_SERVER_HOST=sqlserver
https://github.com/CDCgov/phdi/pull/3100 should resolve the issue.

2025-01-06 16:43 UTC, mcmcgrath13 commented on containers/ecr-viewer/docker-compose.yaml
> +      - SQL_SERVER_HOST=sqlserver
undo this as well

2025-01-06 16:45 UTC, mcmcgrath13 commented on containers/ecr-viewer/README.md
> +Unit tests utilize Jest as the test runner. [Jest-axe](https://github.com/nickcolley/jest-axe) provides basic accesibility utilities and [React testing library](https://testing-library.com/docs/react
the tests seem to assume that only the `LA` folder is seeded into the database. Should that assumption be documented and also checked somehow?

2025-01-06 19:44 UTC, mcmcgrath13 commented on containers/ecr-viewer/README.md
> +1. `npm run convert-seed-data:build` to save all required eCRs necessary for e2e tests. The tests require all eCRs located in `/seed-scripts/baseECR/LA` have been saved.
```suggestion
1. `npm run convert-seed-data:build` to save all required eCRs necessary for e2e tests. The tests require all eCRs located in `/seed-scripts/baseECR/LA` have been saved (and no other eCRs).
```

2025-01-06 19:52 UTC, JNygaard-Skylight approved these changes
LGTM!

2025-01-08 13:27 UTC, merged