chore: replace pretty-format-json with prettier functionality
CDCgov/phdi pull request #3090
Opened 2024-12-26 22:07 UTC by BobanL

# PULL REQUEST

## Summary
- Replace pretty-format-json with prettier functionality
- Remove auto update from pre-commit because eslint and prettier are at the latest supported versions
- Remove terraform formatting because we don't have any tf in the project
- pin eslint and prettier to the latest supported versions.
  - Nextjs 14 does not support eslint 9
  - Pre-commit doesn't play nice with prettier 4+
  -  
## Related Issue
Fixes #

## Acceptance Criteria
Please copy the acceptance criteria from your ticket and paste it here for your reviewer(s)

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

2025-01-03 20:45 UTC, JNygaard-Skylight requested changes
This looks good to me, just a small question on whether we can keep the autoupdate, and have it ignore the two hooks we want to update. If not that's fine by me.

2025-01-03 20:45 UTC, JNygaard-Skylight commented on .pre-commit-config.yaml
> -  autoupdate_branch: ""
Is there a way to keep the autoupdate on, but have it ignore the pre-commit hooks we want to lock?

2025-01-06 12:32 UTC, BobanL commented on .pre-commit-config.yaml
> -  autoupdate_branch: ""
I actually don't think there is a way to disable auto update... The defaults are to always update once a week. 
https://pre-commit.ci/#configuration-autoupdate_branch.

I'll just put it back in.

2025-01-06 19:44 UTC, JNygaard-Skylight approved these changes
LGTM!

2025-01-06 20:10 UTC, merged