Linkage split
CDCgov/phdi pull request #31
Opened 2022-08-24 21:43 UTC by KennethSkylight

Instead of having one linkage module that loops through a bundle, we are splitting out the loop and the resource level modifications. 

That way, a user can perform resource level linkage if they prefer that.

2022-08-29 20:55 UTC, bamader requested changes
The idea of giving the user more flexibility for doing resource- or bundle-level work is definitely an important one, and we should get that change implemented for sure. However, in other areas of the code base, the way we've implemented this is by having functions that are input-agnostic (i.e. don't reference `by_bundle` or `by_resource` in their title) and just type-check the data they're given. I'd like to see this code follow that same convention so that we keep things standardized and aligned (check out `fhir/harmonization` for some examples on handling bundle vs resource. I think that type-checking logic and handling could largely be straight copied here).

2022-08-31 12:35 UTC, spencer-skylight reviewed
Just a few nit-picky suggestions.

2022-08-31 12:35 UTC, spencer-skylight commented on tests/fhir/linkage/test_fhir_link.py
> +def test_add_patient_identifier_by_bundle():
Could you add a few test cases where `overwrite=False` for the 2 functions?

2022-08-31 12:35 UTC, spencer-skylight commented on tutorials/linkage-tutorial.md
> +To add patient identifiers to the bundle, you can use the `add_patient_identifier_by_bundle` function in the FHIR linkage package
Nit: First off, nice job catching the linkage documentation updates. Could we work in to the docs that add_patient_identifier also exists to add an identifier at the patient resource level? I don't think it needs an example - just a sentence mention.

2022-08-31 12:56 UTC, bamader requested changes
We're almost there, just two changes (and ripples of those changes in a couple places) requested:
1. more appropriate name for the bundle function
2. making the `add_identifier` function (for resources) actually accept a resource, rather than a dict with a `resource` key

2022-08-31 12:56 UTC, bamader commented on phdi/fhir/linkage/link.py
> +) -> dict:
Can we rename this to either `add_patient_identifier_to_bundle` or `add_patient_identifier_in_bundle` (your choice)? `_by_` isn't the right descriptor of this to me--it feels off, and while we are technically separating functions by resource and by bundle, that naming convention doesn't work because we're not calling the other function `by_resource` so the rationale is masked from the user. IMO, `_in_` or `_to_` are more descriptive, more appropriate for what's actually happening in the function (all patients _in_ the function are having IDs added _to_ them), and better matches the naming convention that we'll use for other split functions (such as `standardize_names_in_bundle` or `geocode_addresses_in_bundle`).

2022-08-31 12:56 UTC, bamader commented on phdi/fhir/linkage/link.py
> -        patient = resource.get("resource")
This line should stay in the function. Because `resource` at this point isn't an actual FHIR-formatted resource (just a dictionary with a `resource` key), we shouldn't be calling it one or passing it into the `add_patient_identifier` function as a resource. Rather, we should actually get the patient resource here and then pass the extracted resource into the function.

2022-08-31 12:56 UTC, bamader commented on phdi/fhir/linkage/link.py
> +    patient = resource.get("resource")
This line shouldn't need to exist within this function. The function should already be given a patient resource, rather than a dictionary holding a patient resource inside one of its keys. See comment above about moving the logic to the for-loop. This is also important to make sure that our functions behave the way users would expect them to, both from how we're naming them and using docstrings (which indicates that the input `resource` actually _is_ a FHIR resource) and from an intuition perspective.

2022-08-31 12:56 UTC, bamader commented on phdi/fhir/linkage/__init__.py
> +__all__ = ["add_patient_identifier_by_bundle", "add_patient_identifier"]
Will need changed to reflect name change (see comment in `linkage/link.py`)

2022-08-31 12:56 UTC, bamader commented on tests/fhir/linkage/test_fhir_link.py
> +            add_patient_identifier(resource, salt_str, True)
Will need to be modified to receive the `resource.get("resource")` extraction

2022-08-31 12:56 UTC, bamader commented on tutorials/linkage-tutorial.md
> +To add patient identifiers to the bundle, you can use the `add_patient_identifier_by_bundle` function in the FHIR linkage package
Just marking in the one place, but will need to be modified to reflect the changed name

2022-09-06 16:06 UTC, KennethSkylight commented on tutorials/linkage-tutorial.md
> +To add patient identifiers to the bundle, you can use the `add_patient_identifier_by_bundle` function in the FHIR linkage package
Added

2022-09-06 16:07 UTC, KennethSkylight commented on phdi/fhir/linkage/link.py
> +) -> dict:
changed

2022-09-06 16:12 UTC, KennethSkylight commented on phdi/fhir/linkage/link.py
> -        patient = resource.get("resource")
nice catch, I also changed the name per Spencer's comment

2022-09-06 16:12 UTC, KennethSkylight commented on phdi/fhir/linkage/link.py
> +    patient = resource.get("resource")
Changed

2022-09-06 16:13 UTC, KennethSkylight commented on phdi/fhir/linkage/__init__.py
> +__all__ = ["add_patient_identifier_by_bundle", "add_patient_identifier"]
changed

2022-09-06 16:14 UTC, KennethSkylight commented on tests/fhir/linkage/test_fhir_link.py
> +            add_patient_identifier(resource, salt_str, True)
changed

2022-09-06 16:14 UTC, KennethSkylight commented on tutorials/linkage-tutorial.md
> +To add patient identifiers to the bundle, you can use the `add_patient_identifier_by_bundle` function in the FHIR linkage package
changed

2022-09-06 17:07 UTC, KennethSkylight commented on tests/fhir/linkage/test_fhir_link.py
> +def test_add_patient_identifier_by_bundle():
Spencer and I talked and we are moving this to a different PR

2022-09-07 12:19 UTC, bamader approved these changes
LGTM! If the decision to open those other test cases is going to be for another PR, let's get a ticket created marking that as a fast follows item so that we don't lose track of that work.

2022-09-07 13:05 UTC, spencer-skylight approved these changes
Looks good!

I added the test case documentation to an existing ticket we had to update unit tests:
https://app.clickup.com/t/3g9pbgz

2022-09-07 14:53 UTC, merged