Transport module fhir export
CDCgov/phdi pull request #32
Opened 2022-08-24 22:36 UTC by spencer-skylight

# Description
Migrate export-related functionality from the old FHIR module to the new taxonomy in accordance with the [PRD](https://docs.google.com/document/d/1Jzc8KG6idkap6njacoD_Cdqm5fN03LTYslIEhtK9UL8/edit).

In addition to the taxonomy migration, the following changes were made:
* In `phdi.fhir.cloud.azure` function `download_from_export_response` (and helper), expect an AzureCredentialManager to be supplied by the caller, and use it to log in. (and unit tests updated accordingly)
* Minor updates to docstrings.
* Removed logging calls
  * Debug and info
  * Exception logging where we are also raising an exception

2022-08-25 13:10 UTC, bamader requested changes
Looks like a good port, just a couple of formatting / organizational nits to take care of before merging!

2022-08-25 13:10 UTC, bamader commented on phdi/fhir/cloud/azure.py
> +    cred_manager: AzureCredentialManager,
Since we have a `BaseCredentialManager` and are moving away from defining just the Azure specific implementation, can we make this the base class instead? And for that matter, how much of a lift would it be to make this code generic for anything with a credential manager? Looking at some of the below functions, nothing seems particularly specific to Azure (since we just invoke a common member function `.get_credential_object()` on line 47), so could we just rename this whole file something more suitably generic?

2022-08-25 13:10 UTC, bamader commented on phdi/fhir/transport/__init__.py
> +from .export import export_from_fhir_server
Absolute path

2022-08-25 13:10 UTC, bamader commented on phdi/fhir/transport/export.py
> +from .http import http_request_with_reauth
absolute import

2022-08-25 13:10 UTC, bamader commented on phdi/fhir/transport/export.py
> +def __export_from_fhir_server_poll_call(
Can we make this one underscore in front of the function instead of two? I know it's a helper for other helpers but let's standardize it so that underscore functions lead with only one.

2022-08-25 13:10 UTC, bamader commented on phdi/fhir/transport/export.py
> +) -> str:
Small organizational nit: let's put all the functions with underscores at the bottom of the file, so that all the publicly exposed functions a user can call and might want to read more about are at the top of the file in one group and all the private helpers are all together in another group below that.

2022-08-25 19:49 UTC, spencer-skylight commented on phdi/cloud/azure.py
> +
Nope - I'll remove.

2022-08-25 19:51 UTC, spencer-skylight commented on phdi/fhir/cloud/__init__.py
> +from .azure import download_from_fhir_export_response
Updated.

2022-08-25 19:55 UTC, spencer-skylight commented on phdi/fhir/cloud/azure.py
> +    cred_manager: AzureCredentialManager,
If this were itself defined in, or implementing a base class, I'd agree.  But since this is an Azure-specific function and it requires the return value of `get_credential_object()` to be an Azure credential manager not just any "credential object", I think putting the more specific type here makes sense.  

Does that explanation sway you?  Is it OK to leave this as is?

2022-08-25 19:56 UTC, spencer-skylight commented on phdi/fhir/transport/__init__.py
> +from .export import export_from_fhir_server
I'll update this.

2022-08-25 19:56 UTC, spencer-skylight commented on phdi/fhir/transport/export.py
> +from .http import http_request_with_reauth
Will update.

2022-08-25 19:58 UTC, spencer-skylight commented on phdi/fhir/transport/export.py
> +def __export_from_fhir_server_poll_call(
Sure, I can do that. We don't have any guidance around when to use 1 vs 2. I'll keep it standard unless/until we do.

2022-08-25 19:59 UTC, spencer-skylight commented on phdi/fhir/transport/export.py
> +) -> str:
Sure, I'll update.

2022-08-29 18:23 UTC, bamader commented on phdi/fhir/cloud/azure.py
> +    cred_manager: AzureCredentialManager,
Ah that makes sense. Yes I think this is totally fine to leave as-is then. Thanks for clarifying.

2022-08-29 18:27 UTC, bamader approved these changes
LGTM!

2022-08-29 18:50 UTC, merged