Postgres implementation of MPI connector
CDCgov/phdi pull request #323
Opened 2023-03-20 22:56 UTC by m-goggins

This PR creates the Postgres implementation of an MPI connector. The postgres implementation has two main functions and 1 helper function:

- `block_data`: returns blocks of data from the patient table as specified by the user-provided `block_data` dictionary
- `upsert_patient_match`: updates patient and person tables depending on whether a match was found or not
- `_generate_block_query`: generates a Postgres/JSONB specific query for retrieving blocks of data. This one will likely need to be modified for the specific key, values we allow users to query with as the current query generator only goes 1 level deep and could be further specified for the `patient_resource` such that it knows how to generate a query for zip code, for example. 

I tested all of the functions locally and Nick C helped me with the GH actions for testing. The SQL is a bit of a mess, especially with regard to the UUIDs and JSONB formatting, but I wanted to get this out for review sooner rather than later.

2023-03-22 19:50 UTC, emmastephenson reviewed
Overall this is looking great, thanks Marcelle! Just a couple of questions.

2023-03-22 19:50 UTC, emmastephenson commented on phdi/linkage/postgres.py
> +            self.connection = psycopg2.connect(
We may want to open and close this connection at the start of a given function call, rather than leaving it permanently open. I'm a little concerned that by using a single connection for every function call, we'd run into issues around throttling or locking rows (or hitting our max connection limits if we have multiple instances running).

2023-03-22 19:50 UTC, emmastephenson commented on phdi/linkage/postgres.py
> +                + f"""VALUES ('{patient_resource.get("id")}', '{person_id}', """
Is the patient resource ID guaranteed to be a UUID?

2023-03-22 19:50 UTC, emmastephenson commented on tests/linkage/test_postgres_mpi_connector.py
> +def test_postgres_connection():
Will these tests pass locally without a postgres database stood up? Or are they intended to only run within the Github action?

2023-03-22 20:04 UTC, bamader requested changes
The dictionaries of commands and SQL curly bracketed stuff is making my eyes bleed 😭 🤮 . Major props to you for putting this altogether. I had a couple questions about turning the blocked data into LoLs and a big discussion point around external person ID that I think Dan and Brady should weigh in on, but otherwise this is so promising to see 💪

2023-03-22 20:05 UTC, BradySkylight commented on phdi/linkage/postgres.py
> +            self.connection = psycopg2.connect(
This is a good point, but not sure if the connection is the issue or if the cursor matters.  We need to make sure to close the cursors after each operation is completed.  I haven't worked on DB connections in python so much, but typically we would have a db connection factory in Java which managed the connections.  I wonder if there is some way to do that in python.  I'll do some digging..

2023-03-22 20:10 UTC, BradySkylight commented on phdi/linkage/postgres.py
> +
I'm not sure, based upon the very little of what I've read about psycopg2, if we need to close the cursors manually or not....but it may just be a good practice to close them once the query has completed what it needs to do.

2023-03-22 20:10 UTC, BradySkylight commented on phdi/linkage/postgres.py
> +
I'm not sure, based upon the very little of what I've read about psycopg2, if we need to close the cursors manually or not....but it may just be a good practice to close them once the query has completed what it needs to do.

2023-03-22 20:17 UTC, BradySkylight commented on phdi/linkage/postgres.py
> +        the patient table and updates the person table to link to the new patient; else
Based upon our model, this comment should change.  I know I was the one who helped come up with this note, so I take full responsibility here.  

"If a matching person ID has been found in the MPI, inserts a new patient into the patient table with the provided person ID; else inserts a new person into the person table and inserts a new patient with the new personID, from the newly created person record, linking the new person with the new patient."

2023-03-22 20:18 UTC, BradySkylight commented on phdi/linkage/postgres.py
> +        the patient table and updates the person table to link to the new patient; else
Probably should update the comment in the Base class as well.

2023-03-22 20:19 UTC, BradySkylight commented on phdi/linkage/postgres.py
> +                + f"""VALUES ('{patient_resource.get("id")}', '{person_id}', """
Yes, it is.  Should we have two columns for patientid, like a patient_id that is the UUID in postgres, and another that contains the FHIR Patient Identifier (resource id) (maybe name the column 'patient_resource_id')?

2023-03-22 20:23 UTC, BradySkylight commented on phdi/linkage/postgres.py
> +            self.connection.commit()
Are commit's required for select statements?  We may just need to fetch the results, as you are doing below.  Again, new to the postgres python package, so just checking.

2023-03-22 20:25 UTC, BradySkylight commented on phdi/linkage/postgres.py
> +            person_id = self.cursor.fetchall()
Theoretically, there should only be one result returned.  Should we have a check around this or a looping mechanism to ensure there is only one record?  If not, and we let the DB handle the errors by preventing duplicates, that would be fine too, but we will just need to make sure there is a constraint on the table to ensure this.  We could just use cursor.fetchone() as well, if we are going to allow the DB to manage handling duplicates.

2023-03-22 20:32 UTC, BradySkylight commented on phdi/linkage/postgres.py
> +            ]
Nice!  I see the TODO above, but at least this is a good start!

2023-03-22 20:35 UTC, BradySkylight commented on tests/linkage/test_postgres_mpi_connector.py
> +    postgres_client.connection.close()
I like the table creation functions and the clean-up here.  Sweet!

2023-03-22 20:36 UTC, BradySkylight requested changes
Looks good overall! A few questions which may result in some changes.  I'm open/willing to discuss in more detail if needed/desired.

2023-03-22 20:45 UTC, m-goggins commented on phdi/linkage/postgres.py
> +                + f"""VALUES ('{patient_resource.get("id")}', '{person_id}', """
Yep, I based if off the [tables.ddl](https://github.com/CDCgov/phdi/blob/main/phdi/linkage/tables.ddl)

2023-03-22 20:51 UTC, m-goggins commented on phdi/linkage/postgres.py
> +    """
Oops, good call.

2023-03-22 20:54 UTC, m-goggins commented on phdi/linkage/postgres.py
> +        person_table: str,
Correct! Initially, I didn't think it should be required for the class, but if it's not specified here, the user has to specify the tables in the underlying methods (e.g., specify patient table name for `block_data`). I can see it both ways if you think we shouldn't make it required for the class so I'm okay to change if others want to.

2023-03-22 21:02 UTC, m-goggins commented on phdi/linkage/postgres.py
> +            blocked_data[0].append(key)
It works exactly like the last sentence you wrote for #1! 

I do think you're right about point 2. We should implement some kind of check to make sure the data are returned in the same order. Sorting the keys alphabetically would be a low lift to implement.

2023-03-22 21:04 UTC, emmastephenson commented on phdi/linkage/postgres.py
> +            self.connection = psycopg2.connect(
Yep, this is exactly what I'm thinking Brady! That's the pattern I'm used to as well - there's a factory to handle all these transactions for you, so you can just say `execute query` and the factory will handle setting up the connection, closing it at the end of the transaction, handling retries, etc.

2023-03-22 21:08 UTC, m-goggins commented on phdi/linkage/postgres.py
> +            self.connection = psycopg2.connect(
Oh yeah, that's a really good point that I forgot to return to and I manually close the connection in the tests so it didn't come back as an issue. 

In this case, it would move the connection out of the class and into a separate factory method, right?

2023-03-22 21:11 UTC, m-goggins commented on phdi/linkage/postgres.py
> +
I'm pretty sure when you close the connection, the cursor is also closed but I'm also new to psycopg2 so I could be wrong.

2023-03-22 21:11 UTC, m-goggins commented on phdi/linkage/postgres.py
> +
ditto above

2023-03-22 21:16 UTC, emmastephenson commented on phdi/linkage/postgres.py
> +
+1 to this Brady - I think we can [close them manually](https://www.psycopg.org/docs/cursor.html#cursor.close), so we probably should.

2023-03-22 21:18 UTC, m-goggins commented on phdi/linkage/postgres.py
> +            self.connection.commit()
I think you're correct; we don't need it for select statements since we're not changing anything in the table (so wouldn't need to roll back).

2023-03-22 21:22 UTC, m-goggins commented on phdi/linkage/postgres.py
> +            person_id = self.cursor.fetchall()
Good call. I do think we want to check to make sure that only 1 result is returned. I hesitate to use fetchone() though. If there is more than 1 result, it doesn't seem like[ fetchone()](https://www.psycopg.org/docs/cursor.html?highlight=fetchone#cursor.fetchone) orders the results in a particular way. And if there is more than one result, I think we should alert the user to an error. What do you think about raising an exception here?

2023-03-22 21:25 UTC, m-goggins commented on tests/linkage/test_postgres_mpi_connector.py
> +    )
@emmastephenson asked about this same thing so I can put together some documentation. It's pretty simple but would be good to have written down somewhere. Where would be an appropriate place for the write up?

2023-03-22 21:29 UTC, emmastephenson commented on phdi/linkage/postgres.py
> +            self.connection = psycopg2.connect(
That's what I'm thinking Marcelle. If we don't want to bother with a factory yet we could also manage the opening and closing manually within this class; just moving the connection setup into the methods instead of at class instantiation and closing both connections and cursors before the method returns.
The psycopg library also seems to support [context managers](https://www.psycopg.org/docs/connection.html?highlight=connection#connection:~:text=Connections%20can,for%20several%20contexts.), if we wanted to go that route instead.

2023-03-22 21:29 UTC, m-goggins commented on phdi/linkage/postgres.py
> +                + f"VALUES ('{patient_resource.get('id')}');"
Ah I think I misunderstood the ddl file then. I thought that the `person.external_person_id` should correspond to the `patient.patient_id` in the patient table and to the patient's FHIR ID. 

I only inserted so that I can retrieve the newly created `person_id` as you point out in another comment. 

Definitely want to get on the same page about this.

2023-03-22 21:30 UTC, emmastephenson commented on tests/linkage/test_postgres_mpi_connector.py
> +    )
@m-goggins in the new DIBBs wiki would be great! 😄 https://github.com/CDCgov/phdi/wiki/Local-Development

2023-03-22 21:38 UTC, m-goggins commented on phdi/linkage/postgres.py
> +            self.connection.commit()
Will the FHIR's patient ID be the same every time for the same patient?

2023-03-22 21:40 UTC, m-goggins commented on phdi/linkage/postgres.py
> +            )
Will the FHIR patient resource id be the same every time for the same patient? I think this goes to Brandon's comment in the internal channel as to whether we should use the resource id as the `patient_id` and whether that will be consistent over time.

2023-03-22 22:11 UTC, m-goggins commented on tests/linkage/test_postgres_mpi_connector.py
> +    )
Updated with directions

2023-03-23 12:47 UTC, bamader commented on phdi/linkage/postgres.py
> +                + f"""VALUES ('{patient_resource.get("id")}', '{person_id}', """
I would say we don't need a separate patient_resource_id column, personally. That information is very easily accessed just using a JSON query in the patient resource itself, and we deliberately structured our tables to lean and small to get this started. Let's not start adding more columns quite yet 😅

2023-03-23 12:50 UTC, bamader commented on tests/linkage/test_postgres_mpi_connector.py
> +def test_postgres_connection():
Yeah Emma's comment gets at what I was talking about with some small documentation additions around testing this locally. Without setting up a container with that postgres image, you'll never get a successfully running `pytest` from the root test directory, which is imo an important thing to be able to see for large scale refactors or code work. I don't mind that the tests require a DB set up locally, but I do think a little paragraph (maybe in the readme somewhere under testing?) about configuring the docker container and its DB image would be good.

2023-03-23 12:50 UTC, bamader commented on phdi/linkage/postgres.py
> +        person_table: str,
No strong opinions on my part! If nobody else comments on this I say we leave as is.

2023-03-23 12:53 UTC, bamader commented on phdi/linkage/postgres.py
> +            self.connection.commit()
I don't think that's guaranteed, no. If two patients come in that are super similar to each other but have a typo'ed letter off, the FHIR server won't recognize them as the same on its own so they'll get different IDs. And if two patient records really are the same, because we standardize and link before we store back to the FHIR server, I don't know if the FHIR IDs will always match up pre-linkage anyway.

2023-03-23 12:57 UTC, bamader commented on phdi/linkage/postgres.py
> +                + f"VALUES ('{patient_resource.get('id')}');"
For sure. In the ideal world, I would say we want to insert null or none into the external ID, because that's the truest reflection of what that column in the table is supposed to hold--for a patient that's new and has just come in, it _won't_ yet be in another database, so it shouldn't have an external ID. Based on my quick google search, it looks like we can do that while still getting the ID of the thing we just created using something called a Returning Clause, https://www.postgresql.org/docs/8.3/sql-insert.html (ctrl+F returning). https://stackoverflow.com/questions/2143379/returning-a-value-with-psycopg2

2023-03-23 12:57 UTC, bamader commented on phdi/linkage/postgres.py
> +            person_id = self.cursor.fetchall()
Looks like psycopg2 supports returning clauses so we can use those

2023-03-23 12:58 UTC, bamader commented on phdi/linkage/postgres.py
> +            person_id = self.cursor.fetchall()
I have the same hesitation you do Marcelle so I like your suggestion of using fetchall but raising an exception if there's more than 1.

2023-03-23 13:23 UTC, DanPaseltiner commented on phdi/linkage/postgres.py
> +                + f"""VALUES ('{patient_resource.get("id")}', '{person_id}', """
@emmastephenson for context the FHIR converter creates UUIDs for all of the FHIR resources it generates. We are going to use this ID from the patient resource as the ID in the MPI.

2023-03-23 15:29 UTC, BradySkylight commented on phdi/linkage/postgres.py
> +            )
Into the Person table though?  A patient table insert every time, yes, but not a person insert unless the patient doesn't find a match.

2023-03-23 15:37 UTC, DanPaseltiner commented on phdi/linkage/postgres.py
> +            )
yes!

2023-03-24 14:51 UTC, BradySkylight approved these changes
Approving, based upon our conversation we had yesterday.  Pending final updates and tests.  Excellent work on this!

2023-03-24 18:37 UTC, BradySkylight approved these changes
Nice updates!  Great work on this!  LGTM

2023-03-24 20:01 UTC, emmastephenson approved these changes
This looks great! Thanks for all your hard work here, Marcelle!

2023-03-24 20:52 UTC, merged