Conversion docs
CDCgov/phdi pull request #34
Opened 2022-08-30 18:33 UTC by KennethSkylight

This is the docs for conversion. The text is temporary as we figure out how to get STLTs signed up for FHIR server. When we figure that out, these docs will be reworked

2022-08-31 16:53 UTC, spencer-skylight requested changes
Thanks Kenneth! I've got a few cleanup suggestions on this one.

2022-08-31 16:53 UTC, spencer-skylight commented on tutorials/conversion-tutorial.md
> +yourCreds = {...}
This actually isn't necessary, as currently written.  Our implementation leverages the DefaultAzureCredential which can resolve credentials a few ways.  When running this code from Azure cloud resources, this is often part of the service configuration. When running locally, we usually use the `az login` CLI script which sets credentials at the environment level, and is then automatically resolved.  

I'd suggest adding a sentence above this, like: 
Ensure that you are logged in to Azure so that your credentials are recognized by the credential manager.  For more information, see cloud-tutorial.md (yet to be written, but this should link to that filename in the same directory).

2022-08-31 16:53 UTC, spencer-skylight commented on tutorials/conversion-tutorial.md
> +message = "...the HL7 data above..."
In the interest of ease-of-cut-paste, could you rewrite so we don't put the HL7 message content in its own block above, but just include it here, something like this:

```python 
from phdi.fhir.conversion import convert_to_fhir

message = """MSH|^~\&|ADT1|GOOD HEALTH HOSPITAL|GHH LAB, INC.|GOOD HEALTH HOSPITAL|198808181126|SECURITY|ADT^A01^ADT_A01|MSG00001|P|2.8||
EVN|A01|200708181123||
PID|1||PATID1234^5^M11^ADT1^MR^GOOD HEALTH HOSPITAL~123456789^^^USSSA^SS||EVERYMAN^ADAM^A^III||19610615|M||C|2222 HOME STREET^^GREENSBORO^NC^27401-1020|GL|(555) 555-2004|(555)555-2004||S||PATID12345001^2^M10^ADT1^AN^A|444333333|987654^NC|
NK1|1|NUCLEAR^NELDA^W|SPO^SPOUSE||||NK^NEXT OF KIN
PV1|1|I|2000^2012^01||||004777^ATTEND^AARON^A|||SUR||||ADM|A0|"""
url = "https://azure_fhir_url.com"
```

2022-08-31 16:53 UTC, spencer-skylight commented on tutorials/conversion-tutorial.md
> +```
Introduce this as a python block by using 
````
```python
````

2022-08-31 16:53 UTC, spencer-skylight commented on tutorials/conversion-tutorial.md
> +credManager = AzureCredentialManager(url, yourCreds)
We should use variable naming conventions here - should be `cred_manager`

2022-09-06 17:24 UTC, KennethSkylight commented on tutorials/conversion-tutorial.md
> +```
added

2022-09-06 17:24 UTC, KennethSkylight commented on tutorials/conversion-tutorial.md
> +credManager = AzureCredentialManager(url, yourCreds)
changed

2022-09-06 17:25 UTC, KennethSkylight commented on tutorials/conversion-tutorial.md
> +message = "...the HL7 data above..."
changed

2022-09-06 17:27 UTC, KennethSkylight commented on tutorials/conversion-tutorial.md
> +Currently, the solution depends on having your own Azure FHIR server to convert HL7 v2 or CCDA to FHIR.
changed

2022-09-06 17:28 UTC, KennethSkylight commented on tutorials/conversion-tutorial.md
> +In the design of our building blocks, we have modules to be used specifically with the FHIR data type.
Added.

2022-09-06 17:30 UTC, KennethSkylight commented on phdi/fhir/conversion/README.md
> +FHIR Conversion helps convert HL7 v2 or CCDA (XML) data into FHIR (JSON) data. Our library works well with FHIR so this package helps bridge the gap between other healthcare data types and FHIR. A me
Changed

2022-09-06 17:32 UTC, KennethSkylight commented on tutorials/conversion-tutorial.md
> +yourCreds = {...}
Ok I added your new sentence. Could you check if this code example still makes sense?

2022-09-07 13:09 UTC, spencer-skylight approved these changes
LGTM :+1:

2022-09-07 14:59 UTC, merged