Add coverage guidelines
CDCgov/phdi pull request #36
Opened 2022-08-31 20:21 UTC by bamader

This PR adds coverage guidelines to the `contributing.md` file based on the robustness conversation the SDK workstream had earlier this week. Principles are suggested for when tests are appropriate, what cases they should be validating, and howe we use and regard the resulting coverage percentage.

2022-08-31 20:22 UTC, bamader commented
Ann doesn't have a Github account I can request review from, but it might be worth getting her eyes on this as well since robustness assurances are something that could impact usability or comms to STLTs.

2022-09-01 20:30 UTC, spencer-skylight requested changes
A few suggestions for consideration.  I think I'd be OK if this was merged as-is so I'm approving, but please consider the comments I left as well.

2022-09-01 20:30 UTC, spencer-skylight commented on CONTRIBUTING.md
> +1. **We strive for 80% repository coverage at all times.** There's no magic number when it comes to assessing coverage quality. A high coverage percentage doesn't actually guarantee high-quality test
What do you think about striving for 85%?  We are at 95% now, and may go higher when we revise our test cases.  If we start dipping near 85% we can always lower, but 85 seems like a good time to start discussing and revising.

2022-09-01 20:30 UTC, spencer-skylight commented on CONTRIBUTING.md
> +2. **Any public-facing functions should include at least one test case.** If a user can call function, we want that function to have documented test coverage. Ideally, functions should have multiple
I researched this yesterday and couldn't find an easy way to check this in an automated way.  I'm thinking we should group this with the other guidelines in point 4 below.  Does that make sense to you as well?

2022-09-01 20:38 UTC, bamader commented on CONTRIBUTING.md
> +1. **We strive for 80% repository coverage at all times.** There's no magic number when it comes to assessing coverage quality. A high coverage percentage doesn't actually guarantee high-quality test
Sure, I've got no problem with 85% (I think that's what I threw out in our meeting anyway). I feel like I just went with 80% because I read the extra credit article and mentally was like "well let's just take the average between a perfect 100 and the 60 that google uses" lol

2022-09-01 20:41 UTC, bamader commented on CONTRIBUTING.md
> +2. **Any public-facing functions should include at least one test case.** If a user can call function, we want that function to have documented test coverage. Ideally, functions should have multiple
Looking at the way I've organized this, I actually think this content belongs where it is. I was trying to develop an organizational scheme where the first three points were our sort of "governing principles," if you will, which were more like abstract ideas and concepts we were striving to uphold when writing tests and considering coverage. Point 4, on the other hand, is intended to be a more specific "actionable" point that helps developers understand what practical / real tests to be writing. In reading it again, that organization comes across to me but I think only because I was the one who wrote it (i.e. I didn't actually explicitly call that out). If you agree with the organization, I could separate point 4 out into a new paragraph rather than the bulleted list and add a sentence about how these are our practical and actionable test guidelines?

2022-09-01 20:48 UTC, spencer-skylight commented on CONTRIBUTING.md
> +2. **Any public-facing functions should include at least one test case.** If a user can call function, we want that function to have documented test coverage. Ideally, functions should have multiple
Sure sounds good to me to keep this separated out.  I like point 4 as a bullet list - I think it's easier to scan/read that way.  Maybe you could just add a short sentence above the bullet list?

2022-09-01 20:49 UTC, spencer-skylight approved these changes
I think we've worked out everything... Approving!

2022-09-01 21:12 UTC, bamader commented on CONTRIBUTING.md
> +2. **Any public-facing functions should include at least one test case.** If a user can call function, we want that function to have documented test coverage. Ideally, functions should have multiple
Done!

2022-09-01 21:15 UTC, merged