pre extract push
CDCgov/phdi pull request #377
Opened 2023-04-04 12:13 UTC by bamader

# PULL REQUEST

## Summary
What changes are being proposed?

## Related Issue
Fixes #

## Additional Information
Anything else the review team should know?

[//]: # (PR title: Remember to name your PR descriptively!)

2023-04-04 22:54 UTC, emmastephenson reviewed
This looks awesome Brandon! Just a few minor comments, but great work!

2023-04-04 22:54 UTC, emmastephenson commented on phdi/linkage/link.py
> +      "transformation" key whose value is one of our supported tranforms.
```suggestion
      "transformation" key whose value is one of our supported transforms.
```

2023-04-04 22:54 UTC, emmastephenson commented on phdi/linkage/link.py
> +    for person_id in linkage_scores:
I think this function could be simplified down to:
```
best_person = max(linkage_scores, key=linkage_scores.get)
return best_person
```

2023-04-04 22:54 UTC, emmastephenson commented on tests/linkage/test_linkage.py
> +def test_link_record_against_mpi():
This test looks great, but it feels a bit more like an e2e or integration test than a unit test for the linkage test with the PostgresMPI implementation. Any chance there's a specific sub-folder or different file for those kinds of tests?

2023-04-05 14:14 UTC, DanPaseltiner requested changes
This is pretty righteous. I do think that we should pass in an MPI client instead of building it inside `link_record_against_mpi`. I don't think this function should be responsible for instantiating MPI clients given DB connection details, or selecting the appropriate client to use if we eventually support multiple MPIs in the future.

2023-04-05 14:14 UTC, DanPaseltiner commented on phdi/linkage/link.py
> +def _group_patient_block_by_person(data_block: List[list]):
nit: missing return type hint.

2023-04-05 15:32 UTC, bamader commented on phdi/linkage/link.py
> +    )
Yeah definitely agree here. I like the suggestion of not making it the responsibility of the linking function to instantiate a client, so I'll make it just accept one as a parameter.

2023-04-05 15:36 UTC, bamader commented on phdi/linkage/link.py
> +        # element as the one that should be used with the record.
Yep will do!

2023-04-05 15:45 UTC, bamader commented on phdi/linkage/link.py
> +        # element as the one that should be used with the record.
Lol I wound up thinking of a way to efficiently solve this problem too, so I noted that in the ticket. Turns out when you structure your code efficiently/modularized, you only have to change a small helper to get this result.

2023-04-05 15:50 UTC, emmastephenson commented on tests/linkage/test_linkage.py
> +def test_link_record_against_mpi():
Agreed, I'm fine to punt on it for now. Would you mind adding a TODO in the code to move the test to an integration test suite later?

2023-04-05 15:59 UTC, bamader commented on phdi/linkage/link.py
> +    for person_id in linkage_scores:
Woah didn't know max could take a key param!

2023-04-05 16:04 UTC, DanPaseltiner approved these changes
Looks like we are on the same page about a few minor tweaks we should make before merging. I'll approve now so I'm not blocking.

2023-04-05 16:23 UTC, merged