rename find_resource_by_type to find_entry_by_resource_type
CDCgov/phdi pull request #42
Opened 2022-09-07 16:26 UTC by m-goggins

Renamed find_resource_by_type to find_entry_by_resource_type to better articulate the function returning a list of resources within entries by resource type.

Newbie question: In the FHIR documentation it says that an entry can have a resource _or information_. I haven't been able to find any examples of bundles without resources but could this function error on an entry in a bundle that only has information (and therefore no resourceType)?

From https://build.fhir.org/bundle.html:
`"[entry](https://build.fhir.org/bundle-definitions.html#Bundle.entry)" : [{ // [Entry in the bundle - will have a resource or information](https://build.fhir.org/terminologies.html#unbound)`

2022-09-07 18:10 UTC, bamader requested changes
I like this change, good call to add it in. Could we actually make the function named `find_entries_by_resource_type` (pluralizing entry)? Reading the change, I'm realizing we should've made it plural a long time ago since it returns a list, so if we're going to do a name refactor we might as well correct that now.

2022-09-07 18:13 UTC, bamader commented
Regarding your newbie question in FHIR structure: this is a good question, but thankfully I think one that doesn't apply to us. FHIR bundles come in a couple different flavors, but the ones we're concerned with are "Batch" and "Transaction" types. These types of bundles will always have a resource list as their entries, because by construction and their usage, they're intended to ferry data to and from FHIR storage / FHIR interaction. So I think by virtue of what we're using the bundles for, we're safe from the error hypothetical you mention.

2022-09-07 19:06 UTC, spencer-skylight approved these changes
This looks good to me pending Brandon's function renaming suggestion.

I agree with Brandon that we shouldn't expect to process bundles that don't have a resource.  With that said, we could make this a little more tolerant of that case.  I think you could change:
```python
if entry.get("resource").get("resourceType") == resource_type
```

to
```python
if entry.get("resource",{}).get("resourceType") == resource_type
```

This way, if there's no resource, it will default to return an empty dict and fail the resourceType check without throwing an `AttributeError`.

I created a ticket for this: https://app.clickup.com/t/3h0hvhc which can be taken on separately without holding up this PR.

2022-09-07 19:20 UTC, m-goggins commented
Thanks all! Good call on the entry vs. entries. I figured you all had some naming convention but glad it is more aligned with the returned values.

I also added the empty dict return option for bundles without resources since it was an easy fix. 

Also, should I be linking the click up tickets to the PRs? I tried using click up's github integration but there was no option for this repo?

2022-09-07 19:40 UTC, spencer-skylight requested changes
One more minor request - could you add a test case for the new change in functionality for the default dict?  I think it should be a matter of updating the `patient_bundle.json` asset to contain an entry without a resource.  

Maybe just add a "request" property instead something like:
{
  "request": {
    "method": "GET",
    "url": "something"
  }
}

TBH, I'm not sure what a valid FHIR bundle would look like without a resource, but this should test for a missing resource anyhow.

2022-09-07 19:57 UTC, bamader reviewed
Pending Spencer's suggestion to add a modified test case, this looks okay. It looks like there might be some weirdness going on with `cp1232-sample.txt` which I'm not sure what to make of.

2022-09-07 19:57 UTC, bamader commented on tests/assets/cp1252-sample.txt
> +Testing windows-1252 encoding � � �
Why this change?

2022-09-07 20:30 UTC, spencer-skylight commented on tests/assets/cp1252-sample.txt
> +Testing windows-1252 encoding � � �
I can answer that since I was the original author of this file and worked with Marcelle on this change yesterday... 

The newlines on Marcelle's Windows machine were causing problems because Git was automatically converting the file to contain Windows newlines (\r\n) when downloading the sample file to her repo.  This shouldn't actually be a problem when actually downloading a file - it's more an artifact of how Git works with newlines in a windows environment.  So to sidestep the issue, we just removed the newlines.  The character encoding testing is still valid which is what this file was created to test.

2022-09-07 21:09 UTC, spencer-skylight approved these changes
LGTM!

2022-09-08 12:06 UTC, bamader requested changes
Sorry, just one little thing left (deleting the commented out line of code)!

2022-09-08 12:06 UTC, bamader commented on tests/assets/cp1252-sample.txt
> +Testing windows-1252 encoding � � �
That's wild 😲 . Little differences like that amaze me every time they pop up. This one sounds real ugly though so I'm glad you two found a workaround.

2022-09-08 12:06 UTC, bamader commented on tests/cloud/test_cloud.py
> +    # assert download_content == "Testing windows-1252 encoding\n€\nœ\nŸ\n"
Since we no longer need this, let's delete the commented out code

2022-09-08 14:54 UTC, m-goggins commented on tests/cloud/test_cloud.py
> +    # assert download_content == "Testing windows-1252 encoding\n€\nœ\nŸ\n"
Good catch

2022-09-08 16:05 UTC, bamader approved these changes
Good to go!

2022-09-08 21:33 UTC, m-goggins commented
I started adding in :param returns: to all the functions. It's definitely a good way to familiarize myself with the scripts. I wanted to check in about the formatting that I had completed so far (mainly just removing periods at the end of params). I'm not totally sure what is happening in the cloud/ script files and could use an overview, as well as the apply_selection_criteria() function in fhir/tables.py

2022-09-08 22:38 UTC, merged