Convert parquet to fhir
CDCgov/phdi pull request #425
Opened 2023-04-12 22:08 UTC by m-goggins

# PULL REQUEST

## Summary
What changes are being proposed?

## Related Issue
Fixes #

## Additional Information
Anything else the review team should know?

[//]: # (PR title: Remember to name your PR descriptively!)

2023-04-13 23:03 UTC, emmastephenson requested changes
This is a great start!

2023-04-13 23:03 UTC, emmastephenson commented on phdi/linkage/seed.py
> +    patient_resource = {
For creation of new FHIR resources, could we use a library like [`fhir.resources`](https://pypi.org/project/fhir.resources/#:~:text=Example%3A%203%3A%20This%20example%20creates%20a%20new%20Patient%20resource%20from%20json%20object(py%20dict)%3A)? I'm hesitant to hardcode the resource like this.

2023-04-14 16:37 UTC, m-goggins commented on phdi/linkage/seed.py
> +    patient_resource = {
I didn't know that this exists! I did some testing with it. Some things to note:

 - This allows us to have a fully formed Patient resource even if we only feed it partial information. Most elements will just have `None` values.
- We have to do a bit of massaging to get the row data in the correct format so that we can pass it into the Patient resource. the resource wouldn't be hard coded though. Basically, we have to put the into a dictionary like the one created in the original script, e.g., 
```
{
    "resourceType": "Patient",
    "id": str(uuid.uuid4()),
    "identifier": [
        {
            "type": {
                "coding": [
                    {
                        "system": """http://terminology.hl7.org
                                /CodeSystem/v2-0203""",
                        "code": "MR",
                    }
                ]
            },
            "value": f"{data.get('mrn',None)}",
        },
        {
            "type": {
                "coding": [
                    {
                        "system": """http://terminology.hl7.org
                                /CodeSystem/v2-0203""",
                        "code": "SS",
                    }
                ]
            },
            "value": f"{data.get('ssn',None)}",
        },
    ],
    "name": [{"family": f"{data.get('last_name',None)}"}],
}
```

Overall, I think this is a good improvement and could be useful for refactoring other testing assets after the pilot 😄 I will implement it here as well.

2023-04-14 16:55 UTC, BradySkylight commented on examples/MPI-sample-data/build_synthetic_mpi_parquet.py
> +)
This is very awesome to have!!  I love how much you have been working with and integrating synthetic data for all our testing!  Nice work Marcelle!

2023-04-14 17:04 UTC, BradySkylight approved these changes
With the changes you will make based upon Emma's feedback, I think this LGTM.  Excellent work!

2023-04-14 18:57 UTC, m-goggins commented on phdi/linkage/seed.py
> +    patient_resource = {
Hmm upon further review, I am not sure this will actually suit our needs, but maybe you can help me think this through. This resource, which has a special type `<class 'fhir.resources.patient.Patient'>`, gets added to a bundle which is then passed to the RL endpoint. The RL endpoint is expecting a `dict`. When I try to convert the `<class 'fhir.resources.patient.Patient'>` to `dict`, it doesn't appear to correctly convert to a dict. 

For example, the `name` section should look like:
```
"name" : {
      "family" : "du Marché",
      "_family" : {
        "extension" : [{
          "url" : "http://hl7.org/fhir/StructureDefinition/humanname-own-prefix",
          "valueString" : "VV"
        }]
      },
      "given" : ["Bénédicte"]
    }
```

but using `fhir.resources` results in the `name` section looking like:
```
HumanName(resource_type='HumanName', fhir_comments=None, extension=None, id=None, family='Kilback', family__ext=None, given=['Delmar', 'Middle'], given__ext=None, period=None, prefix=None, prefix__ext=None, suffix=None, suffix__ext=None, text=None, text__ext=None, use=None, use__ext=None)
```

2023-04-14 19:45 UTC, emmastephenson commented on phdi/linkage/seed.py
> +    patient_resource = {
Hmmm I was worried about this - seems like unwrapping back to `dict` isn't fully unwrapping all the nested fields. Let's chat offline?

2023-04-14 20:34 UTC, m-goggins commented on phdi/linkage/seed.py
> +    patient_resource = {
Based on offline conversation, we're going to hold off on implementing `fhir.resources`. While it does have some functionality that converts the resource to JSON format, doing so does not add anything different from what is currently implemented. We decided to create a tech debt ticket to investigate how this might be used in the future, especially as it relates to assets and testing.

2023-04-14 21:45 UTC, BradySkylight commented on phdi/linkage/seed.py
> +    patient_resource = {
Yeah, it seems that Python is lacking in their FHIR packages.  This was a simple implementation in Java from my previous experience.  It seems they are treating each data type as a resource.  SMH

2023-04-17 17:05 UTC, m-goggins commented
One thing to note: If LAC's data does not conform to the FHIR standard, this code won't correct for it. For example, if the `gender/sex` column is in a format other than `male` or `female`. It will be easy to modify the data on the fly before putting it into the bundle but just something to flag.

2023-04-17 17:15 UTC, emmastephenson approved these changes
LGTM, thanks Marcelle!

2023-04-17 17:23 UTC, merged