Add :return param: to docstrings
CDCgov/phdi pull request #46
Opened 2022-09-09 15:20 UTC by m-goggins

Started adding :param return: items to all functions with docstrings but wanted someone to take a look at general formatting (e.g.,) removed periods from docstring params) before proceeding. Some of the docstring descriptions and return params are repetitive but for the sake of consistency, I think it's okay.

2022-09-12 13:08 UTC, spencer-skylight reviewed
It's coming along! Matt Goldberg created an API style guide that I think we can leverage here:

https://docs.google.com/document/d/17PSrnDf1bf-mbbF2utV4aboodgBr8gjDaDLVotcQGYQ/edit?pli=1#heading=h.jenb7unpjy0h

I noticed a few things that we need to fix across the board:
* `:param return:` should actually be `:return:` per [Sphinx documentation](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html) - a quick find-and-replace should take care of this.
* Descriptions for getters should start with "Gets the...". Then choose as concise as you can think of for the description for the `:return:`, per the API style guide.
* Functions that do not return anything do not need an empty `:return:` value.

I'm still getting through this PR, but need to step away briefly, and there's enough here to make some progress on corrections.

2022-09-12 15:22 UTC, spencer-skylight requested changes

2022-09-12 15:22 UTC, spencer-skylight commented on phdi/tabulation/tables.py
> +    :param return:
"A dictionary representing read from the supplied `path`."

2022-09-12 17:28 UTC, m-goggins commented on phdi/tabulation/tables.py
> +    :param return:
Would "A dictionary representing read **schema** from the supplied path" be okay?

2022-09-12 17:31 UTC, spencer-skylight commented on phdi/tabulation/tables.py
> +    :param return:
Yep, you're right I was missing that key term. I think your wording is correct, but the following reads more naturally to me. I'm OK either way.
"A dictionary representing a schema read from the supplied path"

2022-09-12 17:37 UTC, m-goggins commented
Not sure if the `return writer` statement on line 58 in phdi/tabulation/tables.py is supposed to be there

2022-09-12 19:17 UTC, spencer-skylight commented on phdi/cloud/azure.py
> +        :return: True if Azure access token is valid; false otherwise
This function does actually return the access token.

2022-09-12 20:11 UTC, m-goggins commented on phdi/cloud/azure.py
> +        :return: True if Azure access token is valid; false otherwise
Changed to "Azure access token"

2022-09-13 11:20 UTC, spencer-skylight approved these changes
This is looking great - I made a few changes to clean things up. I think it's GTG!

2022-09-13 15:28 UTC, merged