Code Coverage for Linkage
CDCgov/phdi pull request #47
Opened 2022-09-09 17:33 UTC by KennethSkylight

To increase the code coverage for linkage unit tests. The `over_write = False` needed to be tested. This PR adds two tests for both bundle and resource linkage as well as fixing a logic bug on the linkage bundle

2022-09-12 12:26 UTC, spencer-skylight requested changes
Looking good, just a few minor changes to suggest.

2022-09-12 12:26 UTC, spencer-skylight commented on tests/fhir/linkage/test_fhir_link.py
> +def test_bundle_overwrite():
Nit: can you make the name more descriptive?  Maybe copy the name of the non-overwrite and append _overwrite? I know we can glean some context from the file, but the link module could do other things with bundles that we might want to differentiate in the future.

2022-09-12 12:26 UTC, spencer-skylight commented on tests/fhir/linkage/test_fhir_link.py
> +    new_bundle = add_patient_identifier_in_bundle(incoming_bundle, salt_str, False)
I think you've got the `overwrite` - non-`overwrite` test cases inverted.  I think if you omit the last parameter here, and change the other test cases' calls to `False`, you should be good.

2022-09-12 12:26 UTC, spencer-skylight commented on tests/fhir/linkage/test_fhir_link.py
> +def test_overwrite():
Same nit as previous function.

2022-09-12 12:26 UTC, spencer-skylight commented on tests/fhir/linkage/test_fhir_link.py
> +            new_resource = add_patient_identifier(resource, salt_str, False)
Same comment as previous function.

2022-09-13 11:26 UTC, spencer-skylight approved these changes
LGTM!

2022-09-13 12:17 UTC, bamader approved these changes
LGTM!

2022-09-13 18:47 UTC, merged