New PHDI Release Workflow
CDCgov/phdi pull request #517
Opened 2023-04-28 19:46 UTC by BradySkylight

# PULL REQUEST

## Summary
We need to be able to version our releases.  This version needs to be part of a tag, release in our GitHub repo, as well as tagging the Packaged Containers, with the same tag/release, in our repo.  This version number also needs to be carried over into the project 'PHDI's version number (init.py), but also should be in the .toml file as well as the version number specified in the FastAPI version within our containers.  This workflow accomplishes all that and more. This workflow will be kicked off manually when we are ready to 'cut' a release.

Work flow steps:

1. Request version number (ie. v1.0.2) which is manually entered.
2. Run all tests.
3. If tests pass then create a tag, based upon the manually entered version number, update the .toml file for the project, which also automatically updates all other internal version numbers for PHDI and the containers.  This step also creates a new release for said tag.
4. Rebuild all containers and store them as packages in our repo with the 'latest' tag as well as the version specified tag.
5. Updates the docs branch with the latest PHDI SDK Documentation

## Related Issue
Fixes #434 

## Additional Information
There are other efforts in progress, that can be added to this workflow, to update the container documentation and store that in the docs branch.  Also, we would like to release the latest version of PHDI SDK to Pypi.  Both of these efforts are almost done and have been a collab. between myself, Nick C., and Kenneth.

2023-04-28 22:56 UTC, nickclyde approved these changes
Amazing work Brady! Glad we were able to get this all sorted out together today 🚀

2023-05-01 21:29 UTC, emmastephenson approved these changes
Looks great to me! Excited to get this working!

2023-05-01 21:29 UTC, emmastephenson commented on tests/not_valid_json_test.json
> +this is a random string that is not in json format
This doesn't seem to be used in this PR?

2023-05-01 21:29 UTC, emmastephenson commented on containers/alerts/requirements.txt
> +phdi @ git+https://github.com/CDCgov/phdi.git@main
Should we tag a specific release here, instead of `main`?

2023-05-02 14:58 UTC, DanPaseltiner commented on containers/alerts/requirements.txt
> +phdi @ git+https://github.com/CDCgov/phdi.git@main
Yeah, we should probably have the release workflow automagically target the version that we are making a release for.

2023-05-02 15:02 UTC, DanPaseltiner requested changes
This is so exciting to see this coming together! Thank you @BradySkylight! I think we should address @emmastephenson's comment about targeting phdi versions in the service requirement.text files. Also, we aren't currently building docs for the container APIs, just the SDK. I'm open to adding support for these docs in a follow up PR, but we should probably have the functionality in place before making our first release with this workflow.

2023-05-02 20:31 UTC, nickclyde commented on .github/workflows/createNewRelease.yaml
> +
I have a branch going for this!
https://github.com/CDCgov/phdi/tree/nick/release-container-docs

2023-05-02 21:34 UTC, nickclyde commented on containers/alerts/requirements.txt
> +phdi @ git+https://github.com/CDCgov/phdi.git@main
I added this into my branch:
https://github.com/CDCgov/phdi/commit/9f4a1a5fa7c782019799df941c310bdb29713cbe

2023-05-03 08:39 UTC, KennethSkylight approved these changes
Excited for this one!

2023-05-03 21:02 UTC, merged