Run record linkage migrations on spin up not RL endpoint request
CDCgov/phdi pull request #518
Opened 2023-04-28 20:18 UTC by gordonfarrell

# PULL REQUEST

## Summary
Changing approach from last PR, not doing an endpoint, just running the migration function in main.py for record linkage. No need for a second PR in phdi-azure for this one.

## Related Issue
Fixes [#432](https://app.zenhub.com/workspaces/dibbs-63f7aa3e1ecdbb0011edb299/issues/gh/cdcgov/phdi/432)

## Additional Information
Anything else the review team should know?

[//]: # (PR title: Remember to name your PR descriptively!)

2023-04-28 21:30 UTC, nickclyde approved these changes

2023-05-02 14:54 UTC, DanPaseltiner requested changes
This looks really good to me. Before we merge and automagically deliver a new version of this service straight to LAC, could we build the image and manually upload to Azure to confirm that these changes won't break anything? I these changes may cause a longer cold start and I'd like to make sure that the slower spin up speed doesn't cause any kind of inadvertent timeout issues in Azure.

2023-05-02 14:54 UTC, DanPaseltiner commented on containers/record-linkage/tests/test_record_linkage.py
> +pop_mpi_env_vars()
Is this actually doing anything for us given that all the other tests clean up the env after themselves? I'm probably missing something here.

2023-05-03 15:28 UTC, emmastephenson approved these changes
Looks good to me!

2023-05-03 15:28 UTC, emmastephenson commented on containers/record-linkage/tests/test_record_linkage.py
> +pop_mpi_env_vars()
+1, is this still needed?

2023-05-03 19:18 UTC, bamader approved these changes
LGTM!

2023-05-03 19:32 UTC, DanPaseltiner approved these changes

2023-05-03 19:35 UTC, merged