Draft: GCP Cloud Connection
CDCgov/phdi pull request #58
Opened 2022-09-15 21:22 UTC by KennethSkylight

Placeholder

2022-09-16 14:08 UTC, DanPaseltiner commented on phdi/cloud/gcp.py
> +        return storage.Client()
One thing I was thinking about after our pairing session yesterday is that while this function works it makes a new instance of `storage.Client` every time it is used. For a one off cloud storage operation this is completely fine, but if we ever want to use this in a loop or some other situation where it will be called repeatedly getting a new instance of `storage.Client()` will be expensive. What do you think about using a construction like what we have done in `GcpCredentialManager.get_credential_object`? When we get a new credential object it is stored for later use. This seems a little more efficient to me.

2022-09-16 17:02 UTC, KennethSkylight commented on phdi/cloud/gcp.py
> +        return storage.Client()
Added a storage client

2022-09-19 13:01 UTC, spencer-skylight requested changes
I like where this is headin'! A few comments/suggestions to review.

2022-09-19 13:30 UTC, DanPaseltiner commented on phdi/cloud/gcp.py
> +        self, bucket_name: str, filename: str, encoding: str = "utf-8"
I had a forgotten we had discussed this. I think it makes sense. On the interface side it makes things "feel" like just any old file path for the user. We'll need to document this clearly though so that folks know the bucket/container must be included in the filename.

2022-09-19 13:36 UTC, DanPaseltiner commented on phdi/cloud/core.py
>      def list_objects(self) -> List[str]:
The challenge here is cloud provider variability. For instance in Azure we need a cred manager while in GCP we do not. Perhaps specifying the parameters on methods other than `__init__` would work.

2022-09-19 13:40 UTC, DanPaseltiner reviewed
This is looking good. I responded to a couple of @spencer-skylight's comments.

2022-09-19 16:38 UTC, KennethSkylight commented on phdi/cloud/core.py
> +    #     pass  # pragma: no cover
Thanks for catching that

2022-09-19 16:41 UTC, KennethSkylight commented on phdi/cloud/gcp.py
> +        self, bucket_name: str, filename: str, encoding: str = "utf-8"
From my experience in AWS, most functions ask to bucket name explicitly, separate from the filename. It seems to me that the GCP functions do the same. I feel that this makes sense for how those cloud functions generally work. 

To me, it seems less intuitive to have to append the bucket name to the file name because that's generally not how it works for AWS and probably for GCP. If I were a developer, I would be wondering where I am supposed to put my bucket name.

2022-09-19 18:16 UTC, KennethSkylight commented on phdi/cloud/core.py
>      def list_objects(self) -> List[str]:
I agree with Dan, it seems that cloud providers call their storage terms something else. Blobs vs buckets vs files vs paths vs storage vs container. 

I think leaving it up to the implementer to call it what it's supposed to be may make more sense

2022-09-20 16:59 UTC, spencer-skylight requested changes
Almost there! Just a few things to bring BaseCloudStorageConnection back in line with the cloud-specific implementations.

2022-09-20 16:59 UTC, spencer-skylight commented on phdi/cloud/core.py
> +    def download_object(self, filename: str, encoding: str = "utf-8") -> str:
Could you add container_name back in here? Per discussion on another thread, all 3 major cloud providers have the concept of buckets/containers.

2022-09-20 16:59 UTC, spencer-skylight commented on phdi/cloud/core.py
> -        container_name: str,
Flagging to add back container_name.

2022-09-20 16:59 UTC, spencer-skylight commented on phdi/cloud/core.py
> -    def list_containers(self) -> List[str]:
Remind me why we are removing this method?  I thought it was because GCP doesn't have the concept of a bucket/container, but I no longer think that's true.

2022-09-20 16:59 UTC, spencer-skylight commented on phdi/cloud/core.py
>      def list_objects(self) -> List[str]:
Not related to this PR, I know, but could we add container_name and prefix to the method signature to match the documentation (and cloud vendor implementations)?

2022-09-20 16:59 UTC, spencer-skylight commented on phdi/cloud/gcp.py
> +        self, bucket_name: str, filename: str, encoding: str = "utf-8"
Sounds good to me.  This being the case, I think we need to make a few adjustments to the base implementation (see other comments).

2022-09-20 16:59 UTC, spencer-skylight commented on tests/cloud/test_cloud.py
> +from phdi.cloud.gcp import GcpCloudStorageConnection, GcpCredentialManager
Testing coverage looks good to me.

2022-09-20 17:02 UTC, KennethSkylight commented on phdi/cloud/core.py
>      def list_objects(self) -> List[str]:
Added

2022-09-21 17:00 UTC, KennethSkylight commented on phdi/cloud/core.py
> -    def list_containers(self) -> List[str]:
Added

2022-09-21 17:01 UTC, KennethSkylight commented on phdi/cloud/core.py
>      def list_objects(self) -> List[str]:
Per our conversation, I changed the names back to container

2022-09-21 17:06 UTC, spencer-skylight approved these changes
LGTM!

2022-09-21 17:08 UTC, merged