Split up FHIR bundles (by FHIR Resources) that are too big for FHIR server to handle
CDCgov/phdi pull request #613
Opened 2023-05-24 22:32 UTC by BradySkylight

# PULL REQUEST

## Summary
This PR contains changes to ensure that FHIR Bundles that have more than a specified maximum number, default to 500, of FHIR Resources will be split up into separate bundles prior to uploading them to the FHIR server.  The following changes can be found:

1- New parameter max_bundle_size, which defaults to 500 (per the issues we saw with the Azure FHIR Server) in both the call to upload bundles to FHIR server as well as the new function _split_bundle_resources.  Note: we can add this parameter to the container at a later time and as needed for our clients.
2- New function split_bundle_resources that returns a list of bundles to be processed.
3- Changes to the upload_bundle_to_fhir_server so that it calls the new split function and loops through the results.  Update the Response.status_code if there is a failure in any of the uploads.  Note: We may need to find a way to append the Response.json() to the final return Response in this function.  I have placed a TODO in the code for this work.  Note that if there are ever any errors they will be logged at the very least.
4- A few documentation updates including updating the PHDI init.py to contain the latest version.  We may need to have this automatically set by our processes in the future when cutting a new release.

## Related Issue
Fixes #https://app.zenhub.com/workspaces/dibbs-63f7aa3e1ecdbb0011edb299/issues/gh/cdcgov/phdi-azure/130

2023-05-24 23:04 UTC, DanPaseltiner requested changes
Thanks for putting this together! Looking good. I think we need to address the TODO as a part of this PR (see comment below).

2023-05-24 23:04 UTC, DanPaseltiner commented on phdi/fhir/transport/http.py
> +    #  witht he logic above.
I think we probably should do this now, otherwise we are effectively taking away functionality from our users. If there is a failure on resource in the first partial bundle then they won't be able to see the actual response to debug. Now that I'm writing this out this might even impact our ability to debug FHIR upload issues.

2023-05-24 23:05 UTC, BradySkylight commented on phdi/fhir/transport/http.py
> +    #  witht he logic above.
Yeah, I was worried about this.  I'll continue plugging away at getting this to work.

2023-05-24 23:06 UTC, BradySkylight commented on phdi/fhir/transport/http.py
> +    return split_bundles
Yes, if you do that then the last replace of entry in bundle_prefix will be present in both 'bundles' in the split_bundles list.  That was the exact issue I was running into.

2023-05-24 23:19 UTC, DanPaseltiner commented on phdi/fhir/transport/http.py
> +    return split_bundles
Now that we are no longer using `.append()` I don't think that will be an issue. Maybe I need to run this code myself to understand, but I really think each iteration would do a clean replace.

2023-05-26 20:37 UTC, DanPaseltiner approved these changes
This looks awesome. One minor nit you can feel free to ignore. I also left a suggestion for changing when we log failures so that we can handle both `200` and `201` status codes.

2023-05-26 20:37 UTC, DanPaseltiner commented on phdi/fhir/transport/http.py
> +                ):
I think this will make us consistent with what we do in the container an handle 201s. We have seen differences across FHIR servers and differences when a resource already exists v. when it is created for the first time.

```suggestion
                if entry_response and entry_response.get("status", "") not in ["200 OK", "201 Created", "200", "201"]:
```

2023-05-26 20:37 UTC, DanPaseltiner commented on containers/ingestion/app/routers/fhir_transport_http.py
> +        "entry": [],
Major nit: Doesn't `"entry"` usually get listed after `"resourceType"` and `"tyep"`?

2023-05-26 20:50 UTC, BradySkylight commented on containers/ingestion/app/routers/fhir_transport_http.py
> +        "entry": [],
You are correct.  I'll fix that up real quick!  Nice catch.

2023-05-26 20:57 UTC, merged