Census geocoding
CDCgov/phdi pull request #62
Opened 2022-09-22 22:00 UTC by m-goggins

Adds a call to the Census API for either a single string address (`searchtype=onelineaddress`) or a dictionary (`searchtype=address`). The resulting GeoCodeResult includes similar components to Smarty with the addition of the following:
- census tract
- census block
- geoid (A combination of state, county, census tract, and census block info)

Precision is not returned for the Census API, and it appears to always be zip5. 

For the MVP, we assume the following input for the call to the API. In future iterations, these could be additional inputs from the user:

```
:param benchmark: A numerical ID or name that references what version of the
            locator should be searched. # Public_AR_Census2020
:param vintage: A numerical ID or name that references what vintage of geography
            is desired for the geoLookup (only needed when returntype = geographies) # Census2020_Census2020
:param format: The format to be used for returning the standardized output
            (json, html) # json
:param layers: By default, State, County, Tract, and Block layers are displayed
            when “geographies” is the chosen returntype. If additional or different
            layers are desired, they can be specified in a comma delimited list by ID
            or name # layer = 10, which is census tract/block info. You can change this to get ACS data (I think)
```

2022-09-23 16:55 UTC, bryan-skylight requested changes
This looks really great so far! I have some changes that I'd like to see implemented, especially around the tests, but overall I think this is close to being done. Thanks for putting this together so quickly!

2022-09-23 16:55 UTC, bryan-skylight commented on phdi/geospatial/census.py
> +    # # @property
Is this supposed to be commented out? If so, can we just remove it from the code and add it back later when we're ready to implement it? I'd prefer to avoid commented code making it into production.

2022-09-23 16:55 UTC, bryan-skylight commented on phdi/geospatial/census.py
> +            raise Exception("Must include street number and name at a minimum")
Can we make this error message consistent with the error message used in `smarty.py`? I don't have a preference for which language we use, but I would prefer that they be consistent.

2022-09-23 16:55 UTC, bryan-skylight commented on phdi/geospatial/census.py
> +    def geocode_from_dict(self, address: dict) -> Union[GeocodeResult, None]:
I know that the smarty module does this as well, so I assume you're just implementing similar functionality, but do we have a use case in mind for when a user would pass a dictionary instead of a string? I'm wondering if we want to change this interface.

2022-09-23 16:55 UTC, bryan-skylight commented on phdi/geospatial/census.py
> +        :return: A GeocodeResult object (if valid result) or None (if no valid
Can we be more descriptive with the return values in the docstrings? Instead of focusing on the type that is returned, which is already included in the Sphinx docs by default, can we specify the context of what's being returned?

2022-09-23 16:55 UTC, bryan-skylight commented on phdi/geospatial/census.py
> +    def _call_census_api(url):
Given that we're handling the request ourselves in this module, as compared to the Smarty module where we utilize `send_lookup`, I'm wondering if we should incorporate our `http_request_with_retry` method to handle things like 429 HTTP status codes.

2022-09-23 16:55 UTC, bryan-skylight commented on phdi/geospatial/census.py
> +                .get("Census Blocks")[0]
How confident are we that if "addressMatches" is present that:
1. it will always have at least one element present, instead of an empty list, and
2. that any given element in "addressMatches" will have the "geographies" and "Census Blocks" keys?

I'm worried that we could get unexpected `KeyError` exceptions given that `.get("geographies")` will return `None` by default. Would it make sense to modify the default values such that we have something like this?

```python
lookup.get("addressMatches", [{}])[0]
.get("geographies", {})
.get("Census Blocks", [None])[0]
```

2022-09-23 16:55 UTC, bryan-skylight commented on phdi/geospatial/census.py
> +                city=addressComponents.get("city", ""),
I could be wrong about this, but I think the smarty module would return `None` for values that aren't present. Can we confirm that the return values for missing elements is consistent across both modules?

2022-09-23 16:55 UTC, bryan-skylight commented on tests/geospatial/test_census_geocode_client.py
> +    censusResponseFullAddress_noAddressMatch = censusResponseFullAddress
nit: Just for my own understanding, why are you loading the file under one variable name and then immediately setting it to another variables name?

2022-09-23 16:55 UTC, bryan-skylight commented on phdi/geospatial/census.py
> +        if address.get("street", "") == "":
I don't think we necessarily need to change this in this PR, but I do have hesitations about not allowing geocoding if there's no street address. In some scenarios, deidentified/anonymized data may only include city, state, and zip as it relates to, say, HIV. Geocoding across several states to show a choropleth map of the most impacted states would require the ability to geocode at this level, no? Is this a restriction we're placing on the data, or one that the API is placing?

2022-09-23 16:55 UTC, bryan-skylight commented on tests/geospatial/test_census_geocode_client.py
> +        assert geocode_result is None
nit: can we make the variable name consistent with the preceding and proceeding tests (`geocoded_response`)?

2022-09-23 16:55 UTC, bryan-skylight commented on tests/geospatial/test_census_geocode_client.py
> +            repr(e) == "Exception('Must include street number and name at a minimum')"
Can we add the same assertion here that `geocoded_response` is still `None` after the attempt to geocode?

2022-09-23 16:55 UTC, bryan-skylight commented on phdi/geospatial/census.py
> +            raise Exception("Cannot geocode given address")
Can we make these exceptions more descriptive? Perhaps `ValueError`?

2022-09-23 16:55 UTC, bryan-skylight commented on tests/geospatial/test_census_geocode_client.py
> +        assert geocode_result is None
Also, I think we should rework this test (and the one below) a little bit. As it stands, I think this mostly tests that the exception message is correct, and not so much that it throws an exception. I think the following might better test for what we want to catch here.

```python
with pytest.raises(ValueError) as e:
    geocoded_response = census_client.geocode_from_str(address)

assert "Must include street number and name at a minimum" in str(e.value)
assert geocoded_response = None
```

See https://docs.pytest.org/en/7.1.x/how-to/assert.html#assertions-about-expected-exceptions for more info.

2022-09-23 17:22 UTC, m-goggins commented on phdi/geospatial/census.py
> +            raise Exception("Must include street number and name at a minimum")
I like "Address must include street number and name at a minimum." I'll change it here and in smarty.py

2022-09-23 17:22 UTC, m-goggins commented on phdi/geospatial/census.py
> +    def geocode_from_dict(self, address: dict) -> Union[GeocodeResult, None]:
Ha! this was my question as well. I think this is another question for user research. Brandon said the dict version was created as a prototype data storage object where people would likely store address information they had that wasn't in string form.

2022-09-23 17:27 UTC, m-goggins commented on phdi/geospatial/census.py
> +        if address.get("street", "") == "":
Sounds like another one for UX :) The census API requires a street name and number at a minimum

2022-09-23 17:29 UTC, m-goggins commented on tests/geospatial/test_census_geocode_client.py
> +    censusResponseFullAddress_noAddressMatch = censusResponseFullAddress
Ah good catch! I think I had intended to add other tests but moved them elsewhere. I'll just changed the loaded file name.

2022-09-26 17:38 UTC, m-goggins commented on phdi/geospatial/census.py
> +    def _call_census_api(url):
I added `http_request_with_retry` into the `_call_census_api` method but kept the same return logic in order to return the result if valid and pass that to the` _parse_census_result` method

2022-09-26 17:42 UTC, m-goggins commented on phdi/geospatial/census.py
> +        :return: A GeocodeResult object (if valid result) or None (if no valid
I am working on this - Spencer and Matt have been going back and forth in a separate space about formatting docstrings and other documentation items.

2022-09-27 12:17 UTC, spencer-skylight requested changes
This is great! I had a bunch of little comments, but nothing major.

One other nit - percentage-wise coverage is good, but the lines we aren't hitting are exceptions and edge cases we should probably be testing.  Could you take care of those as well?

2022-09-27 12:17 UTC, spencer-skylight commented on phdi/geospatial/smarty.py
> +            raise ValueError("Address must include street number and name at a minimum")
Thank you for updating this to throw a more specific exception. We should probably add a `raises` declaration to the docstring as well.

2022-09-27 12:17 UTC, spencer-skylight commented on tests/geospatial/test_smarty_geocode_client.py
>      try:
I think a better way to do this is:
```python
pytest.raises(ValueError, match=r"Address must include street number and name at a minimum")
  smarty_client.geocode_from_str("")
```

Or it looks like you've done `pytest.rasies(ValueError) as e` and checked properties of e in your new tests which I think is also fine.

2022-09-27 18:02 UTC, m-goggins commented on phdi/cloud/core.py
> +    def download_object(self, filename: str, encoding: str = "utf-8") -> str:
huh I'm not totally sure where that change came from since I didn't think I touched the cloud files. In any case, I will add it back in.

2022-09-27 18:16 UTC, m-goggins commented on phdi/geospatial/census.py
> +        Format address for Census API call according to address type.
I added some explanation in the description but I think this should be part of a larger conversation around how we want to customize the census api moving forward. The Census API has several params that I did not include as user options (searchtype, layer, etc). for this iteration of the Census coder. I think in future iterations we should allow the user to have more flexibility in the vintage and layers they want to use. For the sake of the quick release and matching Smarty, I think we should keep these standardized (pre filled-in).

2022-09-27 18:18 UTC, m-goggins commented on phdi/geospatial/census.py
> +            or name
Ditto the comment above around getting the initial version of the Census API wrapper out and then adding in customization based on user research.

2022-09-27 18:41 UTC, bryan-skylight commented on phdi/geospatial/census.py
> +            or name
![mando-way-this-is-the-way](https://user-images.githubusercontent.com/97973748/192609493-cc136e45-63ad-400d-ab2d-be1786b26eed.gif)

Although I would advocate for removing the parameters from the docstring until they're implemented, just to avoid any confusion.

2022-09-28 11:59 UTC, spencer-skylight approved these changes
Super close from my perspective - just a few super nit-picky follow ups, but no blockers.

2022-09-28 11:59 UTC, spencer-skylight commented on phdi/geospatial/smarty.py
> +        :param address: a dictionary with fields outlined above.
Nit: capitalize "a"

2022-09-28 11:59 UTC, spencer-skylight commented on docs/geocoding_beta/overview.md
> +    - Partner will need to obtain a Smarty license (API key); see "Receiving a CDC subsidized Smarty license (API key)" section below for details
This last section should be removed.

2022-09-28 11:59 UTC, spencer-skylight commented on phdi/geospatial/census.py
> +        :param address: The address to geocode, given as a string
Nit: Suggesion: "The address to geocode, given as a string or dictionary."

2022-09-28 11:59 UTC, spencer-skylight commented on tests/geospatial/test_smarty_geocode_client.py
>      try:
This one wasn't implemented - was that intentional? It's not a sticking point for me - just a minor suggestion.

2022-09-28 15:20 UTC, bryan-skylight requested changes
Line 163 of `census.py` is the big blocker for me at this moment. Otherwise, this looks really great!

2022-09-28 15:20 UTC, bryan-skylight commented on phdi/geospatial/census.py
> +        :return: A GeocodeResult object (if valid result) or None (if no valid
That makes sense. In an effort to both keep the return statement short and also provide more useful information to the user, can I propose that we change this to something like "A standardized address enriched with lat, lon, census tract, and more. Returns None if there is no valid result."?

2022-09-28 15:20 UTC, bryan-skylight commented on phdi/geospatial/census.py
> +        if address.get("street", "") == "":
If the Census API requires a street name and number then I'm good with leaving this as is. Again, not for this PR, but we should note that this is a possible limitation of this API for that use case.

2022-09-28 15:20 UTC, bryan-skylight commented on phdi/geospatial/smarty.py
>          :return: A GeocodeResult object (if valid result) or None (if no valid
Can I ask that we update this return description to match the suggestion I made above?

2022-09-28 15:20 UTC, bryan-skylight commented on phdi/geospatial/smarty.py
>          :return: A GeocodeResult object (if valid result) or None (if no valid
Same request here about modifying the return description

2022-09-28 15:20 UTC, bryan-skylight commented on tutorials/geospatial-tutorial.md
> +location = "5905 Wilshire Blvd Los Angeles CA 90036"
Just for my own awareness, was there a driving factor for changing this address? My hypothesis is that you're replacing a fake address that doesn't exist with a real address of a public institution so that readers can follow along with the tutorial. Is that right?

2022-09-28 18:00 UTC, m-goggins commented on tests/geospatial/test_smarty_geocode_client.py
>      try:
Not intentional! I fixed it to match the others

2022-09-28 20:28 UTC, m-goggins commented on phdi/geospatial/census.py
> +        if response.status_code < 400:
I made the changes that you suggested and added in a test to make sure this line got coverage per @spencer-skylight 's suggestion, but I don't think it's a great test. Could one of you take a look at it?

2022-09-29 14:48 UTC, spencer-skylight commented on phdi/geospatial/census.py
> +        if response.status_code < 400:
Thanks for tagging me on this! I think it's testing a valid scenario, but we should be mocking the response from the Census API rather than executing actual requests against it. 

Also, the `else:` clause at the end of `_call_census_api` is probably unnecessary.

2022-09-29 20:41 UTC, m-goggins commented on phdi/geospatial/census.py
> +        if response.status_code < 400:
Hm I think we do need the else clause to return the resulting geocoded address.

2022-09-29 20:42 UTC, m-goggins commented on phdi/geospatial/census.py
> +        if response.status_code < 400:
Per our discussion earlier, I implemented the mocked up the response from the census API

2022-09-29 21:55 UTC, bryan-skylight approved these changes
![pitch-perfect-fat](https://user-images.githubusercontent.com/97973748/193149142-3d840b63-1739-4e97-a8e4-de908287bf19.gif)

2022-09-29 21:55 UTC, bryan-skylight commented on tests/geospatial/test_census_geocode_client.py
> +        assert str(e) == "<ExceptionInfo HTTPError() tblen=2>"
nit: This is nit-pickiest thing in the world, but I'm a big fan of consistency. Can you make this test match the others in that a) the `assert` statement is outside of the with, and b) either modify this comparison to match the ones below (i.e. `"Exception Message" in str(e)`) or modify the ones below to match this approach (I think I like this approach more, but dealer's choice)

2022-09-29 22:13 UTC, merged