FHIR Census geocoding
CDCgov/phdi pull request #71
Opened 2022-09-30 14:55 UTC by m-goggins

Creates a version of the census geocoder for handling geocoding of FHIR resources and bundles. Importantly, a new method `_store_census_tract_extension ` has been added. It adds a census tract Address.line extension to a bundle for every element of an Address line. Note: while the base census geocoder is able to return census block and census geoid, the FHIR version does not yet support adding these items to a resource.

I also made a small change to the main census geocoder client, but I think we should have a discussion around it (perhaps outside github). Originally, the census geocoder returned the full matched address as the address line, e.g., ["239 GREENE ST", "NEW YORK", "NY", "10003"]. This does not match the smarty return (["239 GREENE ST"]) and became a problem when attempting to add a census tract extension for every element of the line; in the above case, the census tract extension would have been added 4 times. I modified so that only the 1st element of the address line is returned for the census geocoder, e.g., ["239 GREENE ST"]. 

A somewhat related problem is that the Census coder removes any 2nd address line information in the matched address, e.g. "239 Greene St, Apt 4L" becomes "239 Greene St." This is not a problem for census coding, but could be a problem in the case of overwriting an address in a patient resource (I think), because address information could potentially be lost.

2022-09-30 14:59 UTC, m-goggins commented
Does the code coverage drop dramatically for anyone else? It doesn't look like the coverage report includes fhir/geospatial/census.py for some reason. Wondering if this is just on my end.

2022-10-03 11:38 UTC, spencer-skylight requested changes
Nice work! :guitar: I had a few suggestions to consider.

2022-10-03 11:38 UTC, spencer-skylight commented on tests/fhir/geospatial/test_fhir_census_client.py
> +def test_geocode_resource_census():
Test test cases should patch the census geocoder.

2022-10-03 11:38 UTC, spencer-skylight commented on tests/fhir/geospatial/test_fhir_census_client.py
> +def test_geocode_resource_census():
Could you test a few edge cases:
* Patient already has an extension on `line`, and it's preserved.
* Existing extension on `line` has one row explicitly set to `None`.

I think you could cover both test cases by doing the following...
```python
patient['_line'] = []
patient['_line'].append("None")
patient['_line'].append({
"extension": [ ...an existing extension... ]
})

2022-10-03 11:38 UTC, spencer-skylight commented on tests/fhir/geospatial/test_fhir_census_client.py
> +    assert patient == census_client.geocode_resource(patient, overwrite=True)
I think you should be checking against `standardized_patient` rather than geocoding again.

2022-10-03 11:38 UTC, spencer-skylight commented on phdi/geospatial/census.py
> +                    lookup["addressMatches"][0]["matchedAddress"].split(",")[0].strip()
Why did you have to remove address lines after the 1st one from the GeocodeResult?

2022-10-03 11:38 UTC, spencer-skylight commented on phdi/geospatial/census.py
> +                    lookup["addressMatches"][0]["matchedAddress"].split(",")[0].strip()
What happens if no responses come back from the Census API? Will you always get a value for `addressMatches` and `addressMatches.matchedAddress`?

2022-10-03 11:38 UTC, spencer-skylight commented on phdi/fhir/geospatial/census.py
> +            _ = self.geocode_resource(entry.get("resource", {}), overwrite=True)
I don't think you need to assign the `_` variable here - just call the function.

2022-10-03 11:38 UTC, spencer-skylight commented on phdi/fhir/geospatial/census.py
> +            onelineaddress = get_one_line_address(address)
Since FHIR has the address split into discrete components, and the Census geocoder supports geocoding discrete components, I'm thinking we should call geocode_from_dict instead of geocode_from_str...

2022-10-03 14:08 UTC, m-goggins commented on phdi/geospatial/census.py
> +                    lookup["addressMatches"][0]["matchedAddress"].split(",")[0].strip()
This is what I was trying to outline in the comment I left on the PR (last paragraph):

I also made a small change to the main census geocoder client, but I think we should have a discussion around it (perhaps outside github). Originally, the census geocoder returned the full matched address as the address line, e.g., ["239 GREENE ST", "NEW YORK", "NY", "10003"]. This does not match the smarty return (["239 GREENE ST"]) and became a problem when attempting to add a census tract extension for every element of the line; in the above case, the census tract extension would have been added 4 times. I modified so that only the 1st element of the address line is returned for the census geocoder, e.g., ["239 GREENE ST"].

A somewhat related problem is that the Census coder removes any 2nd address line information in the matched address, e.g. "239 Greene St, Apt 4L" becomes "239 Greene St." This is not a problem for census coding, but could be a problem in the case of overwriting an address in a patient resource (I think), because address information could potentially be lost.

2022-10-03 14:45 UTC, m-goggins commented on phdi/geospatial/census.py
> +                    lookup["addressMatches"][0]["matchedAddress"].split(",")[0].strip()
As long as the URL for the API call is valid, you will get a response that contains `addressMatches `and `matchedAddress`. If there is no corresponding match, the returned values will be empty and like the Smarty geocoder, return None. I believe `test_parse_census_result_failure()` tests for this scenario in test_census_geocode_client.py

2022-10-03 15:00 UTC, m-goggins commented on phdi/fhir/geospatial/census.py
> +            onelineaddress = get_one_line_address(address)
I was thinking that too originally. However, the geocode_from_dict() is expecting "street" (string) as a key instead of "line" (list of street values). I don't think I'm opposed to switching to geocode_from_dict() but it will impact the expected key-value pairs in geocode_from_dict() and make the function different from the smarty version. Thoughts?

2022-10-03 18:31 UTC, spencer-skylight commented on phdi/fhir/geospatial/census.py
> +            onelineaddress = get_one_line_address(address)
Just documenting what we discussed... I think we can concatenate the multiline streets with a space. Doing that small amount of concatenation should be more easily interpretable by the Census API vs concatenating the whole address into a single line.

Our success with this does depend somewhat on the Census API's implementation, but it seems like a good place to start.

2022-10-03 21:42 UTC, spencer-skylight commented on phdi/geospatial/census.py
> +                    lookup["addressMatches"][0]["matchedAddress"].split(",")[0].strip()
Documenting what we discussed - we will remove "line" from the replaced fields because the Census geocoder doesn't always preserve things like unit number in the response info. 

This doesn't necessarily change the behavior of the (non-FHIR) geocoder.  The non-FHIR geocoder can still return line number in the `GeocodeResult` for the user to do with as they please.

2022-10-04 21:27 UTC, spencer-skylight requested changes
A few minor suggestions.

2022-10-04 21:27 UTC, spencer-skylight commented on phdi/fhir/geospatial/core.py
> +                if address["_line"][element_counter].get("extension", "") is not None:
I think this if statement is unnecessary.  The line below should raise the exceptions you are using to handle edge cases.

2022-10-04 21:27 UTC, spencer-skylight commented on phdi/fhir/geospatial/core.py
> +                )
Since you are initializing the extension array here, you know it's empty. Changing it like this would be clearer/more efficient.
```suggestion
                address["_line"].append({"extension": [ census_extension ]})
```

2022-10-04 21:27 UTC, spencer-skylight commented on tests/fhir/geospatial/test_fhir_census_client.py
> +    # print()
Let's get rid of these debug statements :slightly_smiling_face:

2022-10-04 21:27 UTC, spencer-skylight commented on tests/fhir/geospatial/test_fhir_census_client.py
> +def test_geocode_resource_census():
I think this still isn't covering the case where the patient address coming in to the geocoder has an existing extension on `line`.

To correct (and simplify) the code I suggested above, you could try this:
`patient['address'][0]['_line'] = [ None, { "extension": [ ... an existing extension ... ] } ]`

This should add an extension to the _input_ of the function you're testing, and you can make sure it doesn't cause errors or get overwritten.

2022-10-05 12:44 UTC, m-goggins commented on tests/fhir/geospatial/test_fhir_census_client.py
> +def test_geocode_resource_census():
I probably could have been clearer but I added an extension in a new asset that looks like the following. I think it accomplishes the same thing as your code, but correct me if I'm wrong.

`"address": [
                    {
                        "line": [
                            "239 Greene St",
                            "Apt 4L"
                        ],
                        "city": "New York",
                        "state": "NY",
                        "postalCode": "10003",
                        "country": "USA",
                        "use": "home",
                        "_line": [
                            {
                                "extension": [
                                    {
                                        "existing_url": "existing_extension"
                                    }
                                ]
                            },
                            null
                        ]
                    }
                ],`

2022-10-05 12:57 UTC, m-goggins commented on phdi/fhir/geospatial/core.py
> +                if address["_line"][element_counter].get("extension", "") is not None:
Ah good catch! I added the AttrubuteError but forgot to remove the if statement.

2022-10-05 13:18 UTC, spencer-skylight commented on tests/fhir/geospatial/test_fhir_census_client.py
> +def test_geocode_resource_census():
Yep, you're right - looks good!

2022-10-05 13:19 UTC, spencer-skylight approved these changes
LGTM!

2022-10-05 15:16 UTC, merged