Migrate PHDI to use containerized conversion solution
CDCgov/phdi pull request #73
Opened 2022-10-04 12:39 UTC by spencer-skylight

# Description
The conversion code has been updated to consume the containerized solution created by the cloud implementation team. Related documentation has also been added.

# Testing
In addition to standard unit tests, tests were additionally run against the containerized solution itself.  After installing Docker, the solution can be run from a shell using:

```bash
docker run -p 8080:8080 docker.io/gskathol/fhir-converter
```

An HL7 test can be performed using:
```python
import phdi.fhir.conversion

hl7_message = open("tests/assets/FileSingleMessageSimple.hl7").read()
phdi.fhir.conversion.convert_to_fhir(hl7_message,"http://0.0.0.0:8080/convert-to-fhir").json()
```

```python
import phdi.fhir.conversion

ccda_message = open("tests/assets/ccda_sample.xml").read()
phdi.fhir.conversion.convert_to_fhir(ccda_message,"http://0.0.0.0:8080/convert-to-fhir").json()
```

# Additional notes
A few TODOs were added to update documentation pointing to the containerized solution after it's been moved to the PHDI library.

2022-10-05 17:55 UTC, DanPaseltiner requested changes
Thanks for putting this together. This looks mostly good to me, but I think we should allow the user of this function to see the full response form the FHIR converter even when the status code is not 200. Our request validation with Pydantic gives useful feedback when users make bad requests. Additionally, when conversion fails we currently return whatever error messaging the MSFT converter CLI generates.

2022-10-05 17:55 UTC, DanPaseltiner commented on phdi/fhir/conversion/convert.py
> +    headers: dict = {},
I like including `header` here.

2022-10-05 17:55 UTC, DanPaseltiner commented on phdi/fhir/conversion/convert.py
Do we want to raise an exception here, or just return the response so that the user can see what went wrong during conversion? The converter provides relatively robust messaging back to users when they make bad requests.

2022-10-05 19:56 UTC, spencer-skylight commented on phdi/fhir/conversion/convert.py
I think it makes sense to return response regardless of status code. As an alternative, we could raise a requests.HTTPError that contains the response, so the caller can get to it if they need to.

IIRC @bryan-skylight might have been advocating for going the exception route, and @bamader might also have an opinion. What are your thoughts here?

2022-10-06 18:17 UTC, bamader approved these changes
Good stuff here! I think once we get that response (or error holding a response) configured we'll be good to go!

2022-10-06 18:17 UTC, bamader commented on phdi/fhir/conversion/convert.py
> -        ],
Is the fact that we can simplify this due to the converter that's been containerized? I love that we can eliminate these lines, just want to make sure a user's request will always be packaged appropriately to the container.

2022-10-06 18:17 UTC, bamader commented on phdi/transport/http.py
> +    http.mount("http://", adapter)
What's the reason for this addition? Shouldn't we always be opting for secured channels when possible?

2022-10-07 15:35 UTC, spencer-skylight commented on phdi/fhir/conversion/convert.py
I thought about this more and decided that wrapping in an HTTPError wasn't exactly correct, since the HTTP request actually succeeded, it is just reporting an error that occurred during the conversion operation. So I created a ConversionError, with an http_response property. Curious to know what you think of this approach!

2022-10-07 15:47 UTC, spencer-skylight commented on phdi/fhir/conversion/convert.py
> +    if conversion_settings.get("input_type") == "hl7v2":
Lowercase is currently required by the containerized conversion service.

2022-10-07 17:44 UTC, DanPaseltiner approved these changes
Thanks for the pairing session. This looks like a good solution to me.

2022-10-07 17:49 UTC, spencer-skylight commented on phdi/transport/http.py
> +    http.mount("http://", adapter)
The containerized conversion service only operates in http mode currently. The plan is to have cloud services handle https encryption, but since we also want to be able to run it against the container locally, we added the ability to connect via http. For on-prem solutions, this should be OK as long as the converter service is protected by the firewall.

2022-10-07 17:50 UTC, merged