Bugfix cu#30zf9qg
CDCgov/phdi pull request #77
Opened 2022-10-05 16:00 UTC by bryan-skylight

# Description
A bug was identified in which we required the "use" of a Resource field be specified, but the STU3 and R4 specifications for FHIR do not list "use" as a required data point. This PR addresses this issue by modifying `get_field` to make the `use` parameter optional. In doing so, "use" now becomes an optional filtering criteria, as well as a means for indicating priority. If a user wants only "official" names, then they can set the `use` parameter to `"name"` and the `require_use` parameter to `True`.  However, if they'd _prefer_ to get the home phone of a patient, but will accept any number in the record, then they can set `use` to `"mobile"` and `require_use` to `False`. Lastly, if they have no specific use they care about, `use` can be set to `None` and `require_use` will be ignored.

The function signature has also been updated to reflect that the return value can be one of several data types. This violates one of our design principles, which states that functions should return one (two if `None` can be returned) data type, but we view this as a necessity for the sake of simplifying things for our end users. 

# What this doesn't do
This does not account for more complex data types that FHIR supports, nor does it support field extraction deeper than the the top level. For example, a user cannot extract _only_ the `Address.line` field, and must instead extract the whole address. Supporting this nested extraction would require implementing FHIRPath, which is a bridge we will cross later.

# Feedback requested
The key question I had was around how to handle the various return types, which was settled via a Slack conversation. Other than that, the common key questions are still outstanding:

1. Are we missing any edge cases?
2. Are the tests covering what they need to cover?
3. Does the logic make sense?
4. Is this usable by our users?

# Tests
`test_utils.py` needed to be updated to reflect the new function signature, but all tests pass and the `test_get_field` test already tests for an option `use` parameter in its attempt to extract "telecom".

2022-10-05 16:33 UTC, BradySkylight commented on phdi/fhir/utils.py
> +        raise KeyError(f"This resource does not contain a field called {field}")
This may be nit-picky, especially since there are different meaning for these terms (field, element, etc... ) depending upon the context (FHIR vs. coding, etc..).  It may be good to follow the FHIR definition of terms here?  ie: "This resource does not contain an element called {field}".  I could go either way and depends upon what would be better for the user/audience.

2022-10-05 17:18 UTC, m-goggins commented on phdi/fhir/utils.py
> +    if no elements of the specified field have that use, none will be returned. If
Nit but slightly more understandable to me: If True _and_ if no elements of the specified field have that use, none will be returned

2022-10-05 17:18 UTC, m-goggins commented on phdi/fhir/utils.py
> +    False, then if no elements of the specified field have that use the default index
If False _and_

2022-10-05 17:20 UTC, BradySkylight approved these changes
This all looks good to me.  I didn't have one comment/recommendation, but isn't 'required' as it's a bit nitpicky.  

To answer the questions:

1. Are we missing any edge cases?
I think so other than the one concern discussed and resolved during stand-up.
2. Are the tests covering what they need to cover?
Yes, they are clear and straightforward.
3. Does the logic make sense?
Yes, and I like your Python wizardry!
4. Is this usable by our users?
Yes, I think this is a simple enough change and the function/method is simple to understand and use.

2022-10-05 17:30 UTC, m-goggins commented on phdi/fhir/utils.py
>      if field not in resource:
I'm wondering if it would be helpful to the user to also include the use in the error message (if use is included). For example, someone inputs a legitimate field and use, but the particular field they specify is not in the specified use and is instead in another section of the resource?

2022-10-05 19:39 UTC, spencer-skylight requested changes
A few comments, functionally it looks good.

I'd suggest including a few other output datatype in the code coverage since it was a focus of the changes made.  There's also a test that I'd expect to fail, asserting an exception on a missing use parameter. That should be updated to assert it returns the first entry I think.

I'm not sure why the checks aren't running for this PR - maybe just a GitHub hiccup? I'm happy to pair or dig in further on that if needed.

2022-10-05 20:09 UTC, bryan-skylight commented on phdi/fhir/utils.py
> +    raw_one_line += f" {address.get('city')}, {address.get('state')}"
You're absolutely right, and I'm not sure how this change got made because I didn't make tweaks to this line of code. 😅 I'll change it back to what it was before, because `None` should definitely not be the default.

2022-10-05 20:11 UTC, bryan-skylight commented on phdi/fhir/utils.py
> +) -> Union[Dict, List, str, None]:
Should we just change this to `Any` then?

2022-10-05 21:09 UTC, spencer-skylight commented on phdi/fhir/utils.py
> +) -> Union[Dict, List, str, None]:
Sounds fine to me! A little less specific, but also less room for error, and I think it makes sense based on the number of possible return types.

2022-10-05 21:16 UTC, spencer-skylight reviewed
One more quick comment - as long as you're modifying test cases, you might consider changing the ones that should throw exceptions to use `pytest.raises`. Right now, if the function calls _don't_ raise the expected exception, the test could still succeed when we'd want it to fail.

2022-10-06 15:21 UTC, bryan-skylight commented on phdi/fhir/utils.py
> +        raise KeyError(f"This resource does not contain a field called {field}")
Given that this error is related to the field we're extracting (e.g. a user wants to extract "name" from a Lab resource and it's not there) and not the element (e.g. The Patient's given name is "Sam") we should refer to this as the field and not the element, right? Or do I have those backwards?

2022-10-06 15:41 UTC, bryan-skylight commented on phdi/fhir/utils.py
> +    if no elements of the specified field have that use, none will be returned. If
Fixed in the latest commit.

2022-10-06 15:41 UTC, bryan-skylight commented on phdi/fhir/utils.py
> +) -> Union[Dict, List, str, None]:
Done!

2022-10-06 15:42 UTC, bryan-skylight commented on phdi/fhir/utils.py
> +    can be found, instead return a specified default value for the field.
Great call out! I've updated the docstring and would appreciate your feedback on the new language. Going to resolve this comment in favor of creating a new one should additional changes need to be made.

2022-10-06 15:42 UTC, bryan-skylight commented on phdi/fhir/utils.py
> +    :param require_use: (optional) Indicates if the 'use' is required. If True, then
Done!

2022-10-06 16:39 UTC, m-goggins commented on phdi/fhir/utils.py
>      if field not in resource:
In retrospect, I think I was confusing use and field. I was thinking of a scenario where someone includes a non-empty field, e.g. "name" and a non-empty resource "case", but name is not in the case resource. I see that is taken care of in the line just below this comment 😀

2022-10-06 18:26 UTC, bamader approved these changes

2022-10-06 18:26 UTC, bamader commented on phdi/fhir/utils.py
> +    element.
Super small nit: spacing on the param docstring lines after the first should be prefaced with two spaces

2022-10-06 18:26 UTC, bamader commented on phdi/fhir/utils.py
> +    This parameter is ignored if no use is specified.
Spacing thing here too

2022-10-06 18:26 UTC, bamader commented on phdi/fhir/utils.py
> +    This parameter is ignored if no use is specified.
I believe according to the style guide, the `index`, `use`, and `require_use` docstring lines should have second sentences of the form `Default: True.` specifying their default values.

2022-10-06 18:52 UTC, bryan-skylight commented on phdi/fhir/utils.py
> +    element.
Good call out! Most recent commit address this and the comment you left below.

2022-10-06 18:52 UTC, bryan-skylight commented on phdi/fhir/utils.py
> +    This parameter is ignored if no use is specified.
This has been added in the most recent commit. Thanks for flagging!

2022-10-06 18:57 UTC, merged