Upload parsing schemas endpoint
CDCgov/phdi pull request #790
Opened 2023-08-24 14:40 UTC by DanPaseltiner

# PULL REQUEST

## Summary
This PR expands the `/schemas` endpoint on the message parser to allow PUT operations so that users can upload new parsing schemas and update existing ones. Currently the service has the following behavior:

1. Return a `201` when a users uploads a new schema successfully 
2. Return a `200` when a user updates an existing schema. Not that updating existing schemas is only allowed when the `overwrite` parameter is set to `true` as a guardrail to prevent folks from accidentally overwriting data.
3. Return a `400` if a user requests to update an existing schema without setting `overwrite` to `true`.

We have request validation on schemas that get uploaded/updated via this endpoint to ensure they conform to the standard we expect.

## Related Issue
Fixes #https://github.com/CDCgov/phdi-azure/issues/262

## Additional Information
Anything else the review team should know?

[//]: # (PR title: Remember to name your PR descriptively!)

2023-08-24 19:03 UTC, emmastephenson approved these changes
LGTM! The examples look great too!

2023-08-24 21:19 UTC, BradySkylight commented on containers/message-parser/app/main.py
> +    "string", "integer", "float", "boolean", "date", "timestamp"
Do we need to change the ecr.json schema that we have as a default.  I think some of the data types were listed as 'number' instead of 'integer'?

2023-08-24 21:23 UTC, BradySkylight approved these changes
This is so nice to have!  Nice work Dan.  I just had one question/concern, that is more related to our default schema.

2023-08-25 16:07 UTC, DanPaseltiner commented on containers/message-parser/app/main.py
> +    "string", "integer", "float", "boolean", "date", "timestamp"
Nice catch. What are your thoughts on `float` v. `number`?

2023-08-25 17:28 UTC, DanPaseltiner commented on containers/message-parser/app/main.py
> +    "string", "integer", "float", "boolean", "date", "timestamp"
@BradySkylight just push a change to replace `number` with `float` in `ecr.json` based on our conversation. Can you confirm that this has been resolved from your point of view?

2023-08-25 18:35 UTC, BradySkylight commented on containers/message-parser/app/default_schemas/ecr.json
> +            "data_type": "float",
If this a coding system, this should be 'string' instead of float.  Weird I didn't catch this before!

2023-08-25 18:35 UTC, BradySkylight commented on containers/message-parser/app/default_schemas/ecr.json
> +            "data_type": "float",
IF this is a unit this should be a 'string'. Sorry I didn't catch this before.

2023-08-25 18:36 UTC, BradySkylight commented on containers/message-parser/app/default_schemas/ecr.json
> +            "data_type": "float",
This should be 'string' since it's a unit.  My bad!

2023-08-25 18:36 UTC, BradySkylight requested changes
A few bugs that I introduced are still there.  Sorry about that.  I called them out.

2023-08-25 19:46 UTC, BradySkylight approved these changes
LGTM

2023-08-25 19:54 UTC, merged