Raw Data Harmonization
CDCgov/phdi pull request #8
Opened 2022-08-05 20:39 UTC by bamader

This PR adds the harmonization functionality for the raw-data versions of the module (i.e. FHIR wrappers aren't currently written). Standardization and HL7 functionality are covered here, as well as unit tests for every function in the module. I went with a somewhat different directory structure than we initially discussed for harmonization, but nothing breaking: rather than put all the code, period, into a single `harmonization.py` file, I made a `harmonization/` directory in which there are a handful of underscore files (`_hl7`, `_standardization`) that group code based on its content. I thought that not only is this more maintainable for us because the code is more split out and modular, it's easier for a user to lookup things for a specific task than to sift through an entire mega module. Plus, it lets us cordon off the private helper functions that we decided not to expose to the user via an `__init__.py` file that imports everything that *will* be exposed at the top level.

2022-08-08 14:48 UTC, KennethSkylight commented on phdi/harmonization/_hl7.py
> +        # PID-7 - Date of Birth
Instead of comments, these magic numbers should be constants

2022-08-08 15:02 UTC, KennethSkylight commented on phdi/harmonization/_hl7.py
> +def _clean_hl7_batch(batch: str, delimiter: str = "\n") -> str:
@spencer-skylight what are your thoughts for docstrings docs for private functions? Personally I think they should be optional, but wanted to get your thoughts on this

2022-08-08 15:02 UTC, KennethSkylight commented on phdi/harmonization/_standardization.py
> +            # We were able to pull the phone # and corresponding country
97, 102, 106, and 117 are unnecessary comments

2022-08-08 15:03 UTC, KennethSkylight commented on phdi/harmonization/_standardization.py
> +    # Allow users to pass in either a string or list of strings
Redundant, you explained this in the params docstrings

2022-08-08 15:03 UTC, KennethSkylight commented on phdi/harmonization/_standardization.py
> +    # Return same type as user input
unnecessary

2022-08-08 15:11 UTC, KennethSkylight commented on phdi/harmonization/_hl7.py
> +        # PID-7 - Date of Birth
Actually, after looking at it again, I'm not sure if constants would really even help since they're specific and I don't think it would any more sense. So I don't think these need to be changed

2022-08-09 11:21 UTC, spencer-skylight reviewed
A few things that need to be updated:
* `phdi.fhir.harmonization.__init__.py` I think should have standardize_names and standardize_phones
* flake8 issues resolved

2022-08-09 11:21 UTC, spencer-skylight commented on phdi/harmonization/_hl7.py
> +        # If we reach a line that starts with MSH and we have
My 2c... I would tend to allow this kind of comment because it clarifies how the looping and next message detection works here.  I suspect the author had to think about this, and this way of viewing the looping logic made sense and could help future developers who use this code in the future.

2022-08-09 11:21 UTC, spencer-skylight commented on phdi/harmonization/_hl7.py
> +            # If the segment is not found, there is nothing to do
I'm not sure it's immediately clear to a developer coming in to this code that KeyError = segment not found so I find some value in leaving this comment.

2022-08-09 11:21 UTC, spencer-skylight commented on phdi/harmonization/_hl7.py
> +        # Conversion from \n to \r EOL characters is needed for hl7
IMO, this comment gives some context on why the EOL conversion is being done.

2022-08-09 11:21 UTC, spencer-skylight commented on phdi/harmonization/_hl7.py
> +        )
See comment above - we may want to remove use of the logging module.

2022-08-09 11:21 UTC, spencer-skylight commented on phdi/harmonization/_standardization.py
> +    # First, identify what country the input is referencing
I think the comments in this function are helpful for organizational purposes. Perhaps pulling these sections of the code into private helpers would be better although I'd leave it to Brandon to decide whether this in scope for the work we are doing here.

2022-08-09 11:21 UTC, spencer-skylight commented on phdi/harmonization/_standardization.py
> +    # Base cases: we always want to try the phone # on its own first;
I think most of the comments in this function are helpful for organizational purposes. I don't think they are required, but they help make the code more readable so my vote would be to leave them in.

2022-08-09 14:53 UTC, bryan-skylight commented on phdi/harmonization/_hl7.py
> +        # PV1-44 - Admisstion Date
typo: "Admisstion" -> "Admission"

2022-08-09 14:53 UTC, bryan-skylight commented on phdi/harmonization/_hl7.py
> +def standardize_hl7_datetimes(message: str) -> str:
Recommendation for a later PR: generalize this function such that it's not hardcoded like this. Allow the user to pass in a dictionary like {"pid": [7, 29, 33], "msh": [7]} and loop through the key:value pairs. They should also be able to specify the format that they want the timestamp in.

2022-08-09 14:53 UTC, bryan-skylight commented on phdi/harmonization/_hl7.py
> +            "Exception occurred while cleaning message.  "
There are two scenarios in which error handling needs to be conducted:

1. Manual mode, where an analyst is manually running code in a notebook and will be able to see any exceptions raised, and
2. Automated mode, where a pipeline has been built and the code is being run from a script where no one will see the error.

In the first case, I think we should just raise the exception and ensure that the error message is clear so the analyst can address the issue. No need for logging. In the second case, I think we need a much more robust approach to raising the error, beyond just `logging.exception`. As was noted during the LAC meeting, the raising of an error should be actionable, not just some message stored in a file somewhere.

For the purposes of this PR, I'd suggest just leaving this as is given that I believe the point of the PR is to port existing functionality over to the new taxonomy. I'd also add a TODO comment highlighting the need to update this to fit our new approach in the future.

2022-08-09 14:53 UTC, bryan-skylight commented on phdi/harmonization/_hl7.py
> +        # If we reach a line that starts with MSH and we have
I agree with Spencer. The code is clear to developers that are used to seeing this kind of loop, but our end users may not be as familiar. It's important to keep in mind who we're developing for and how tech savvy they may or may not be.

2022-08-09 14:53 UTC, bryan-skylight commented on phdi/harmonization/_hl7.py
> +    # Since our loop only adds messages to output when it finds
I think your comment here actually demonstrates why we need the comments above. I get the impression that lines 131-137 were clear to you and easily interpretable, but the intent of lines 142-143 was not as readily understood, which is why you feel some comments are necessary and others aren't. Our end users, and those who are likely to be reading our code, may have less exposure to code than you do and so both sections may not be very clear to them. This is why I advocate for airing on the side of verbosity in our comments.

2022-08-09 14:53 UTC, bryan-skylight commented on phdi/harmonization/_hl7.py
> +            # If the segment is not found, there is nothing to do
I agree with Kenneth here. There is only a single line of code in the `try` statement, and it's pretty clear what it's trying to do. And there is only one exception type being handled, so it's also clear what it's handling. I think we can remove this comment. 

But let's also keep in mind that this is PR is mostly geared towards just porting code over to the new taxonomy, albeit with some small changes. If we feel that a cleanup of the code is necessary, let's create a ticket and separate PR for that.

2022-08-09 14:53 UTC, bryan-skylight commented on phdi/harmonization/_hl7.py
> +        logging.debug(f"Segment {segment_id} not found in message.")
If you replace it with a comment, then the exception handler doesn't do anything and the exception would be raised, which removes the need for the `try/except` logic altogether. But again, see my comments about not overloading this PR.

2022-08-09 14:53 UTC, bryan-skylight commented on phdi/harmonization/__init__.py
> +from phdi.harmonization._hl7 import (
See my comment in the `_hl7.py` file about the use of underscore prefixes in file names.

2022-08-09 16:11 UTC, KennethSkylight commented on phdi/harmonization/_hl7.py
> +        # If we reach a line that starts with MSH and we have
My counterpoint to that is that our end users are just importing the packages, they aren't looking at our code itself, but just importing it and using it. 

People who contribute to our repo are going to be a different audience than those who import our packages.

2022-08-09 17:05 UTC, bamader commented
After looking through the opinions on comments here, I'm going to leave all of them in unless there was consensus that one should be removed or abridged. Without reiterating my (long) train of thought from slack, I find comments exceedingly important for developers and users. They're adding a lot of valuable context and information for both while presenting few if any downsides. I think that just because we _could_ get away with omitting a comment doesn't mean we _should_.

2022-08-09 17:19 UTC, KennethSkylight commented on phdi/harmonization/_hl7.py
> +        # Conversion from \n to \r EOL characters is needed for hl7
I just noticed that this repeated. So wouldn't the better fix to be to create a private function that is called `_remove_EOL` or something then we don't have to maintain the comments and the code in two places

2022-08-09 17:20 UTC, KennethSkylight commented on phdi/harmonization/_hl7.py
> +def _clean_hl7_batch(batch: str, delimiter: str = "\n") -> str:
Cool I'm fine with these docstrings for this private function, was just asking in general

2022-08-09 17:21 UTC, KennethSkylight commented on phdi/harmonization/_standardization.py
> +    # First, identify what country the input is referencing
I agree private helpers would make it better.

2022-08-09 17:25 UTC, KennethSkylight commented on phdi/harmonization/_standardization.py
> +    # Base cases: we always want to try the phone # on its own first;
To me, the comment is just repeating what the code is clearly saying. It's also laid out in the docstrings what is happening

2022-08-09 17:48 UTC, bamader commented on phdi/harmonization/_hl7.py
> +        # module, and doesn't impact conversion ability
Unfortunately it seems like this is a yes. I just spent some time combing over the HL7 package docs, and everywhere that they make invocations to parsing or even sending/receiving HL7 messages, there are always calls like `.replace('\r', '\n')`. It's never spelled out explicitly but the overwhelming frequency of their usage pattern makes me think we really do need this replacement :/

2022-08-09 17:53 UTC, bryan-skylight commented on phdi/harmonization/_hl7.py
> +        # module, and doesn't impact conversion ability
Wait, doesn't that prove my point? They're replacing `\r` with `\n` because they don't want to work with carriage returns either. Why are we doing this for them if they're already handling it?

2022-08-09 20:53 UTC, bamader commented on phdi/harmonization/_hl7.py
> +        # If we reach a line that starts with MSH and we have
We're opting to keep comment verbosity as well as comments that provide organizational, contextual, or even just summary information. As such, marking this as resolved.

2022-08-09 20:53 UTC, bamader commented on phdi/harmonization/_hl7.py
> +    # Since our loop only adds messages to output when it finds
Agreed, this is the same principle I share. Marking as resolved.

2022-08-09 20:57 UTC, bamader commented on phdi/harmonization/_hl7.py
> +            # If the segment is not found, there is nothing to do
I'm going to leave it in because if I hadn't worked with the HL7 module, I wouldn't know that `.segment()` is actually an instance-retrieving function that looks up with segment ID as an actual key. The comment isn't hurting anything and may clarify something for someone down the road.

2022-08-09 20:58 UTC, bamader commented on phdi/harmonization/_hl7.py
> +        # Conversion from \n to \r EOL characters is needed for hl7
I agree with Spencer. Because the actual conversion of EOL characters is in itself a one-line function call, making a full function for it feels bizarre. I prefer the inline comment.

2022-08-09 21:05 UTC, bamader commented on phdi/harmonization/_standardization.py
> +    # First, identify what country the input is referencing
I'm going to pass on a private helper here for now. We can revisit that later if we so choose, but I almost am of the opinion that it doesn't really need one. The function's purpose is to implement very basic country code standardization, which starts with figuring out what country is being referenced. If we pull that out (and pull out everything that's commented into a private helper), I would argue we lose the meaningful logic of how that process is done, _in the function where the user would expect to find it_. It would be like a series of appendix references in a book or a paper, like "see X, p. 259; X: do this thing, see Y, p. 135; Y: statement of Z, see Z, p.399". I think this is non-burdensome enough and centralied logically tha tit makes sense to keep it all here.

2022-08-09 21:08 UTC, bamader commented on phdi/harmonization/_standardization.py
> +            # We were able to pull the phone # and corresponding country
I'm going to leave them in because I spent a fair bit of time looking into the `phonenumbers.NumberParseException` and reading about what it did. I had to do that because it wasn't clear to me what the objective of calling `parse` in this case was and exactly how much `NumberParseException` covered. And leaving in the 117 because it's very likely the reader has scrolled past the docstring at the top and its nice for them to get reminded of why stuff is there without having to reference something else or scroll.

2022-08-09 21:09 UTC, bamader commented on phdi/harmonization/_standardization.py
> +    # Return same type as user input
Actually on second look here and the unanimity of some other stuff, I agree with you. Will delete this comment and the prior instance.

2022-08-10 20:45 UTC, spencer-skylight commented on phdi/fhir/harmonization/__init__.py
> +def standardize_names(
Can you move these functions to `standardization.py` and just import those functions from here, similar to how we did the base harmonization?

2022-08-10 20:50 UTC, KennethSkylight reviewed
A few questions and super nit picky stuff, but other than that looks good.

2022-08-10 20:50 UTC, KennethSkylight commented on phdi/harmonization/standardization.py
> +        # Start by removing all punctuation
lol this super nitpicky, but I think just `remove all punctuation` is fine

2022-08-10 20:50 UTC, KennethSkylight commented on phdi/harmonization/hl7.py
> +            segment.extract_field(field_num=field_num) is None
Using `!segment.extract_field(field_num=field_num)` may just work here because `None` and empty string are falsey.

2022-08-10 20:50 UTC, KennethSkylight commented on phdi/harmonization/hl7.py
> +                if len(segment) > field_num and segment[field_num][0] != "":
It's a little confusing to me what `segment[field_num][0]` is. Could we add a variable with a descriptive name to make it clear?

2022-08-11 10:53 UTC, spencer-skylight requested changes
I think the only real blocking comment for me is the slight restructuring of phdi.fhir.harmonization. A few other very minor things, and should be GTG!

2022-08-11 10:53 UTC, spencer-skylight commented on tests/harmonization/test_hl7_underscore_funcs.py
> +def test_default_hl7_value():
Very nitty, but I think I like the naming convention you used with the FHIR tests.  Could we call this test_hl7_helpers.py?

2022-08-11 13:19 UTC, bamader commented on phdi/harmonization/hl7.py
> +            segment.extract_field(field_num=field_num) is None
You're totally right about this. However, we made a decision (long before you joined the team so not like you'd have any way of knowing this) that we as a team aren't going to use implicit truthy and falsey comparisons. Instead we're going to write out the full explicit `is None` or `is empty` or whatever the condition check may be. We felt this was a bit more readable, so this is just continuing that practice.

2022-08-11 13:23 UTC, bamader commented on phdi/harmonization/hl7.py
> +                if len(segment) > field_num and segment[field_num][0] != "":
@spencer-skylight Can we change `field_num` to something like component, or is field already the right nomenclature? I want to make sure we're using the right terminology to address Kenneth's request here.

@KennethSkylight Basically this is an HL7 terminology minefield lol. An HL7 message is broken down into specific _segments_, which are things like PID, OBX, etc. A segment is an order-specific "list", in essence, of sub-fields that contain health-related information. I _believe_ the fields within a segment are actually just called _fields_ in a technical sense, but I could be wrong and they could be components. We just want to make sure we're using the right word here so that people familiar with HL7 will know what the variables mean (since we're making that assumption of familiarity for our user base).

2022-08-11 15:38 UTC, KennethSkylight commented on phdi/harmonization/hl7.py
> +            segment.extract_field(field_num=field_num) is None
Interesting, sounds good to me

2022-08-11 17:12 UTC, spencer-skylight commented on phdi/harmonization/hl7.py
> +                if len(segment) > field_num and segment[field_num][0] != "":
`field` is the correct nomenclature for this...
@KennethSkylight 's interpretation is correct, and to address his question, the pipe (|) character separates fields within a segment (e.g. name, gender, etc).  The carat (^) character separates components within a field (e.g. first name, last name, etc). There are also other characters that can further divide components into subcomponents - the ampersand (&), and separate repeated field values - the tilde (~).  

So I think the nomenclature is good. To make it slightly more clear what that value means, you could do something like this...
```suggestion
                component_num = 0  # The datetime value is always found in the 1st component
                field_value = segment[field_num][component_num]
                if len(segment) > field_num and field_value != "":
```

2022-08-11 17:42 UTC, bamader commented on phdi/fhir/utils.py
> +def get_field(resource: dict, field: str, use: str, default_field: int) -> str:
Yep done

2022-08-11 17:43 UTC, bamader commented on tests/harmonization/test_hl7_underscore_funcs.py
> +def test_default_hl7_value():
Sure thing

2022-08-11 17:51 UTC, bamader commented on phdi/harmonization/hl7.py
> +                if len(segment) > field_num and segment[field_num][0] != "":
Well, have to do a modified version to make sure `len(segment) > field_num` but otherwise this is good

2022-08-11 18:04 UTC, spencer-skylight approved these changes
LGTM!

2022-08-11 18:07 UTC, merged