Add tabulate function and tests
CDCgov/phdi pull request #85
Opened 2022-10-14 19:22 UTC by bamader

This PR adds functionality to tabulate data that has been extracted from the FHIR server. This will eventually replace the part of the `generate_all_tables` function that incrementally appends resource-level values into a list of data.

2022-10-17 11:44 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +    data = data.replace(r"^\s*$", np.nan, regex=True)
I spoke with Bryan about this late last week and decided we don't actually want to convert to pandas at this stage - just return the list of dicts. I think you would just need remove these lines - do you think the NaN handling could wait until we add support for `include_unknowns`?

2022-10-17 21:30 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
>      :param schema: A schema specifying the desired values to extract,
Add :return: param

2022-10-17 21:30 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
> +            headers = sorted(list(values_from_resource.keys()))
For my own understanding, why are we sorting the headers?

2022-10-18 12:18 UTC, bamader commented on phdi/fhir/tabulation/tables.py
>      :param schema: A schema specifying the desired values to extract,
Sorry, what is this in reference to? The `apply_schema_to_resource` function that this re-formatted comment applies to already has a `:return:`, and the function I added in `tabulate_data` was written with a `:return:` as well.

2022-10-18 15:47 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
> +            headers = sorted(list(values_from_resource.keys()))
Got it, thank you for explaining. I think you're definitely right about `sorted() `adding clarity. I could be wrong on this, but I was under the impression that `.keys()` returns returns the list in insertion order as of [Python 3.7](https://docs.python.org/3/library/stdtypes.html?highlight=keys#dict-views)(?).

For 2, I am wondering if users are expecting the data to come back in roughly the same order that they would see in a resource rather than alphabetical. I am okay with leaving it as alphabetical until we have user research, but maybe we could add it to our list of research questions for this BB? 

side note: Should we have a doc to store research questions as we make modifications to a BB?

2022-10-18 17:32 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +            headers = sorted(list(values_from_resource.keys()))
I looked up the return type and found `set()` but it very well could be list (version changes and all that).

Re: 2: I personally think alphabetical is the best ordering for the end-user (particularly given that FHIR's nested structure could lead to differing placement of some nested fields in unexpected place), but I think you raise a good point that users might have a different expectation. I would love to get that added to some research docs, but in the mean time I vote for leaving it at alphabetical.

2022-10-18 17:51 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
> +            headers = sorted(list(values_from_resource.keys()))
Sounds good to me!

2022-10-18 17:52 UTC, m-goggins approved these changes

2022-10-18 22:36 UTC, spencer-skylight requested changes
The changes with the new schema we discussed have been merged! This is ready to refactor.

2022-10-19 18:49 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +    :param schema: The schema of columns and values to apply to the
I actually rewrote the code in a way that allows `tabulate_data` to just take the whole schema and let `apply_schema_to_resource` do the work of sifting through particular columns. That way we have a single workhorse function responsible for identifying resource types, columns, and the like from the schema as they apply to FHIR resources.

2022-10-19 20:37 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +                col_in_table = field.lower().strip().replace(" ", "_")
I would bet there's a pretty rare output type that _shouldn't_ just have lower case and underscores used as the default. I think we could change this in the future if we needed, but I would honestly say from an analyst's perspective it's probably best practice to use lowercase column names in a table and to avoid white spaces.

2022-10-19 20:38 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +            for field in table.get("columns", []).keys():
Great calls on both points 😎

2022-10-19 20:40 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +            for field in table.get("columns", []).keys():
Yeah we probably should. The way I've been thinking about it mentally is that a "field" is what the property is called when it's associated with a FHIR resource or otherwise not yet in a tabular format. It becomes a "column" when put into a table or otherwise tabulated. I don't know if we need to write that anywhere in the code, but at the very least that kind of usage should probably be something we make consistent.

2022-10-19 20:42 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +    for _, table in schema.get("tables", {}).items():
I believe that would make `table` a _key_ to the dictionary of tables instead of a value. So to access an actual table in the schema's table set, I would have to write `schema["tables"]["table"]`. I went with the `_, table` approach coupled with `.items()` because the underscore means the keys to `schema["table"]` won't be saved at all, but the values will still be stored in `table` so I don't have to access anything else nested.

2022-10-19 20:43 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +    for _, table in schema.get("tables", {}).items():
same as above comment

2022-10-19 20:47 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +                col_in_table = field.lower().strip().replace(" ", "_")
OK, you're probably right.

2022-10-19 20:49 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +    for _, table in schema.get("tables", {}).items():
You're absolutely right. What about using `schema.get("tables", {}).values()`?

2022-10-19 20:50 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +            for field in table.get("columns", []).keys():
By this way of thinking, it should probably be called a "field" in the schema. I'm thinking we should put it to the SDK team to debate and make a decision. Thoughts?

2022-10-19 20:58 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +        if resource.get("resourceType", "") == resource_type:
I think we could technically have two tables defined in the same schema for the same resource, which would cause problems for this approach.  For example, what if we want to have a table for lab observations, and another for growth chart observations? I think it would be better to leave table selection/identification to the calling function.

2022-10-19 20:58 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +            for field in table.get("columns", []).keys():
By this way of thinking, it should probably be called a "field" in the schema. I'm thinking we should put it to the SDK team to debate and make a decision. Thoughts?

2022-10-19 21:26 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +    for _, table in schema.get("tables", {}).items():
Sure, I can do that

2022-10-19 21:27 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +            for field in table.get("columns", []).keys():
Oh I guess I think of it as more columnar-related in the schema. I think calling it column in the schema makes sense more from an intuitive perspective, but the schema is used to define the _columns_ that will occur in the output table. Maybe what this conversation is revealing is that we might need to have a larger conversation with the SDK team as you proposed, but that might also be something Bryan is involved in for nomenclature and user accessibility reasons--would you be okay not counting this then as a blocker to this PR?

2022-10-19 21:49 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +            for field in table.get("columns", []).keys():
Nope, not a blocker. I like thinking on next steps.

2022-10-20 12:08 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +        if resource.get("resourceType", "") == resource_type:
That's a really fair observation. I spent some time thinking about a programmatic splitting solution to this problem last night before I realized you were probably talking about something simpler. I thought you were asking for an `apply_schema_to_resource` function that could programmatically and intelligently decide which of two observation tables an observation resource should belong to, and that was giving me fits because it would involve a lot of pre-specifying work on the user that would defeat the point of doing this programmatically (I also didn't see any reasonably effective way to do that). But, what I think you're _actually_ asking for is that if a schema contains multiple tables for the same resource, grab all of the fields associated with all of those tables, not just the first occurring table (i.e. delete the `break` statement on line 93). This is way more effective and lets the calling function and user decide how to split up those fields after they're retrieved.

2022-10-20 15:45 UTC, bryan-skylight requested changes
This is a great start, but I've got some things that I'd like to see changed before we merge this. Namely, I think we need to revisit the schema structure because I think something is getting lost in translation.

2022-10-20 15:45 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
> +            for column_name, column in table.get("columns", {}).items():
Again, here I'd recommend changing to `column_name` and `column_params`

2022-10-20 15:45 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
> +                    selection_criteria = column["selection_criteria"]
Shouldn't we use `.get()` here to be consistent? What if the schema doesn't specify it?

2022-10-20 15:45 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
> +                path = column["fhir_path"]
We should use `.get()` here as well to ensure we don't get an unexpected `KeyError` if it's not present.

2022-10-20 15:45 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
> +                    data[col_in_table] = ""
Why are we using strings as our default empty value? Shouldn't this be `None`?

2022-10-20 15:45 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
> +                    data[col_in_table] = str(value)
Again here, why are we converting everything to string? If this is a carryover from the issues we were having with the Parquet writer, I'd advocate forcing the `load` function (or whatever we're going to call the function that persists the data) to deal with that. We shouldn't be preemptively passing back data that masks the datatype of a value.

2022-10-20 15:45 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
>  def apply_schema_to_resource(resource: dict, schema: dict) -> dict:
This function should be renamed in my opinion. There's more to the schema than just the selection criteria, and this function is only extracting the value from the resource. I think we should rename it to something that reflects that.

2022-10-20 15:45 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
> +        resource_type = table.get("resource_type", "")
This approach seems to reinforce the idea that a table will contain only a single resource, which isn't true. We'll need to update the schema structure and rethink this approach.

2022-10-20 15:45 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
> +    subsequent lists are each an extracted data element represented
I don't think this accurately depicts what is returned. Each subsequent list should be a row, right? Meaning it would hold many extracted data elements? It might make more sense to say ", and each subsequent list contains the data extracted from a FHIR resource, according to the fields specified in the schema, which represent the rows of data" or something like that.

2022-10-20 15:45 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
>      :param return: List of resources with removed nulls.
Can we make this more descriptive? Something like `:param return: A list of FHIR resources that meet the include_null specification of the schema`

2022-10-20 15:45 UTC, bryan-skylight commented on tests/fhir/tabulation/test_fhir_tabulation.py
> +    assert len(extracted_data["entry"]) + 1 == len(tabulated_data)
nit: Can we change this to the following?

```python
assert len(extracted_data["entry"]) == len(tabulated_data[1:])
```

Both solutions achieve the same goal, but I think this more clearly demonstrates what we're testing.

2022-10-20 15:57 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +    and a schema. The given schema should define a table for each
Spencer and I talked on Tuesday when you were out and actually decided to push forward with the assumption that table = resource as a desirable one. There were a lot of angles covered, but some big points of the discussion came down to one of the following: 1) it being the user's / caller's responsibility to execute the joins and unions they want to see on their data after the data has been tabulated, or 2) if that's something we want to handle, this function as presently scoped isn't the right place to try to handle unions and joins and so it's actually advantageous from a "get things working" perspective to limit each table to holding the fields for a single resource. FWIW I also do think the schema structure has changed somewhat since you've been out so we probably need to go over that too.

I think more generally we need to have a larger conversation around what tabulation and schema work will look like because I feel like I've been given a new moving target for "schema" and "tabulation" every day this PR has been open. We're all clearly operating with some sort of different vision for what the work should be so I think we need to define that better before this PR work continues.

2022-10-27 12:58 UTC, spencer-skylight requested changes
The code looks great - I like the structure you've created to meet the requirements! Most of the non-nitpicky stuff is just edge case handling.

The only other thing I had to point out is for @m-goggins 's invalid value handling code, I think she will need to do almost everything that `tabulate_data` does with the exception of build the `data` dictionary that gets returned at the end. Instead she'll just drop entries in the `extracted_data` parameter. The way the code is written now, I think she would need to copy and paste a lot of the tabulation logic, so we probably should refactor this to allow for better code reuse to support her changes.

2022-10-27 12:58 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +                ref_loc = directions_by_table[table_name]["reverse"][rtype]
If `directions_by_table[table_name][direction][resource_type] is made into a list as suggested above, this would become:
```python
                for ref_loc in directions_by_table[table_name]["reverse"][resource_type]:
```

2022-10-27 12:58 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +        rtype = resource.get("resourceType", "")
nit: Should we make a more descriptive variable name?

2022-10-27 12:58 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +            ref_dicts.get(table_name, {}).get(anchor_type, {}).items()
It's possible that we could have included resources that are of the anchor resource type that we would not want to build rows for. There is a field in the response `entry.search.mode` that I think we'll need to use to make sure we are selecting only the primary search results.

2022-10-27 12:58 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +            for _, column_params in column_items:
Nit: You could use column_item.values() here to avoid the throwaway variable.

2022-10-27 12:58 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +                    [direction, ref_path] = column_params["reference_location"].split(
Nit: This might be a good spot to refactor code into another internal function to make this slightly more modular.

2022-10-27 12:58 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +        )
Just a minor refactor suggestion for readability.
```suggestion
    for table_name, table_params in schema["tables"].items():
        # Get the columns from the schema so we always iterate through
        # them in a consistent order
        column_items = table_params.get("columns", {}).items()
        headers = [column_name for column_name, _ in column_items]
        data[table_name] = [headers]
        anchor_type = table_params.get("resource_type", "")
```

2022-10-27 12:58 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +                    ] = ref_path
edge case - what if the same resource type is referenced twice from the same resource type? For instance:

```yaml
resource_type: Practitioner
columns:
  Interpreted Reports:
    fhir_path: DiagnosticReport.code.text
    reference_location: reverse:DiagnosticReport:resultsInterpreter
  Performed Reports: 
    fhir_path: DiagnosticReport.code.text
    reference_location: reverse:DiagnosticReport:performer
```

Thinking maybe you could make this element reference an array of `ref_path`s?
```suggestion
                    if directions_by_table[table_name][direction].get(referenced_resource_type) is None:
                        directions_by_table[table_name][direction][referenced_resource_type] = []
                    directions_by_table[table_name][direction][
                        referenced_resource_type
                    ].append(ref_path)
```

2022-10-28 16:00 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +def tabulate_data(extracted_data: dict, schema: dict) -> dict:
Yep you're absolutely right. Removing all referenced adjectives.

2022-10-28 16:09 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +    :param schema: A user-defined schema featuring some number
Yeah this makes sense. I'll check out how we refer to it across this file and standardize.

2022-10-28 16:16 UTC, bamader commented on phdi/fhir/tabulation/tables.py
>  def apply_schema_to_resource(resource: dict, schema: dict) -> dict:
Yep! We no longer have need of this function. I would actually love to delete it, along with the code for `generate_schema_table` and `generate_all_tables`, because they're cluttering up this file, but I don't want to do so without some okay from @bryan-skylight and some notice to the cloud implementation workstream.

2022-10-28 16:18 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +                referenced_anchor = parse_function(resource)[0]
Good call. I totally forgot to just sub this code for the helper function I wrote anyway.

2022-10-28 16:20 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +        rtype = resource.get("resourceType", "")
Sure thing 👍

2022-10-28 16:22 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +            for _, column_params in column_items:
Actually here, I don't think we can. A few lines above, we get the list of tuples for the schema in `column_items` so that we can extract the headers and then process the schema's columns in the same order. If we replaced the header extraction with a `.keys()` and this with a `.values()`, there's no guarantee that both sets come back in the same order because of the way Python stores dictionaries. So although we do have a throwaway here, I think it actually is necessary to preserve the ordering we grabbed.

2022-10-28 16:54 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +        )
I like this! Will implement.

2022-10-28 18:06 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +                    [direction, ref_path] = column_params["reference_location"].split(
Yeah that's a good idea, I'll break this out and add some testing around it

2022-10-28 18:36 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +                    ] = ref_path
The code can actually already account for this! The part that you've commented on is _just_ responsible for creating the directions of association between the various resource types. If one resource references an anchor multiple times (in the way you illustrated), it actually doesn't matter that we're only processing one of those ref_paths. The `build_reference_dicts` just assembles the resources themselves that are connected to the anchor in an aggregated fashion--the `ref_path` is just used to figure out what the connection to the anchor is. This means that when we actually get to `tabulate`, because we're iterating back over the _schema columns_ rather than the ref_paths, the proper value can still be looked up and extracted. On the other hand, if we were to implement this change and make the reverse directions hold a list of ref_paths, the `build_reference_dicts` function would interpret those as two separate resources, which would lead to every resource linked to anchor being added to the reference dictionary twice. This in turn would cause the tabulate function to double report every value that was a reverse reference.

To back up everything that I'm saying, I just modified the test cases I have locally and ran them through. I asked for another reverse reference Observation (to make sure nothing was excluded or double counted) in the schema, and then without changing algorithm logic at all, checked the output. The code successfully added the new column with the new information from the additional observations without double counting anything. So, I think this case is already handled and not a concern with the algorithmm.

2022-10-31 18:12 UTC, bamader commented
In addition to the re-review, we also have to decide if we want to delete `apply_schema_to_resource` and the related `generate_table` functions here as well. I would be in favor of removing the former but leaving the latter until the write functionality is also in place.

2022-10-31 19:00 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +            ref_dicts.get(table_name, {}).get(anchor_type, {}).items()
We created a ticket to address this at a later date:
https://app.clickup.com/t/3rgqa07

2022-10-31 19:30 UTC, spencer-skylight approved these changes
LGTM!

2022-11-01 13:06 UTC, spencer-skylight commented
> In addition to the re-review, we also have to decide if we want to delete apply_schema_to_resource and the related generate_table functions here as well. I would be in favor of removing the former but leaving the latter until the write functionality is also in place (not least because not only do we not use the apply_schema_to_resource function for anything productive any more, but maintaining is also forcing us to maintain cluttered and out dated tests assets).

My vote is to restore `apply_schema_to_resource` to it's original code, and delete all old code as a part of the [ticket](https://app.clickup.com/t/3pc6e55) to re-implement `generate_all_tables_in_schema`. While I don't think it's strictly necessary to back out the changes this PR made to `apply_schema_to_resource`, but doing so would make things cleaner.

2022-11-01 14:40 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
> +    for table_name, table in schema.get("tables", {}).items():
This conversation has been marked as resolved, but neither of the following two conditions were met:

1. The change was implemented, or
2. An explanation of why the change won't be implemented is provided.

I know we've never officially declared those as criteria for any kind of official process, but I think it's good practice to not simply resolve comments without one of those two criteria taking place.

2022-11-01 14:41 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
> +            for column_name, column in table.get("columns", {}).items():
Same comment as above about resolved conversations with no indication of why.

2022-11-01 14:42 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
> +                path = column["fhir_path"]
Same comment as above about unresolved comments.

2022-11-01 14:43 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
> +                    data[col_in_table] = ""
Same comment above about unresolved comments.

2022-11-01 14:44 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
> +                    selection_criteria = column["selection_criteria"]
Same comment as above about unresolved comments.

2022-11-01 14:48 UTC, bryan-skylight approved these changes
So, I haven't done a full analysis of the PR because GitHub seems to really struggle to show the appropriate information when PRs get this big (97 comments and 20 commits for, effectively, 2 files). If issues arise, we can fix them in the future. but this PR is too big and I just want to get it closed.

2022-11-01 17:11 UTC, m-goggins approved these changes
Looks good to me per the conversation on slack about submitting and re-adjusting as needed.

2022-11-01 17:20 UTC, merged