Add drop_unknown function and tests
CDCgov/phdi pull request #89
Opened 2022-10-18 21:04 UTC by m-goggins

This PR adds functionality and tests for dropping unknown resources from FHIR responses when tabulating data; it is very similar to the drop_null PR (#87)

2022-10-19 18:55 UTC, spencer-skylight requested changes
Looking good! I had a few small fixes and suggested optimizations.

2022-10-19 18:55 UTC, spencer-skylight commented on tests/fhir/tabulation/test_fhir_tabulation.py
> +            pathlib.Path(__file__).parent.parent.parent / "assets" / "test_schema.yaml"
Could you code this against `valid_schema.yaml`, which has the new schema structure? You may also need to update the drop_null logic as well.

2022-10-19 18:55 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +            if not resource[i]:
I think this would also capture null-string resources.  This should probably be `if resource[i] is None:`.

2022-10-19 18:55 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +    for resource in response[1:]:
This will loop over all resources which will be expensive.  I think we should only looping over data if `len(indices_of_unknowns)>0`... That way, if we know we don't want to drop any data, we don't have to scan the dataset.

2022-10-19 18:55 UTC, spencer-skylight commented on tests/fhir/tabulation/test_fhir_tabulation.py
> +    fhir_server_responses_1_null = [
Additional suggested test cases:
* Columns that should not drop nulls do not cause rows to be dropped for unknown values.
* Null (empty string) values are not dropped.

2022-10-19 21:02 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
> +    for resource in response[1:]:
I see your point. My understanding was that this function would only ever be called if we already knew from the schema that the user wanted to drop at least 1 column if unknown, but maybe that assumption is wrong?

2022-10-19 21:48 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +    for resource in response[1:]:
That's a fair point. I think we can do that in our code, but the user could also make use of the function directly and we're not sure what they will do. It's probably reasonable to expect they would do the same check, but also an easy change for us to make and it could improve perception of performance in PHDI. Since it's simple and I'd argue the pros outweigh the cons, I'd probably just add it, but I don't think it's a blocker.

2022-10-20 15:39 UTC, m-goggins commented on tests/fhir/tabulation/test_fhir_tabulation.py
> +            pathlib.Path(__file__).parent.parent.parent / "assets" / "test_schema.yaml"
Will do!

2022-10-20 16:52 UTC, m-goggins commented on tests/fhir/tabulation/test_fhir_tabulation.py
> +    fhir_server_responses_1_null = [
I understand the 2nd bullet and implemented, but I'm not understanding the 1st one. Is that for the drop_null function; don't drop unknowns when we intend to only drop nulls?

2022-10-21 16:06 UTC, bryan-skylight requested changes
Thanks for putting this together. I really like your implementation for dropping resources; very clean! I do have some questions about the approach though which I think we'll need to clear up before merging.

2022-10-21 16:06 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
> +                if resource[i] is None:
This is a nice, clean implementation, and I really like it! I think this line, though, would effectively make this function the same as `drop_null`, right? I think this function is the more complicated one because we need a set of known values that constitute "unknown" such as "UNK", "UNKNOWN", "Did not ask", "DNA", etc. I'm wondering if we add a parameter that allows a STLT to specify what they consider to be "unknown" and use those values to filter.

2022-10-21 16:06 UTC, bryan-skylight commented on tests/assets/valid_schema.yaml
> +incremental_query_count: 1000
I believe Spencer just merged a PR that includes this file as well, so I'd recommend making sure to merge `main` into your branch when you make updates.

2022-10-21 16:06 UTC, bryan-skylight commented on tests/fhir/tabulation/test_fhir_tabulation.py
> +    # Drop null resource
I'm not sure that `drop_unknown` should drop resources if a field is `None`. See my comment above about this.

2022-10-21 17:34 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
> +def drop_unknown(response: list, schema_columns: dict):
Makes sense to me and I will keep this in mind for future functions

2022-10-21 17:38 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
> +                if resource[i] is None:
It is very similar to drop_null but not exactly the same. After doing some research and checking with Spencer, we determined that an unknown value in a FHIR server would return as None (or really just not present, which would become None in a dictionary) whereas a null value would return as an empty string. 

To your second point, I think that is really important. Perhaps we could have an additional field in the schema where users can list the unknown values for a particular column?

2022-10-21 17:38 UTC, m-goggins commented on tests/assets/valid_schema.yaml
> +incremental_query_count: 1000
Yeah, I forgot to do that until afterwards.

2022-10-25 18:38 UTC, spencer-skylight reviewed
I think this is a great change in approach!

Something to consider: if we just apply filtering when "invalid_values" is set, we could probably avoid having the "include_invalid" boolean setting. Does keeping "include_invalid" make things more clear to the user?

2022-10-25 18:38 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +def drop_invalid(data: list, schema_columns: dict):
Ideally the declared data type should be more specific: `List[list]`. Also add declared data type for return value to the method signature.

2022-10-25 18:38 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +    Removes resources from FHIR response if the resource contains an invalid value for
Could you add a little more to the documentation about how `invalid_values` is defined and used?

2022-10-25 18:38 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +        if not schema_columns[column]["include_invalid"]
I think it _should_ be safe to check `schema_columns[column]` directly here because of the way you are looping over `schema_columns`. However, should we allow a default value? i.e., `if not schema_columns[column].get("include_invalid",True)`

2022-10-25 18:38 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +        indices_of_invalids[data[0].index(column)] = schema_columns[column][
I think we'll only try to pull "invalid_values" when "include_invalid" is False. In this case, we'd expect "invalid_values" to be set to something. If the schema didn't set "invalid_values", I think the code would raise a generic `KeyError`. Do you think we should check for this case and raise an error that is more descriptive to the user, like...
```python
try:
  indices_of_invalids[data[0].index(column)] = schema_columns[column]["invalid_values"]
except KeyError as ke:
  raise KeyError(f"Schema column {column} must define 'invalid_values' because 'include_invalid' is set to False") from ke
```

2022-10-25 20:00 UTC, m-goggins commented
> I think this would be a good point if we were only handling user-generate schemas, but I am curious about how we might implement this in the web version. My assumption was that users would have to check a box if they want to drop invalid values and then something would prompt them to enter the invalid values. If we proceed in that direction, I think we should also make the change from "include_invalid" to "drop_invalid" in the schema. It makes more sense to me to say "Yes, I want to drop invalid values, here are the invalid values I want to drop" rather than "No, I do not want to include invalid values, but here are the ones I want to drop." Does that make sense?

2022-10-25 20:11 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
> +        if not schema_columns[column]["include_invalid"]
Yes, I like this approach.

2022-10-25 20:28 UTC, spencer-skylight commented on tests/fhir/tabulation/test_fhir_tabulation.py
> +    fhir_server_responses_1_null = [
Let's say we don't want to drop patients without a first name (i.e. include_invalid = True). We should make sure that patients without a first name are not dropped. The code will not drop them obviously since we are using invalid_values, which isn't read or used when include_invalid = True. But I thought we may just want to add it as an edge test case.

2022-10-25 20:31 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
> +        indices_of_invalids[data[0].index(column)] = schema_columns[column][
Yes, that's a good catch and definitely something we want to alert users to. I'll make the change.

2022-10-25 20:45 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +        indices_of_invalids[data[0].index(column)] = schema_columns[column][
I did some research about this earlier today, and found that adding the `as ke` and `from ke` to this is unnecessary. You could still consider raising an exception with a more detailed description. Pretty nit-picky, I wouldn't consider this a blocker.

2022-10-25 20:47 UTC, spencer-skylight commented
> I think this would be a good point if we were only handling user-generate schemas, but I am curious about how we might implement this in the web version. My assumption was that users would have to check a box if they want to drop invalid values and then something would prompt them to enter the invalid values. If we proceed in that direction, I think we should also make the change from "include_invalid" to "drop_invalid" in the schema. It makes more sense to me to say "Yes, I want to drop invalid values, here are the invalid values I want to drop" rather than "No, I do not want to include invalid values, but here are the ones I want to drop." Does that make sense?

This is a good point. I do think in the web version it _probably_ makes more sense to pair a checkbox with a list of values rather than just having a list labeled "invalid values". It's not clear in that case what they actually do. I'm good with just keeping the two separate settings.

2022-10-26 11:48 UTC, spencer-skylight requested changes
So close! Sorry 2 minor things:
* Could you move the invalid test case (drop_invalid=true without invalid_values) to a new schema file? As of now, valid_schema.yaml is technically invalid.
* Add a new row where patient last name is None and make sure it is _not_ filtered since drop_invalid = false for the last name column (this will take care of my last remaining comment as well).

2022-10-26 15:57 UTC, m-goggins commented
I moved the invalid schema to a new test file called `invalid_schema_no_invalid_values` and I believe the test starting on line 415 of the test file (under `User-specified values are not dropped if drop_invalid is False`) takes care of the second test you mentioned.

2022-10-26 17:32 UTC, spencer-skylight approved these changes
LGTM!

2022-10-26 18:17 UTC, bamader requested changes
Mostly there. There's a couple points of clarification in one of the docstrings that I think needs cleaned up. Also, I think we need Bryan to weigh in on whether this is an appropriate point to use pandas, as with a previous PR he's said he'd like to avoid using it to minimize overhead on users.

2022-10-26 18:17 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +    :param data: List of resources returned from FHIR API.
Is this function intended to be used before or after the data is tabulated? Right now, the input `data` is a list of lists, which suggests that it's post-tabulation, but the comment for `data` says it's a list of resources returned from the FHIR API, which actually provides a bundle (a dict).

2022-10-26 18:17 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +    :param return: List of resources with invalid resources.
Should this be "...with invalid fields"? Resources shouldn't have invalid resources, right?

2022-10-26 18:17 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +                "invalid_values"
Is this assuming conversion to a pandas data frame? I think Bryan said he wants to explicitly avoid `DataFrame` conversion at this point to avoid overhead.

2022-10-26 18:45 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
> +    :param return: List of resources with invalid resources.
Yes! I changed to "List of resources with valid fields"

2022-10-26 18:50 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
> +                "invalid_values"
No, this operates without Pandas, working on the list of lists. Here I am creating a list of indices (in a list of data) to check for invalid fields. So if we have data that look like:
`
data = [
    ["Patient ID", "First Name", "Last Name", "Phone Number"],
    ["some-uuid", "John", "Doe", "123-456-7890"],
    ["some-uuid2", None, "Lastname", None],
    ["some-uuid2", "Firstname2, "Lastname2", 123-456-7890],
]
`

And I know from the schema that the user wants to drop resources if the Phone Number column is invalid (Null/None), from the code above I would know to only check index 3 for Phone Number in each of the rows of data after the headers one. Does that make sense?

2022-10-26 19:01 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
> +    :param data: List of resources returned from FHIR API.
No, this function is intended to happen within `extract_data_from_fhir_search_incremental`, which I am now seeing will return a list of dictionaries rather than a list of lists, as you pointed out. 


 The thinking behind inclduing this as part of  `extract_data_from_fhir_search_incremental` is that we want the functions to be modular so if someone only wants to extract data and they provide a list of invalid_values, they should be able to extract it as they want without going through tabulation. It seems that this function needs to be updated to work on a list of dictionaries rather than a list of lists.

I am still reviewing your tabulation code, and I am now seeing

2022-10-26 19:12 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +                "invalid_values"
That makes perfect sense to me! My question around pandas was based on a completely boneheaded assumption on my part--I saw a `.index()` method and was like oh that must be a data frame because nothing else in Python has _ever_ implemented a method with _that_ name 😝 . So yeah, that's on me and the code here is totally fine.

2022-10-26 19:14 UTC, bamader commented on phdi/fhir/tabulation/tables.py
> +    :param data: List of resources returned from FHIR API.
Ahh I see. Yeah, the data won't become a a list of lists until after tabulation (and even then, it'll actually be a dictionary where the keys are table names as defined in the schema and the values are lists of lists), so we should update this function to work on either a list of dictionaries (representing a list of resources) _or_ a FHIR bundle (which we know will always have a field `entry` which holds a list of resources).

2022-10-28 19:16 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
> +    :param data: List of resources returned from FHIR API.
After looking into the extraction via querying and considering that LAC has not indicated a need for working with FHIR-formatted data, we're moving to drop invalids after tabulation for now and revisit drop invalid values after extraction. I think my latest changes address the expected data coming out of the tabulation work.

2022-10-29 12:55 UTC, spencer-skylight requested changes
A few minor things to review in comments, and I think you can also delete the drop_nulls function. It should be replaced by this, and is no longer covered by unit tests.

2022-10-29 12:55 UTC, spencer-skylight commented on tests/assets/valid_schema.yaml
> +        fhir_path: Patient.name.famil
You are missing a `y` here.

2022-10-29 12:55 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +        ]
`get()` won't throw an exception if nothing is found at that index, but it will return None. I'd suggest using a direct index for anything that you expect will always succeed, and give a default if you are handling a case that you later expect to be valued.
```suggestion
    for table in schema.get("tables",{}):
        invalid_columns_to_drop[table] = [
            column
            for column in schema["tables"][table].get("columns", {})
            if (
                schema["tables"][table]["columns"][column].get("invalid_values")
            )
        ]
```

This should
* avoid a TypeError: NoneType object is not iterable error if "tables" or "columns" are empty
* Use a slightly more readable syntax when we (developers) are confident a dict index exists
* throw a KeyError if table or column doesn't exist (which they always should since you are iterating over them)
* .get("invalid_values") will evaluate to None if it isn't values which works fine when checking for presence of that configuration

2022-10-29 12:55 UTC, spencer-skylight commented on phdi/fhir/tabulation/tables.py
> +            )
Similar suggestion as the dictionary indexing described above...

2022-10-31 16:00 UTC, spencer-skylight approved these changes
LGTM!

2022-11-01 18:49 UTC, m-goggins commented
This PR might be in the same boat as the tabulate_data one, where it has many out-of-scope changes now. I am wondering if we would consider moving it forward as is and opening new tickets/PRs for further modifications. @bryan-skylight @bamader

2022-11-02 15:48 UTC, bryan-skylight approved these changes
This looks good to me. Like I said, I really like your approach here. I have on nit-picky change I'd like to have implemented before merging (the spacing in the docstring), but otherwise it's good to go.

With that said, I also offered an alternative approach to the one you implemented. It's the same concept, and still your code, it just cleans it up a bit and removes one of the `for` loop blocks. Feel free to implement it if you'd like, or don't. I think it makes the code a little more clear and clean, but it doesn't change anything functionally.

2022-11-02 15:48 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
> +    :param schema: A schema of columns and values to apply to the
nit: we need a standardized description for the schema parameter. I've opened a [ticket in ClickUp](https://app.clickup.com/t/3qve7j5) for this as it's out of scope for this PR.

2022-11-02 15:48 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
> +
If I'm reading these two `for` loops correctly, it appears that we're looping over the columns in each table in the schema and identifying which columns should be dropped twice. The first loop will give us an object that looks something like the following.

```python
invalid_columns_to_drop = {"table1A": ["col1", "col3"], "table2A": [], "table3A": ["col4"]}
```

The next `for` loop is getting the invalid values for any given column. This gives us something like the following:

```python
# note that the indexes are off by 1 from the column names
indicies_of_invalids = {"table1A": {0: ["unknown"], 2: ["unknown", "unk", None]}, "table3A": {3: [None]}}
```

Both of these for loops require looping over the schema to get the information, so I'm wondering if we can just combine them into something like this:

```python
invalid_values_by_column_index = {}
for table in schema.get("tables"):
    columns = schema["tables"][table]["columns"]
    invalid_values_by_column_index[table] = {i: columns[col].get("invalid_values") for i,col in enumerate(columns) if columns[col].get("invalid_values", [])}
```

This would give us something that looks like this:

```python
invalid_values_by_column = {"table1A": {0: ["unknown"], 2: ["unknown", "unk", None]}, "table3A": {3: [None]}
```

This approach should make the code more performant (not that I think that'll be a huge issue here) and a little cleaner, and it should work with the third `for` loop below.

2022-11-02 15:48 UTC, bryan-skylight commented on phdi/fhir/tabulation/tables.py
> +
Using the above approach, this code block would change to:

```python
for table in data.keys():
    if len(invalid_values_by_column_index[table]) > 0:
        for resource in data[table][1:]:
            for index, invalid_values in invalid_values_by_column_index[table].items():
                if resource[index] in invalid_values:
                    data[table].remove(resource)
                    break
```

2022-11-02 17:51 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
> +
I think it only loops over the schema once; the second time it's looping over the `invalid_columns_to_drop` list that came out of the first loop. But overall, I agree with your point that we only need to loop once and can grab all the information we need. I'm not sure what the schemas for STLTs will look like but better to be on the safer side.

2022-11-02 17:52 UTC, m-goggins commented on phdi/fhir/tabulation/tables.py
> +
Modified following your approach above

2022-11-02 18:05 UTC, bamader approved these changes
Looks great! Sorry for being a bum on this for so long.

2022-11-02 20:11 UTC, merged