Create the geocoding container
CDCgov/phdi pull request #90
Opened 2022-10-20 16:13 UTC by BradySkylight

This PR includes:
1- The container code to geocode addresses within a bundle or patient resource utilizing the PHDI SDK
2- Allows for smarty, census, or all geocoding methods - if all is selected then census and smarty are both completed
3- Tests to verify all the different possible pathways - success, errors, exceptions

2022-10-20 22:11 UTC, nickclyde approved these changes
This looks great! Awesome work Brady!

2022-10-21 14:40 UTC, DanPaseltiner requested changes
Thanks for this Brady! I think there are a couple things we should change before merging. Happy for discussion and/or push back though!

2022-10-21 14:40 UTC, DanPaseltiner commented on containers/phdi-ingestion/app/routers/fhir_geospatial.py
> +    del input["auth_token"]
I think should use the `.pop()` method here instead of `del` because if these keys are not present, which I believe would be the case when `"geocode_method"=="census"`, we will raise an error (example below).

```
Python 3.10.6 (main, Aug  8 2022, 19:28:58) [Clang 13.1.6 (clang-1316.0.21.2.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> test = {}
>>> del test["missing-key"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'missing-key'
>>> test.pop("missing-key", None)
>>> 
```

2022-10-21 14:40 UTC, DanPaseltiner commented on containers/phdi-ingestion/app/routers/fhir_geospatial.py
> +        geocode_client = CensusFhirGeocodeClient()
I'm a little confused about our use of `"all"` here. The docs state that when `"gecode_method" == "all"` we will geocode with both Smarty and the US Census. It looks to me that the current behavior is:

1. If `"gecode_method" == "smarty"` we will make a geocoding client for Smarty and use it appropriately.
2. If `"gecode_method" == "census"`  we will make a geocoding client for Census and use it appropriately.
3. If `"gecode_method" == "all"` we will first make a Smarty client, overwrite it with a Census client and then only geocode with the Census.

If I'm missing something subtle here I apologize. 

Additionally, I don't think we really need the `"all"` option, although it is a cool idea. Since the geocoding process (as currently written) replaces values in  `Patient.address` we would simply replace the result of work from the first geocoder with the result from the second. What do you think about this combined with modifying `GeocodeAddressInBundleInput`?

```suggestion
    input = dict(input)

    if input.get("geocode_method")  == "smarty" :
        required_values = ["auth_id", "auth_token"]
        search_result = search_for_required_values(input, required_values)
        if search_result != "All values were found.":
            response.status_code = status.HTTP_400_BAD_REQUEST
            return search_result
        geocode_client = SmartyFhirGeocodeClient(
            auth_id=input.get("auth_id"), auth_token=input.get("auth_token")
        )

    elif:
        geocode_client = CensusFhirGeocodeClient()
```

2022-10-21 14:40 UTC, DanPaseltiner commented on containers/phdi-ingestion/app/routers/fhir_linkage_link.py
Thank you for catching this! Definitely a typo I introduced.

2022-10-21 14:40 UTC, DanPaseltiner commented on containers/phdi-ingestion/tests/test_config.py
> +    os.environ.pop("CREDENTIAL_MANAGER", None)
Nice!

2022-10-21 14:40 UTC, DanPaseltiner commented on containers/phdi-ingestion/tests/test_fhir_geospatial.py
> +    assert actual_response.json() == expected_response
Is this test actually making a call to the US Census API? I'm not sure we want our unit tests to depend on services external to PHDI. Also, if the US Census makes a change to their addresses cleaning process could it cause this test to fail? What about mocking the geocoder client and testing for how it was called?

2022-10-21 14:40 UTC, DanPaseltiner commented on containers/phdi-ingestion/tests/test_fhir_geospatial.py
> +    os.environ.pop("AUTH_TOKEN", None)
Do we need to test the success case for Smarty?

2022-10-21 14:51 UTC, DanPaseltiner commented on containers/phdi-ingestion/app/routers/fhir_geospatial.py
> +    method and auth_id and auth_token are not supplied an HTTP 500 status code will
Looks like we are actually returning a 400. This might be a mistake I originally introduced.

2022-10-21 15:41 UTC, BradySkylight commented on containers/phdi-ingestion/app/routers/fhir_geospatial.py
> +    del input["auth_token"]
That makes sense and not sure how I didn't catch that.  I'll update this.

2022-10-21 15:44 UTC, BradySkylight commented on containers/phdi-ingestion/app/routers/fhir_geospatial.py
> +        geocode_client = CensusFhirGeocodeClient()
I had considered not adding the 'all' option as well and I did miss the fact that it's not making a call to the actual client until the end.  So, major miss on my part.  Now thinking about it, a user could potentially make two calls to the same geocoder if they wanted both...this is less efficient, but, we can always add the 'all' ability later down the road.

2022-10-21 15:45 UTC, BradySkylight commented on containers/phdi-ingestion/tests/test_fhir_geospatial.py
> +    assert actual_response.json() == expected_response
Yes, I need to mock this and I need to make a mocked test for Smarty as well.

2022-10-21 15:52 UTC, DanPaseltiner commented on containers/phdi-ingestion/tests/test_fhir_geospatial.py
> +    assert actual_response.json() == expected_response
The FHIR upload tests should have examples of very similar mocking that might be helpful.

2022-10-21 20:50 UTC, DanPaseltiner approved these changes
Approving now so I'm not blocking while on vacation, but I think we still need a test for a Smarty success.

2022-10-21 20:50 UTC, DanPaseltiner commented on containers/phdi-ingestion/tests/test_fhir_geospatial.py
> +
I think we are still missing a testing for a Smarty success.

2022-10-21 20:53 UTC, BradySkylight commented on containers/phdi-ingestion/tests/test_fhir_geospatial.py
> +
Nope, it's there on line 46-58

2022-10-21 20:53 UTC, merged